CREATE TABLE paralelo (
    prlid integer GENERATED BY DEFAULT AS IDENTITY,
    prlnombre varchar(10) NOT NULL,
    CONSTRAINT pk_paralelo PRIMARY KEY (prlid),
    CONSTRAINT uq_paralelo_prlnombre UNIQUE (prlnombre)
);

CREATE TABLE nivel_educativo (
    nedid integer GENERATED BY DEFAULT AS IDENTITY,
    nednombre varchar(50) NOT NULL,
    CONSTRAINT pk_nivel_educativo PRIMARY KEY (nedid),
    CONSTRAINT uq_nivel_educativo_nednombre UNIQUE (nednombre)
);

CREATE TABLE parentesco (
    pteid integer GENERATED BY DEFAULT AS IDENTITY,
    ptenombre varchar(50) NOT NULL,
    CONSTRAINT pk_parentesco PRIMARY KEY (pteid),
    CONSTRAINT uq_parentesco_ptenombre UNIQUE (ptenombre)
);

CREATE TABLE estado_civil (
    eciid integer GENERATED BY DEFAULT AS IDENTITY,
    ecinombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_civil PRIMARY KEY (eciid),
    CONSTRAINT uq_estado_civil_ecinombre UNIQUE (ecinombre)
);

CREATE TABLE instruccion (
    istid integer GENERATED BY DEFAULT AS IDENTITY,
    istnombre varchar(50) NOT NULL,
    CONSTRAINT pk_instruccion PRIMARY KEY (istid),
    CONSTRAINT uq_instruccion_istnombre UNIQUE (istnombre)
);

CREATE TABLE estado_matricula (
    emdid integer GENERATED BY DEFAULT AS IDENTITY,
    emdnombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_matricula PRIMARY KEY (emdid),
    CONSTRAINT uq_estado_matricula_emdnombre UNIQUE (emdnombre)
);

CREATE TABLE condicion_vivienda (
    cviid integer GENERATED BY DEFAULT AS IDENTITY,
    cvinombre varchar(80) NOT NULL,
    cviactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_condicion_vivienda PRIMARY KEY (cviid),
    CONSTRAINT uq_condicion_vivienda_cvinombre UNIQUE (cvinombre)
);

CREATE TABLE grupo_sanguineo (
    gsid integer GENERATED BY DEFAULT AS IDENTITY,
    gsnombre varchar(10) NOT NULL,
    gsactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_grupo_sanguineo PRIMARY KEY (gsid),
    CONSTRAINT uq_grupo_sanguineo_gsnombre UNIQUE (gsnombre)
);

CREATE TABLE atencion_medica (
    amid integer GENERATED BY DEFAULT AS IDENTITY,
    amnombre varchar(80) NOT NULL,
    amactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_atencion_medica PRIMARY KEY (amid),
    CONSTRAINT uq_atencion_medica_amnombre UNIQUE (amnombre)
);

CREATE TABLE tipo_condicion_salud (
    tcsid integer GENERATED BY DEFAULT AS IDENTITY,
    tcsnombre varchar(80) NOT NULL,
    tcsactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_condicion_salud PRIMARY KEY (tcsid),
    CONSTRAINT uq_tipo_condicion_salud_tcsnombre UNIQUE (tcsnombre)
);

CREATE TABLE seguro_medico (
    smid integer GENERATED BY DEFAULT AS IDENTITY,
    smnombre varchar(120) NOT NULL,
    smactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_seguro_medico PRIMARY KEY (smid),
    CONSTRAINT uq_seguro_medico_smnombre UNIQUE (smnombre)
);

CREATE TABLE tipo_embarazo (
    teid integer GENERATED BY DEFAULT AS IDENTITY,
    tenombre varchar(50) NOT NULL,
    teactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_embarazo PRIMARY KEY (teid),
    CONSTRAINT uq_tipo_embarazo_tenombre UNIQUE (tenombre)
);

CREATE TABLE tipo_parto (
    tpid integer GENERATED BY DEFAULT AS IDENTITY,
    tpnombre varchar(50) NOT NULL,
    tpactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_parto PRIMARY KEY (tpid),
    CONSTRAINT uq_tipo_parto_tpnombre UNIQUE (tpnombre)
);

CREATE TABLE documento_matricula (
    domid integer GENERATED BY DEFAULT AS IDENTITY,
    domnombre varchar(150) NOT NULL,
    domdescripcion varchar(250),
    domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO',
    domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO',
    domurl varchar(255),
    domplantilla_archivo varchar(255),
    domplantilla_extension varchar(10),
    domobligatorio boolean NOT NULL DEFAULT true,
    domactivo boolean NOT NULL DEFAULT true,
    domfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domfecha_modificacion timestamp,
    CONSTRAINT pk_documento_matricula PRIMARY KEY (domid),
    CONSTRAINT uq_documento_matricula_domnombre UNIQUE (domnombre),
    CONSTRAINT ck_documento_matricula_domtipo
        CHECK (domtipo IN ('ESTATICO', 'PLANTILLA')),
    CONSTRAINT ck_documento_matricula_domorigen
        CHECK (domorigen IN ('ARCHIVO', 'URL')),
    CONSTRAINT ck_documento_matricula_domplantilla_extension
        CHECK (
            domplantilla_extension IS NULL
            OR domplantilla_extension IN ('DOCX')
        ),
    CONSTRAINT ck_documento_matricula_contenido
        CHECK (
            (
                domtipo = 'ESTATICO'
                AND (
                    (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
                    OR
                    (domorigen = 'URL' AND domurl IS NOT NULL)
                )
                AND domplantilla_archivo IS NULL
            )
            OR
            (
                domtipo = 'PLANTILLA'
                AND domorigen = 'ARCHIVO'
                AND domplantilla_archivo IS NOT NULL
                AND domplantilla_extension = 'DOCX'
            )
        )
);

CREATE TABLE tipo_personal (
    tpid integer GENERATED BY DEFAULT AS IDENTITY,
    tpnombre varchar(50) NOT NULL,
    tpdescripcion varchar(150),
    tpestado boolean NOT NULL DEFAULT true,
    tpfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tpfecha_modificacion timestamp,
    CONSTRAINT pk_tipo_personal PRIMARY KEY (tpid),
    CONSTRAINT uq_tipo_personal_tpnombre UNIQUE (tpnombre)
);
