CREATE TABLE institucion (
    insid integer GENERATED BY DEFAULT AS IDENTITY,
    insnombre varchar(150) NOT NULL,
    insrazonsocial varchar(200),
    insruc varchar(13),
    inscodigoamie varchar(20),
    insdireccion varchar(250),
    instelefono varchar(20),
    inscorreoelectronico varchar(150),
    insrepresentantelegal varchar(150),
    CONSTRAINT pk_institucion PRIMARY KEY (insid),
    CONSTRAINT uq_institucion_insruc UNIQUE (insruc),
    CONSTRAINT uq_institucion_inscodigoamie UNIQUE (inscodigoamie)
);

CREATE TABLE periodo_lectivo (
    pleid integer GENERATED BY DEFAULT AS IDENTITY,
    pledescripcion varchar(20) NOT NULL,
    plefechainicio date NOT NULL,
    plefechafin date NOT NULL,
    pleactivo boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_periodo_lectivo PRIMARY KEY (pleid)
);

CREATE TABLE grado (
    graid integer GENERATED BY DEFAULT AS IDENTITY,
    nedid integer NOT NULL,
    granombre varchar(50) NOT NULL,
    CONSTRAINT pk_grado PRIMARY KEY (graid),
    CONSTRAINT fk_grado_nivel_educativo FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT uq_grado_nedid_granombre UNIQUE (nedid, granombre)
);

CREATE TABLE curso (
    curid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    graid integer NOT NULL,
    prlid integer NOT NULL,
    curestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_curso PRIMARY KEY (curid),
    CONSTRAINT fk_curso_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_curso_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_curso_paralelo FOREIGN KEY (prlid)
        REFERENCES paralelo (prlid),
    CONSTRAINT uq_curso_pleid_graid_prlid UNIQUE (pleid, graid, prlid)
);