CREATE TABLE persona (
    perid integer GENERATED BY DEFAULT AS IDENTITY,
    percedula varchar(10) NOT NULL,
    pernombres varchar(100) NOT NULL,
    perapellidos varchar(100) NOT NULL,
    pertelefono1 varchar(20),
    pertelefono2 varchar(20),
    percorreo varchar(150),
    persexo varchar(20),
    perfechanacimiento date,
    eciid integer,
    istid integer,
    perprofesion varchar(150),
    perocupacion varchar(150),
    perlugardetrabajo varchar(150),
    perhablaingles boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_persona PRIMARY KEY (perid),
    CONSTRAINT uq_persona_percedula UNIQUE (percedula),
    CONSTRAINT fk_persona_estado_civil FOREIGN KEY (eciid)
        REFERENCES estado_civil (eciid),
    CONSTRAINT fk_persona_instruccion FOREIGN KEY (istid)
        REFERENCES instruccion (istid)
);

CREATE TABLE personal (
    psnid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    psnfechacontratacion date NOT NULL,
    psnfechasalida date,
    psnestado boolean NOT NULL DEFAULT true,
    psnobservacion varchar(250),
    psnfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    psnfecha_modificacion timestamp,
    CONSTRAINT pk_personal PRIMARY KEY (psnid),
    CONSTRAINT fk_personal_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_personal_perid UNIQUE (perid)
);

CREATE TABLE asignacion_tipo_personal (
    atpid integer GENERATED BY DEFAULT AS IDENTITY,
    psnid integer NOT NULL,
    tpid integer NOT NULL,
    atpestado boolean NOT NULL DEFAULT true,
    atpfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    atpfecha_modificacion timestamp,
    CONSTRAINT pk_asignacion_tipo_personal PRIMARY KEY (atpid),
    CONSTRAINT fk_asignacion_tipo_personal_personal FOREIGN KEY (psnid)
        REFERENCES personal (psnid),
    CONSTRAINT fk_asignacion_tipo_personal_tipo_personal FOREIGN KEY (tpid)
        REFERENCES tipo_personal (tpid),
    CONSTRAINT uq_asignacion_tipo_personal_psnid_tpid UNIQUE (psnid, tpid)
);

CREATE TABLE estudiante (
    estid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    estlugarnacimiento varchar(150),
    estdireccion varchar(250),
    estparroquia varchar(100),
    estestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_estudiante PRIMARY KEY (estid),
    CONSTRAINT fk_estudiante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_estudiante_perid UNIQUE (perid)
);

CREATE TABLE estudiante_contexto_familiar (
    ecfid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    ecfconvivecon varchar(250),
    ecfnumerohermanos integer,
    ecfposicionhermanos varchar(50),
    ecffecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ecffecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_contexto_familiar PRIMARY KEY (ecfid),
    CONSTRAINT fk_estudiante_contexto_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT uq_estudiante_contexto_familiar_estid UNIQUE (estid)
);
CREATE TABLE estudiante_convive_con (
    eccid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    pteid integer NOT NULL,
    eccfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    eccfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_convive_con PRIMARY KEY (eccid),
    CONSTRAINT fk_estudiante_convive_con_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_convive_con_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_estudiante_convive_con_estid_pteid UNIQUE (estid, pteid)
);

CREATE TABLE estudiante_vivienda (
    estvid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    cviid integer NOT NULL,
    estvdescripcion varchar(500),
    estvluzelectrica boolean NOT NULL DEFAULT false,
    estvaguapotable boolean NOT NULL DEFAULT false,
    estvsshh boolean NOT NULL DEFAULT false,
    estvtelefono boolean NOT NULL DEFAULT false,
    estvcable boolean NOT NULL DEFAULT false,
    estvfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    estvfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_vivienda PRIMARY KEY (estvid),
    CONSTRAINT fk_estudiante_vivienda_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_vivienda_condicion_vivienda FOREIGN KEY (cviid)
        REFERENCES condicion_vivienda (cviid),
    CONSTRAINT uq_estudiante_vivienda_estid UNIQUE (estid)
);

CREATE TABLE estudiante_contexto_salud (
    ecsid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    gsid integer,
    ecstienediscapacidad boolean NOT NULL DEFAULT false,
    ecsdetallediscapacidad varchar(500),
    amid integer,
    ecsfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ecsfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_contexto_salud PRIMARY KEY (ecsid),
    CONSTRAINT fk_estudiante_contexto_salud_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_contexto_salud_grupo_sanguineo FOREIGN KEY (gsid)
        REFERENCES grupo_sanguineo (gsid),
    CONSTRAINT fk_estudiante_contexto_salud_atencion_medica FOREIGN KEY (amid)
        REFERENCES atencion_medica (amid),
    CONSTRAINT uq_estudiante_contexto_salud_estid UNIQUE (estid)
);

CREATE TABLE estudiante_condicion_salud (
    ecsaid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    tcsid integer NOT NULL,
    ecsadescripcion varchar(500) NOT NULL,
    ecsamedicamentos varchar(500),
    ecsaobservacion varchar(500),
    ecsavigente boolean NOT NULL DEFAULT true,
    ecsafecha_registro timestamp NOT NULL DEFAULT current_timestamp,
    ecsafecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_condicion_salud PRIMARY KEY (ecsaid),
    CONSTRAINT fk_estudiante_condicion_salud_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_condicion_salud_tipo FOREIGN KEY (tcsid)
        REFERENCES tipo_condicion_salud (tcsid)
);

CREATE TABLE estudiante_medicion_salud (
    emsid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    emspeso numeric(5,2) NOT NULL,
    emstalla numeric(4,2) NOT NULL,
    emsimc numeric(5,2) NOT NULL,
    emsfecha_medicion date NOT NULL,
    emsobservacion varchar(250),
    emsfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    emsfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_medicion_salud PRIMARY KEY (emsid),
    CONSTRAINT fk_estudiante_medicion_salud_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid)
);

CREATE TABLE estudiante_historia_vital (
    ehvid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    ehvedadmadre integer,
    ehvcomplicacionesembarazo varchar(500),
    ehvmedicacionembarazo varchar(500),
    teid integer,
    tpid integer,
    ehvdetalleembarazo varchar(1000),
    ehvpesonacer varchar(20),
    ehvtallanacer varchar(20),
    ehvedadcaminar varchar(50),
    ehvedadhablar varchar(50),
    ehvperiodolactancia varchar(50),
    ehvedadbiberon varchar(50),
    ehvedadcontrolesfinteres varchar(50),
    ehvfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ehvfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_historia_vital PRIMARY KEY (ehvid),
    CONSTRAINT fk_estudiante_historia_vital_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_historia_vital_tipo_embarazo FOREIGN KEY (teid)
        REFERENCES tipo_embarazo (teid),
    CONSTRAINT fk_estudiante_historia_vital_tipo_parto FOREIGN KEY (tpid)
        REFERENCES tipo_parto (tpid),
    CONSTRAINT uq_estudiante_historia_vital_estid UNIQUE (estid)
);

CREATE TABLE estudiante_contexto_academico (
    ecaid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    ecafechaingresoinstitucion date,
    ecaharepetidoanios boolean NOT NULL DEFAULT false,
    ecadetallerepeticion varchar(500),
    ecaasignaturaspreferencia varchar(500),
    ecaasignaturasdificultad varchar(500),
    ecaactividadesextras varchar(500),
    ecafecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ecafecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_contexto_academico PRIMARY KEY (ecaid),
    CONSTRAINT fk_estudiante_contexto_academico_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT uq_estudiante_contexto_academico_estid UNIQUE (estid)
);

CREATE TABLE familiar (
    famid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_familiar PRIMARY KEY (famid),
    CONSTRAINT fk_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_familiar_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_familiar_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_familiar_estid_perid_pteid UNIQUE (estid, perid, pteid)
);
