CREATE TABLE persona (
    perid integer GENERATED BY DEFAULT AS IDENTITY,
    percedula varchar(10) NOT NULL,
    pernombres varchar(100) NOT NULL,
    perapellidos varchar(100) NOT NULL,
    pertelefono1 varchar(20),
    pertelefono2 varchar(20),
    percorreo varchar(150),
    persexo varchar(20),
    CONSTRAINT pk_persona PRIMARY KEY (perid),
    CONSTRAINT uq_persona_percedula UNIQUE (percedula)
);

CREATE TABLE estudiante (
    estid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    estlugarnacimiento varchar(150),
    estdireccion varchar(250),
    estparroquia varchar(100),
    estestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_estudiante PRIMARY KEY (estid),
    CONSTRAINT fk_estudiante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_estudiante_perid UNIQUE (perid)
);

CREATE TABLE familiar (
    famid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    eciid integer,
    istid integer,
    famprofesion varchar(100),
    famlugardetrabajo varchar(150),
    famfechanacimiento date,
    CONSTRAINT pk_familiar PRIMARY KEY (famid),
    CONSTRAINT fk_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_familiar_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_familiar_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT fk_familiar_estado_civil FOREIGN KEY (eciid)
        REFERENCES estado_civil (eciid),
    CONSTRAINT fk_familiar_instruccion FOREIGN KEY (istid)
        REFERENCES instruccion (istid),
    CONSTRAINT uq_familiar_estid_perid_pteid UNIQUE (estid, perid, pteid)
);