CREATE TABLE tipo_matricula (
    tmaid integer GENERATED BY DEFAULT AS IDENTITY,
    tmanombre varchar(50) NOT NULL,
    tmadescripcion varchar(150),
    tmaestado boolean NOT NULL DEFAULT true,
    tmafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tmafecha_modificacion timestamp,
    CONSTRAINT pk_tipo_matricula PRIMARY KEY (tmaid),
    CONSTRAINT uq_tipo_matricula_tmanombre UNIQUE (tmanombre)
);

CREATE TABLE configuracion_matricula (
    cmid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    cmhabilitada boolean NOT NULL DEFAULT false,
    cmfechainicio date,
    cmfechafin date,
    cmhabilitadaextraordinaria boolean NOT NULL DEFAULT false,
    cmfechainicioextraordinaria date,
    cmfechafinextraordinaria date,
    cmobservacion varchar(250),
    cmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmfecha_modificacion timestamp,
    CONSTRAINT pk_configuracion_matricula PRIMARY KEY (cmid),
    CONSTRAINT fk_configuracion_matricula_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT uq_configuracion_matricula_pleid UNIQUE (pleid),
    CONSTRAINT ck_configuracion_matricula_fechas_ordinarias
        CHECK (
            cmfechainicio IS NULL
            OR cmfechafin IS NULL
            OR cmfechainicio <= cmfechafin
        ),
    CONSTRAINT ck_configuracion_matricula_fechas_extraordinarias
        CHECK (
            cmfechainicioextraordinaria IS NULL
            OR cmfechafinextraordinaria IS NULL
            OR cmfechainicioextraordinaria <= cmfechafinextraordinaria
        )
);

CREATE TABLE matricula (
    matid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    curid integer NOT NULL,
    matfecha date NOT NULL,
    matfoto varchar(255),
    emdid integer NOT NULL,
    tmaid integer NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (matid),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_matricula_estado_matricula FOREIGN KEY (emdid)
        REFERENCES estado_matricula (emdid),
    CONSTRAINT fk_matricula_tipo_matricula FOREIGN KEY (tmaid)
        REFERENCES tipo_matricula (tmaid),
    CONSTRAINT uq_matricula_estid_curid UNIQUE (estid, curid)
);

CREATE TABLE matricula_representante (
    mreid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_matricula_representante PRIMARY KEY (mreid),
    CONSTRAINT fk_matricula_representante_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_representante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_matricula_representante_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_matricula_representante_matid UNIQUE (matid)
);

CREATE TABLE matricula_recurso_tecnologico (
    mrtid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mrtinternet boolean NOT NULL DEFAULT false,
    mrtcomputador boolean NOT NULL DEFAULT false,
    mrtlaptop boolean NOT NULL DEFAULT false,
    mrttablet boolean NOT NULL DEFAULT false,
    mrtcelular boolean NOT NULL DEFAULT false,
    mrtimpresora boolean NOT NULL DEFAULT false,
    mrtfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_recurso_tecnologico PRIMARY KEY (mrtid),
    CONSTRAINT fk_matricula_recurso_tecnologico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_recurso_tecnologico_matid UNIQUE (matid)
);

CREATE TABLE matricula_seguro_medico (
    msmid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    smid integer NOT NULL,
    msmtelefono varchar(30),
    msmobservacion varchar(250),
    msmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    msmfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_seguro_medico PRIMARY KEY (msmid),
    CONSTRAINT fk_matricula_seguro_medico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_seguro_medico_seguro_medico FOREIGN KEY (smid)
        REFERENCES seguro_medico (smid),
    CONSTRAINT uq_matricula_seguro_medico_matid UNIQUE (matid)
);

CREATE TABLE matricula_facturacion (
    mfcid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mfcnombre varchar(150) NOT NULL,
    mfctipoidentificacion varchar(10) NOT NULL,
    mfcidentificacion varchar(13) NOT NULL,
    mfcdireccion varchar(250),
    mfccorreo varchar(150),
    mfctelefono varchar(20),
    mfcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mfcfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_facturacion PRIMARY KEY (mfcid),
    CONSTRAINT fk_matricula_facturacion_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_facturacion_matid UNIQUE (matid),
    CONSTRAINT ck_matricula_facturacion_tipo_identificacion
        CHECK (mfctipoidentificacion IN ('CEDULA', 'RUC'))
);

CREATE TABLE matricula_documento_generado (
    mdgid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgnombre varchar(180) NOT NULL,
    mdgruta_archivo varchar(255) NOT NULL,
    mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
    mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdghash varchar(128),
    mdgobservacion varchar(250),
    CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
    CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT ck_matricula_documento_generado_extension
        CHECK (mdgextension IN ('DOCX', 'PDF'))
);

CREATE TABLE matricula_aceptacion_documentos (
    madid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgid integer,
    madaceptado boolean NOT NULL DEFAULT false,
    madfecha_aceptacion timestamp,
    madobservacion varchar(250),
    CONSTRAINT pk_matricula_aceptacion_documentos PRIMARY KEY (madid),
    CONSTRAINT fk_matricula_aceptacion_documentos_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_aceptacion_documentos_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT fk_matricula_aceptacion_documentos_generado FOREIGN KEY (mdgid)
        REFERENCES matricula_documento_generado (mdgid),
    CONSTRAINT uq_matricula_aceptacion_documentos_matid_domid UNIQUE (matid, domid)
);
