CREATE TABLE matricula (
    matid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    curid integer NOT NULL,
    matfecha date NOT NULL,
    matfoto varchar(255),
    emdid integer NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (matid),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_matricula_estado_matricula FOREIGN KEY (emdid)
        REFERENCES estado_matricula (emdid),
    CONSTRAINT uq_matricula_estid_curid UNIQUE (estid, curid)
);

CREATE TABLE matricula_representante (
    mreid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_matricula_representante PRIMARY KEY (mreid),
    CONSTRAINT fk_matricula_representante_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_representante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_matricula_representante_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_matricula_representante_matid UNIQUE (matid)
);

CREATE TABLE matricula_recurso_tecnologico (
    mrtid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mrtinternet boolean NOT NULL DEFAULT false,
    mrtcomputador boolean NOT NULL DEFAULT false,
    mrtlaptop boolean NOT NULL DEFAULT false,
    mrttablet boolean NOT NULL DEFAULT false,
    mrtcelular boolean NOT NULL DEFAULT false,
    mrtfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_recurso_tecnologico PRIMARY KEY (mrtid),
    CONSTRAINT fk_matricula_recurso_tecnologico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_recurso_tecnologico_matid UNIQUE (matid)
);

CREATE TABLE matricula_facturacion (
    mfcid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mfcnombre varchar(150) NOT NULL,
    mfctipoidentificacion varchar(10) NOT NULL,
    mfcidentificacion varchar(13) NOT NULL,
    mfcdireccion varchar(250),
    mfccorreo varchar(150),
    mfctelefono varchar(20),
    mfcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mfcfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_facturacion PRIMARY KEY (mfcid),
    CONSTRAINT fk_matricula_facturacion_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_facturacion_matid UNIQUE (matid),
    CONSTRAINT ck_matricula_facturacion_tipo_identificacion
        CHECK (mfctipoidentificacion IN ('CEDULA', 'RUC'))
);

CREATE TABLE matricula_aceptacion_documentos (
    madid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    madaceptado boolean NOT NULL DEFAULT false,
    madfecha_aceptacion timestamp,
    madobservacion varchar(250),
    CONSTRAINT pk_matricula_aceptacion_documentos PRIMARY KEY (madid),
    CONSTRAINT fk_matricula_aceptacion_documentos_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_aceptacion_documentos_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT uq_matricula_aceptacion_documentos_matid_domid UNIQUE (matid, domid)
);
