CREATE TABLE usuario (
    usuid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    usunombre varchar(50) NOT NULL,
    usuclave varchar(255) NOT NULL,
    usuestado boolean NOT NULL DEFAULT false,
    usufecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    usufecha_modificacion timestamp,
    CONSTRAINT pk_usuario PRIMARY KEY (usuid),
    CONSTRAINT fk_usuario_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_usuario_perid UNIQUE (perid),
    CONSTRAINT uq_usuario_usunombre UNIQUE (usunombre)
);

CREATE TABLE usuario_temporal (
    utid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    utestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    utfecha_expiracion timestamp NOT NULL,
    utfecha_eliminacion timestamp,
    utmotivo_eliminacion varchar(250),
    utfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utfecha_modificacion timestamp,
    CONSTRAINT pk_usuario_temporal PRIMARY KEY (utid),
    CONSTRAINT fk_usuario_temporal_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_usuario_temporal_usuid UNIQUE (usuid),
    CONSTRAINT ck_usuario_temporal_estado
        CHECK (utestado IN ('ACTIVO', 'EXPIRADO', 'ELIMINADO', 'CONVERTIDO'))
);

CREATE TABLE representante_habilitacion_matricula (
    rhmid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    pleid integer NOT NULL,
    rhmestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    rhmfecha_expiracion timestamp,
    rhmfecha_uso timestamp,
    rhmfecha_anulacion timestamp,
    rhmmotivo_anulacion varchar(250),
    rhmusuid_secretaria integer,
    rhmobservacion varchar(250),
    rhmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rhmfecha_modificacion timestamp,
    CONSTRAINT pk_representante_habilitacion_matricula PRIMARY KEY (rhmid),
    CONSTRAINT fk_representante_habilitacion_matricula_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_representante_habilitacion_matricula_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_representante_habilitacion_matricula_secretaria FOREIGN KEY (rhmusuid_secretaria)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_representante_habilitacion_matricula_estado
        CHECK (rhmestado IN ('ACTIVO', 'USADO', 'EXPIRADO', 'ANULADO'))
);

CREATE UNIQUE INDEX uq_representante_habilitacion_matricula_activa
    ON representante_habilitacion_matricula (usuid, pleid)
    WHERE rhmestado = 'ACTIVO';

CREATE TABLE rol (
    rolid integer GENERATED BY DEFAULT AS IDENTITY,
    rolnombre varchar(50) NOT NULL,
    roldescripcion varchar(200),
    rolestado boolean NOT NULL DEFAULT true,
    rolfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    rolfecha_modificacion timestamp,
    CONSTRAINT pk_rol PRIMARY KEY (rolid),
    CONSTRAINT uq_rol_rolnombre UNIQUE (rolnombre)
);
CREATE TABLE usuario_rol (
    usrid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    rolid integer NOT NULL,
    usrestado boolean NOT NULL DEFAULT true,
    usrfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    usrfecha_modificacion timestamp,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usrid),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (rolid)
        REFERENCES rol (rolid),
    CONSTRAINT uq_usuario_rol_usuid_rolid UNIQUE (usuid, rolid)
);
CREATE TABLE permiso (
    prmid integer GENERATED BY DEFAULT AS IDENTITY,
    prmnombre varchar(100) NOT NULL,
    prmcodigo varchar(100) NOT NULL,
    prmdescripcion varchar(200),
    prmestado boolean NOT NULL DEFAULT true,
    prmfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    prmfecha_modificacion timestamp,
    CONSTRAINT pk_permiso PRIMARY KEY (prmid),
    CONSTRAINT uq_permiso_prmnombre UNIQUE (prmnombre),
    CONSTRAINT uq_permiso_prmcodigo UNIQUE (prmcodigo)
);
CREATE TABLE rol_permiso (
    rpeid integer GENERATED BY DEFAULT AS IDENTITY,
    rolid integer NOT NULL,
    prmid integer NOT NULL,
    rpeestado boolean NOT NULL DEFAULT true,
    rpefecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    rpefecha_modificacion timestamp,
    CONSTRAINT pk_rol_permiso PRIMARY KEY (rpeid),
    CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (rolid)
        REFERENCES rol (rolid),
    CONSTRAINT fk_rol_permiso_permiso FOREIGN KEY (prmid)
        REFERENCES permiso (prmid),
    CONSTRAINT uq_rol_permiso_rolid_prmid UNIQUE (rolid, prmid)
);
