-- Estructura academica y asistencia.
--
-- Este script define las materias por curso, sus docentes, calendario de
-- asistencia, sesiones por hora, registros de asistencia y justificaciones.
-- No incluye el modulo de novedades.

CREATE TABLE area_academica (
    areaid integer GENERATED BY DEFAULT AS IDENTITY,
    areanombre varchar(100) NOT NULL,
    areaestado boolean NOT NULL DEFAULT true,
    areafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    areafecha_modificacion timestamp,
    CONSTRAINT pk_area_academica PRIMARY KEY (areaid),
    CONSTRAINT uq_area_academica_areanombre UNIQUE (areanombre)
);

CREATE TABLE asignatura (
    asgid integer GENERATED BY DEFAULT AS IDENTITY,
    areaid integer NOT NULL,
    asgnombre varchar(100) NOT NULL,
    asgestado boolean NOT NULL DEFAULT true,
    asgfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    asgfecha_modificacion timestamp,
    CONSTRAINT pk_asignatura PRIMARY KEY (asgid),
    CONSTRAINT fk_asignatura_area_academica FOREIGN KEY (areaid)
        REFERENCES area_academica (areaid),
    CONSTRAINT uq_asignatura_areaid_asgnombre UNIQUE (areaid, asgnombre)
);

CREATE TABLE materia_curso (
    mtcid integer GENERATED BY DEFAULT AS IDENTITY,
    curid integer NOT NULL,
    asgid integer NOT NULL,
    mtcfecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    mtcfecha_fin date,
    mtcorden integer,
    mtcestado boolean NOT NULL DEFAULT true,
    mtcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtcfecha_modificacion timestamp,
    CONSTRAINT pk_materia_curso PRIMARY KEY (mtcid),
    CONSTRAINT fk_materia_curso_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_materia_curso_asignatura FOREIGN KEY (asgid)
        REFERENCES asignatura (asgid),
    CONSTRAINT ck_materia_curso_fechas
        CHECK (
            mtcfecha_fin IS NULL
            OR mtcfecha_fin >= mtcfecha_inicio
        )
);

CREATE UNIQUE INDEX uq_materia_curso_activa
    ON materia_curso (curid, asgid)
    WHERE mtcestado = true;

CREATE TABLE materia_curso_docente (
    mcdid integer GENERATED BY DEFAULT AS IDENTITY,
    mtcid integer NOT NULL,
    perid integer NOT NULL,
    mcdfecha_inicio date NOT NULL DEFAULT CURRENT_DATE,
    mcdfecha_fin date,
    mcdestado boolean NOT NULL DEFAULT true,
    mcdfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mcdfecha_modificacion timestamp,
    CONSTRAINT pk_materia_curso_docente PRIMARY KEY (mcdid),
    CONSTRAINT fk_materia_curso_docente_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_materia_curso_docente_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_materia_curso_docente_mcdid_mtcid UNIQUE (mcdid, mtcid),
    CONSTRAINT ck_materia_curso_docente_fechas
        CHECK (
            mcdfecha_fin IS NULL
            OR mcdfecha_fin >= mcdfecha_inicio
        )
);

CREATE UNIQUE INDEX uq_materia_curso_docente_activo
    ON materia_curso_docente (mtcid, perid)
    WHERE mcdestado = true;

CREATE TABLE configuracion_asistencia (
    coaid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    coafecha_inicio_clases date NOT NULL,
    coafecha_fin_clases date NOT NULL,
    coaobservacion varchar(250),
    usuid_registro integer NOT NULL,
    coafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    coafecha_modificacion timestamp,
    CONSTRAINT pk_configuracion_asistencia PRIMARY KEY (coaid),
    CONSTRAINT fk_configuracion_asistencia_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_configuracion_asistencia_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_configuracion_asistencia_pleid UNIQUE (pleid),
    CONSTRAINT ck_configuracion_asistencia_fechas
        CHECK (coafecha_fin_clases >= coafecha_inicio_clases)
);

ALTER TABLE matricula
ADD COLUMN matfecha_retiro date,
ADD COLUMN matmotivo_retiro varchar(250),
ADD COLUMN matfecha_modificacion timestamp;

ALTER TABLE matricula
ADD CONSTRAINT ck_matricula_fecha_retiro
CHECK (
    matfecha_retiro IS NULL
    OR matfecha_retiro >= matfecha
);

CREATE TABLE matricula_movimiento (
    mmoid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mmotipo varchar(30) NOT NULL,
    mmofecha date NOT NULL,
    mmomotivo varchar(250),
    usuid integer,
    mmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_matricula_movimiento PRIMARY KEY (mmoid),
    CONSTRAINT fk_matricula_movimiento_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_movimiento_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_matricula_movimiento_tipo
        CHECK (mmotipo IN ('ACTIVACION', 'RETIRO', 'REINGRESO', 'CORRECCION'))
);

CREATE TABLE calendario_asistencia (
    caid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    cafecha date NOT NULL,
    catipo_jornada varchar(20) NOT NULL DEFAULT 'NORMAL',
    cahabilitado boolean NOT NULL DEFAULT true,
    cahora_limite integer,
    caobservacion varchar(250),
    usuid_registro integer NOT NULL,
    cafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cafecha_modificacion timestamp,
    CONSTRAINT pk_calendario_asistencia PRIMARY KEY (caid),
    CONSTRAINT fk_calendario_asistencia_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_calendario_asistencia_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_calendario_asistencia_pleid_fecha UNIQUE (pleid, cafecha),
    CONSTRAINT ck_calendario_asistencia_tipo
        CHECK (catipo_jornada IN ('NORMAL', 'REDUCIDA', 'SUSPENDIDA', 'ESPECIAL')),
    CONSTRAINT ck_calendario_asistencia_hora_limite
        CHECK (
            cahora_limite IS NULL
            OR cahora_limite BETWEEN 1 AND 7
        ),
    CONSTRAINT ck_calendario_asistencia_tipo_hora
        CHECK (
            (
                catipo_jornada = 'NORMAL'
                AND cahabilitado = true
                AND (cahora_limite IS NULL OR cahora_limite = 7)
            )
            OR (
                catipo_jornada = 'REDUCIDA'
                AND cahabilitado = true
                AND cahora_limite BETWEEN 1 AND 6
            )
            OR (
                catipo_jornada = 'SUSPENDIDA'
                AND cahabilitado = false
                AND cahora_limite IS NULL
            )
            OR (
                catipo_jornada = 'ESPECIAL'
                AND cahabilitado = true
                AND (cahora_limite IS NULL OR cahora_limite BETWEEN 1 AND 7)
            )
        )
);

CREATE TABLE calendario_asistencia_detalle (
    cadid integer GENERATED BY DEFAULT AS IDENTITY,
    caid integer NOT NULL,
    curid integer NOT NULL,
    cadnumero_hora integer NOT NULL,
    cadhabilitado boolean NOT NULL DEFAULT true,
    cadobservacion varchar(250),
    CONSTRAINT pk_calendario_asistencia_detalle PRIMARY KEY (cadid),
    CONSTRAINT fk_calendario_asistencia_detalle_calendario FOREIGN KEY (caid)
        REFERENCES calendario_asistencia (caid),
    CONSTRAINT fk_calendario_asistencia_detalle_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT uq_calendario_asistencia_detalle_curso_hora
        UNIQUE (caid, curid, cadnumero_hora),
    CONSTRAINT ck_calendario_asistencia_detalle_hora
        CHECK (cadnumero_hora BETWEEN 1 AND 7)
);

CREATE TABLE sesion_clase (
    sclid integer GENERATED BY DEFAULT AS IDENTITY,
    caid integer NOT NULL,
    mtcid integer NOT NULL,
    mcdid integer NOT NULL,
    sclnumero_hora integer NOT NULL,
    sclestado varchar(20) NOT NULL DEFAULT 'REGISTRADA',
    sclobservacion varchar(250),
    usuid_registro integer NOT NULL,
    sclfecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_anulacion integer,
    sclfecha_anulacion timestamp,
    sclmotivo_anulacion varchar(250),
    CONSTRAINT pk_sesion_clase PRIMARY KEY (sclid),
    CONSTRAINT fk_sesion_clase_calendario FOREIGN KEY (caid)
        REFERENCES calendario_asistencia (caid),
    CONSTRAINT fk_sesion_clase_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_sesion_clase_materia_docente FOREIGN KEY (mcdid, mtcid)
        REFERENCES materia_curso_docente (mcdid, mtcid),
    CONSTRAINT fk_sesion_clase_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_sesion_clase_usuario_anulacion FOREIGN KEY (usuid_anulacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_sesion_clase_hora
        CHECK (sclnumero_hora BETWEEN 1 AND 7),
    CONSTRAINT ck_sesion_clase_estado
        CHECK (sclestado IN ('REGISTRADA', 'CERRADA', 'ANULADA')),
    CONSTRAINT ck_sesion_clase_anulacion
        CHECK (
            sclestado <> 'ANULADA'
            OR (
                usuid_anulacion IS NOT NULL
                AND sclfecha_anulacion IS NOT NULL
                AND NULLIF(trim(sclmotivo_anulacion), '') IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX uq_sesion_clase_materia_dia_hora_activa
    ON sesion_clase (mtcid, caid, sclnumero_hora)
    WHERE sclestado <> 'ANULADA';

CREATE TABLE justificacion_asistencia (
    jaid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    matid integer,
    sclid integer,
    jafecha_inicio date NOT NULL,
    jafecha_fin date NOT NULL,
    jatipo varchar(20) NOT NULL DEFAULT 'DIA',
    jamotivo varchar(250) NOT NULL,
    jaarchivo varchar(255),
    jaobservacion varchar(250),
    jaestado varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    jausuid_solicita integer,
    jausuid_revisa integer,
    jaobservacion_revision varchar(250),
    jafecha_solicitud timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    jafecha_revision timestamp,
    jausuid_anulacion integer,
    jafecha_anulacion timestamp,
    jamotivo_anulacion varchar(250),
    CONSTRAINT pk_justificacion_asistencia PRIMARY KEY (jaid),
    CONSTRAINT fk_justificacion_asistencia_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_justificacion_asistencia_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_justificacion_asistencia_sesion FOREIGN KEY (sclid)
        REFERENCES sesion_clase (sclid),
    CONSTRAINT fk_justificacion_asistencia_usuario_solicita FOREIGN KEY (jausuid_solicita)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_justificacion_asistencia_usuario_revisa FOREIGN KEY (jausuid_revisa)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_justificacion_asistencia_usuario_anulacion FOREIGN KEY (jausuid_anulacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_justificacion_asistencia_fechas
        CHECK (jafecha_fin >= jafecha_inicio),
    CONSTRAINT ck_justificacion_asistencia_tipo
        CHECK (jatipo IN ('DIA', 'HORA', 'RANGO')),
    CONSTRAINT ck_justificacion_asistencia_estado
        CHECK (jaestado IN ('PENDIENTE', 'APROBADA', 'RECHAZADA', 'ANULADA')),
    CONSTRAINT ck_justificacion_asistencia_anulacion
        CHECK (
            jaestado <> 'ANULADA'
            OR (
                jausuid_anulacion IS NOT NULL
                AND jafecha_anulacion IS NOT NULL
                AND NULLIF(trim(jamotivo_anulacion), '') IS NOT NULL
            )
        )
);

CREATE TABLE asistencia_estudiante (
    aesid integer GENERATED BY DEFAULT AS IDENTITY,
    sclid integer NOT NULL,
    estid integer NOT NULL,
    aesestado varchar(30) NOT NULL DEFAULT 'ASISTENCIA',
    aesobservacion varchar(250),
    jaid integer,
    usuid_registro integer NOT NULL,
    aesfecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_modificacion integer,
    aesfecha_modificacion timestamp,
    CONSTRAINT pk_asistencia_estudiante PRIMARY KEY (aesid),
    CONSTRAINT fk_asistencia_estudiante_sesion FOREIGN KEY (sclid)
        REFERENCES sesion_clase (sclid),
    CONSTRAINT fk_asistencia_estudiante_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_asistencia_estudiante_justificacion FOREIGN KEY (jaid)
        REFERENCES justificacion_asistencia (jaid),
    CONSTRAINT fk_asistencia_estudiante_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_asistencia_estudiante_usuario_modificacion FOREIGN KEY (usuid_modificacion)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_asistencia_estudiante_sclid_estid UNIQUE (sclid, estid),
    CONSTRAINT ck_asistencia_estudiante_estado
        CHECK (aesestado IN ('ASISTENCIA', 'ATRASO', 'FALTA_JUSTIFICADA', 'FALTA_INJUSTIFICADA')),
    CONSTRAINT ck_asistencia_estudiante_justificacion
        CHECK (
            aesestado IN ('FALTA_JUSTIFICADA', 'FALTA_INJUSTIFICADA')
            OR jaid IS NULL
        )
);

CREATE INDEX ix_matricula_curid_fechas
    ON matricula (curid, matfecha, matfecha_retiro);

CREATE INDEX ix_materia_curso_curid
    ON materia_curso (curid);

CREATE INDEX ix_materia_curso_docente_perid_estado
    ON materia_curso_docente (perid, mcdestado);

CREATE INDEX ix_calendario_asistencia_pleid_fecha
    ON calendario_asistencia (pleid, cafecha);

CREATE INDEX ix_sesion_clase_caid_hora
    ON sesion_clase (caid, sclnumero_hora);

CREATE INDEX ix_asistencia_estudiante_estid
    ON asistencia_estudiante (estid);

CREATE INDEX ix_justificacion_asistencia_estid_fechas
    ON justificacion_asistencia (estid, jafecha_inicio, jafecha_fin);

CREATE VIEW vw_materia_curso AS
SELECT
    mc.mtcid,
    mc.curid,
    mc.asgid,
    c.pleid,
    c.graid,
    c.prlid,
    a.areaid,
    aa.areanombre,
    a.asgnombre,
    g.granombre,
    p.prlnombre,
    CASE
        WHEN paralelos.total_paralelos > 1
            THEN a.asgnombre || ' ' || g.granombre || p.prlnombre
        ELSE a.asgnombre || ' ' || g.granombre
    END AS mtcnombre_mostrar,
    mc.mtcfecha_inicio,
    mc.mtcfecha_fin,
    mc.mtcorden,
    mc.mtcestado
FROM materia_curso mc
INNER JOIN asignatura a ON a.asgid = mc.asgid
INNER JOIN area_academica aa ON aa.areaid = a.areaid
INNER JOIN curso c ON c.curid = mc.curid
INNER JOIN grado g ON g.graid = c.graid
INNER JOIN paralelo p ON p.prlid = c.prlid
INNER JOIN (
    SELECT
        pleid,
        graid,
        COUNT(*) AS total_paralelos
    FROM curso
    WHERE curestado = true
    GROUP BY pleid, graid
) paralelos ON paralelos.pleid = c.pleid
            AND paralelos.graid = c.graid;

CREATE VIEW vw_asistencia_resumen_diario AS
SELECT
    ae.estid,
    ca.pleid,
    ca.cafecha,
    CASE
        WHEN COUNT(*) FILTER (
            WHERE ae.aesestado IN ('ATRASO', 'FALTA_JUSTIFICADA', 'FALTA_INJUSTIFICADA')
        ) > 0
            THEN 'ALERTA'
        ELSE 'OK'
    END AS resumen_estado,
    COUNT(*) FILTER (WHERE ae.aesestado = 'ASISTENCIA') AS total_asistencias,
    COUNT(*) FILTER (WHERE ae.aesestado = 'ATRASO') AS total_atrasos,
    COUNT(*) FILTER (WHERE ae.aesestado = 'FALTA_JUSTIFICADA') AS total_faltas_justificadas,
    COUNT(*) FILTER (WHERE ae.aesestado = 'FALTA_INJUSTIFICADA') AS total_faltas_injustificadas
FROM asistencia_estudiante ae
INNER JOIN sesion_clase sc ON sc.sclid = ae.sclid
INNER JOIN calendario_asistencia ca ON ca.caid = sc.caid
WHERE sc.sclestado <> 'ANULADA'
GROUP BY ae.estid, ca.pleid, ca.cafecha;

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
SELECT *
FROM (
    VALUES
        ('Asistencia - calendario', 'asistencia.calendario.gestionar', 'Gestion de dias, jornadas y horas habilitadas para asistencia', true),
        ('Asistencia - registrar', 'asistencia.registrar', 'Registro docente de asistencia por materia y hora', true),
        ('Asistencia - supervisar', 'asistencia.supervisar', 'Supervision y anulacion de sesiones de asistencia', true),
        ('Justificaciones - gestionar', 'justificaciones.gestionar', 'Registro, aprobacion, rechazo y anulacion de justificaciones', true),
        ('Asistencia - propia', 'asistencia.ver_propia', 'Consulta de asistencia propia del estudiante', true),
        ('Asistencia - representante', 'asistencia.representante.ver', 'Consulta de asistencia de estudiantes representados', true)
) AS source (prmnombre, prmcodigo, prmdescripcion, prmestado)
WHERE NOT EXISTS (
    SELECT 1
    FROM permiso p
    WHERE p.prmcodigo = source.prmcodigo
);

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'asistencia.calendario.gestionar',
    'asistencia.registrar',
    'asistencia.supervisar',
    'justificaciones.gestionar',
    'asistencia.ver_propia',
    'asistencia.representante.ver'
)
WHERE r.rolnombre = 'Administrador'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'asistencia.calendario.gestionar',
    'asistencia.supervisar',
    'justificaciones.gestionar'
)
WHERE r.rolnombre IN ('Secretaria', 'Coordinador', 'Inspector')
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'asistencia.registrar'
WHERE r.rolnombre = 'Docente'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'asistencia.ver_propia'
WHERE r.rolnombre = 'Estudiante'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'asistencia.representante.ver'
WHERE r.rolnombre = 'Representante'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );
