-- Migracion para normalizar estudiante_contexto_familiar.ecfconvivecon.
-- Ejecutar solo en bases ya existentes. En bases nuevas, la tabla se crea desde
-- 03_personas.sql o desde el consolidado sgeap.sql.

CREATE TABLE IF NOT EXISTS estudiante_convive_con (
    eccid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    pteid integer NOT NULL,
    eccfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    eccfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_convive_con PRIMARY KEY (eccid),
    CONSTRAINT fk_estudiante_convive_con_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_convive_con_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_estudiante_convive_con_estid_pteid UNIQUE (estid, pteid)
);

INSERT INTO estudiante_convive_con (estid, pteid)
SELECT
    ecf.estid,
    p.pteid
FROM estudiante_contexto_familiar ecf
CROSS JOIN LATERAL regexp_split_to_table(COALESCE(ecf.ecfconvivecon, ''), '\s*,\s*') AS convive(nombre)
INNER JOIN parentesco p
    ON LOWER(TRIM(p.ptenombre)) = CASE
        WHEN LOWER(TRIM(convive.nombre)) IN ('hermano', 'hermana') THEN 'hermano/a'
        ELSE LOWER(TRIM(convive.nombre))
    END
WHERE TRIM(convive.nombre) <> ''
ON CONFLICT (estid, pteid) DO NOTHING;
