-- Soporte para usuarios temporales de representantes en matricula de alumnos nuevos.
-- Ejecutar en bases existentes despues de database/scripts/05_seguridad.sql.

CREATE TABLE IF NOT EXISTS usuario_temporal (
    utid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    utestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    utfecha_expiracion timestamp NOT NULL,
    utfecha_eliminacion timestamp,
    utmotivo_eliminacion varchar(250),
    utfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    utfecha_modificacion timestamp,
    CONSTRAINT pk_usuario_temporal PRIMARY KEY (utid),
    CONSTRAINT fk_usuario_temporal_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_usuario_temporal_usuid UNIQUE (usuid),
    CONSTRAINT ck_usuario_temporal_estado
        CHECK (utestado IN ('ACTIVO', 'EXPIRADO', 'ELIMINADO', 'CONVERTIDO'))
);

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
SELECT *
FROM (
    VALUES
        ('Usuarios temporales', 'usuarios_temporales.gestionar', 'Creacion y anulacion de accesos temporales para representantes', true),
        ('Matricula temporal - ver', 'matricula_temporal.ver', 'Acceso del representante temporal a su proceso de matricula', true),
        ('Matricula temporal - editar', 'matricula_temporal.editar', 'Edicion de datos del proceso de matricula temporal', true),
        ('Matricula temporal - enviar', 'matricula_temporal.enviar', 'Envio de la solicitud de matricula temporal', true)
) AS source (prmnombre, prmcodigo, prmdescripcion, prmestado)
WHERE NOT EXISTS (
    SELECT 1
    FROM permiso p
    WHERE p.prmcodigo = source.prmcodigo
);

INSERT INTO rol (rolnombre, roldescripcion, rolestado)
SELECT
    'Representante temporal',
    'Acceso limitado para representantes durante la matricula de alumnos nuevos',
    true
WHERE NOT EXISTS (
    SELECT 1
    FROM rol
    WHERE rolnombre = 'Representante temporal'
);

INSERT INTO rol (rolnombre, roldescripcion, rolestado)
SELECT
    'Secretaria',
    'Gestion operativa de personas, estudiantes, matriculas y accesos temporales',
    true
WHERE NOT EXISTS (
    SELECT 1
    FROM rol
    WHERE rolnombre = 'Secretaria'
);

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'matricula_temporal.ver',
    'matricula_temporal.editar',
    'matricula_temporal.enviar'
)
WHERE r.rolnombre = 'Representante temporal'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'usuarios_temporales.gestionar'
WHERE r.rolnombre = 'Administrador'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'dashboard.ver',
    'personas.gestionar',
    'estudiantes.gestionar',
    'matriculas.gestionar',
    'usuarios_temporales.gestionar'
)
WHERE r.rolnombre = 'Secretaria'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );
