CREATE TABLE IF NOT EXISTS representante_habilitacion_matricula (
    rhmid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    pleid integer NOT NULL,
    rhmestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    rhmfecha_expiracion timestamp,
    rhmfecha_uso timestamp,
    rhmfecha_anulacion timestamp,
    rhmmotivo_anulacion varchar(250),
    rhmusuid_secretaria integer,
    rhmobservacion varchar(250),
    rhmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rhmfecha_modificacion timestamp,
    CONSTRAINT pk_representante_habilitacion_matricula PRIMARY KEY (rhmid),
    CONSTRAINT fk_representante_habilitacion_matricula_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_representante_habilitacion_matricula_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_representante_habilitacion_matricula_secretaria FOREIGN KEY (rhmusuid_secretaria)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_representante_habilitacion_matricula_estado
        CHECK (rhmestado IN ('ACTIVO', 'USADO', 'EXPIRADO', 'ANULADO'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_representante_habilitacion_matricula_activa
    ON representante_habilitacion_matricula (usuid, pleid)
    WHERE rhmestado = 'ACTIVO';

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
SELECT 'Representante - matricula nueva', 'representante.matricula_nueva', 'Acceso habilitado por secretaria para agregar un nuevo estudiante', true
WHERE NOT EXISTS (
    SELECT 1
    FROM permiso
    WHERE prmcodigo = 'representante.matricula_nueva'
);

INSERT INTO rol (rolnombre, roldescripcion, rolestado)
SELECT 'Representante matricula nueva', 'Acceso puntual para que un representante agregue un nuevo estudiante', true
WHERE NOT EXISTS (
    SELECT 1
    FROM rol
    WHERE rolnombre = 'Representante matricula nueva'
);

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'representante.matricula_nueva'
WHERE r.rolnombre = 'Representante matricula nueva'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );
