-- Configuracion de rango real de clases para asistencia.
-- Puede ejecutarse varias veces sin duplicar la estructura.

CREATE TABLE IF NOT EXISTS configuracion_asistencia (
    coaid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    coafecha_inicio_clases date NOT NULL,
    coafecha_fin_clases date NOT NULL,
    coaobservacion varchar(250),
    usuid_registro integer NOT NULL,
    coafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    coafecha_modificacion timestamp,
    CONSTRAINT pk_configuracion_asistencia PRIMARY KEY (coaid),
    CONSTRAINT fk_configuracion_asistencia_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_configuracion_asistencia_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_configuracion_asistencia_pleid UNIQUE (pleid),
    CONSTRAINT ck_configuracion_asistencia_fechas
        CHECK (coafecha_fin_clases >= coafecha_inicio_clases)
);
