-- Registro de novedades estudiantiles.
--
-- Las novedades reutilizan la matricula para identificar al estudiante dentro
-- del periodo/curso, y sesion_clase solo cuando el hecho ocurre en hora clase.

CREATE TABLE tipo_novedad (
    tnoid integer GENERATED BY DEFAULT AS IDENTITY,
    tnonombre varchar(120) NOT NULL,
    tnodescripcion varchar(250),
    tnogravedad varchar(20) NOT NULL DEFAULT 'LEVE',
    tnoestado boolean NOT NULL DEFAULT true,
    tnofecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tnofecha_modificacion timestamp,
    CONSTRAINT pk_tipo_novedad PRIMARY KEY (tnoid),
    CONSTRAINT uq_tipo_novedad_nombre UNIQUE (tnonombre),
    CONSTRAINT ck_tipo_novedad_gravedad
        CHECK (tnogravedad IN ('LEVE', 'MEDIA', 'GRAVE'))
);

CREATE TABLE novedad_estudiante (
    noeid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    sclid integer,
    tnoid integer,
    noetipo_contexto varchar(30) NOT NULL DEFAULT 'CLASE',
    noefecha date NOT NULL,
    noehora time,
    noeubicacion varchar(120),
    noedescripcion text NOT NULL,
    noeestado varchar(20) NOT NULL DEFAULT 'REGISTRADA',
    usuid_registro integer NOT NULL,
    noefecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_anulacion integer,
    noefecha_anulacion timestamp,
    noemotivo_anulacion varchar(250),
    CONSTRAINT pk_novedad_estudiante PRIMARY KEY (noeid),
    CONSTRAINT fk_novedad_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_novedad_sesion FOREIGN KEY (sclid)
        REFERENCES sesion_clase (sclid),
    CONSTRAINT fk_novedad_tipo FOREIGN KEY (tnoid)
        REFERENCES tipo_novedad (tnoid),
    CONSTRAINT fk_novedad_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_novedad_usuario_anulacion FOREIGN KEY (usuid_anulacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_novedad_contexto
        CHECK (noetipo_contexto IN ('CLASE', 'RECREO', 'ENTRADA', 'SALIDA', 'PATIO', 'BAR', 'EVENTO', 'OTRO')),
    CONSTRAINT ck_novedad_estado
        CHECK (noeestado IN ('REGISTRADA', 'ANULADA')),
    CONSTRAINT ck_novedad_sesion_contexto
        CHECK (
            (noetipo_contexto = 'CLASE' AND sclid IS NOT NULL)
            OR
            (noetipo_contexto <> 'CLASE' AND sclid IS NULL)
        ),
    CONSTRAINT ck_novedad_anulacion
        CHECK (
            noeestado <> 'ANULADA'
            OR (
                usuid_anulacion IS NOT NULL
                AND noefecha_anulacion IS NOT NULL
                AND NULLIF(trim(noemotivo_anulacion), '') IS NOT NULL
            )
        )
);

CREATE INDEX ix_novedad_estudiante_matricula
    ON novedad_estudiante (matid);

CREATE INDEX ix_novedad_estudiante_sesion
    ON novedad_estudiante (sclid);

CREATE INDEX ix_novedad_estudiante_tipo
    ON novedad_estudiante (tnoid);

CREATE INDEX ix_novedad_estudiante_fecha
    ON novedad_estudiante (noefecha);
