-- Modulo de calificaciones.
--
-- Este script inicia la estructura del motor de evaluacion definido en
-- docs/logica-calificaciones.md. La configuracion vive por periodo lectivo y
-- perfil; los resultados se guardan como snapshots calculados para reportes.

CREATE TABLE perfil_calificacion (
    pcaid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    pcaid_origen integer,
    pcanombre varchar(120) NOT NULL,
    pcadescripcion varchar(250),
    pcaversion integer NOT NULL DEFAULT 1,
    pcaestado varchar(20) NOT NULL DEFAULT 'BORRADOR',
    pcatipo_base varchar(30) NOT NULL DEFAULT 'CUANTITATIVO',
    pcavigencia_desde date NOT NULL,
    pcavigencia_hasta date,
    pcaminima numeric(5,2),
    pcamaxima numeric(5,2),
    pcaaprobacion numeric(5,2),
    pcadecimales integer NOT NULL DEFAULT 2,
    pcametodo_decimal varchar(20) NOT NULL DEFAULT 'REDONDEO',
    pcapromedia_final boolean NOT NULL DEFAULT true,
    pcaaplica_promocion boolean NOT NULL DEFAULT true,
    pcamotivo_version varchar(250),
    usuid_creacion integer NOT NULL,
    usuid_autorizacion integer,
    pcafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pcafecha_modificacion timestamp,
    CONSTRAINT pk_perfil_calificacion PRIMARY KEY (pcaid),
    CONSTRAINT fk_pca_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_pca_origen FOREIGN KEY (pcaid_origen)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT fk_pca_usuario_creacion FOREIGN KEY (usuid_creacion)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_pca_usuario_autorizacion FOREIGN KEY (usuid_autorizacion)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_pca_id_periodo UNIQUE (pcaid, pleid),
    CONSTRAINT uq_pca_periodo_nombre_version UNIQUE (pleid, pcanombre, pcaversion),
    CONSTRAINT ck_pca_estado
        CHECK (pcaestado IN ('BORRADOR', 'ACTIVA', 'EN_REVISION', 'BLOQUEADA', 'ARCHIVADA')),
    CONSTRAINT ck_pca_tipo_base
        CHECK (pcatipo_base IN ('CUANTITATIVO', 'CUALITATIVO', 'AMBITOS_DESTREZAS')),
    CONSTRAINT ck_pca_fechas
        CHECK (pcavigencia_hasta IS NULL OR pcavigencia_hasta >= pcavigencia_desde),
    CONSTRAINT ck_pca_escala
        CHECK (
            (
                pcatipo_base IN ('CUALITATIVO', 'AMBITOS_DESTREZAS')
                AND pcaminima IS NULL
                AND pcamaxima IS NULL
                AND pcaaprobacion IS NULL
            )
            OR
            (
                pcatipo_base = 'CUANTITATIVO'
                AND pcaminima IS NOT NULL
                AND pcamaxima IS NOT NULL
                AND pcaaprobacion IS NOT NULL
                AND pcaminima < pcamaxima
                AND pcaaprobacion BETWEEN pcaminima AND pcamaxima
            )
        ),
    CONSTRAINT ck_pca_decimales
        CHECK (pcadecimales BETWEEN 0 AND 4),
    CONSTRAINT ck_pca_metodo_decimal
        CHECK (pcametodo_decimal IN ('REDONDEO', 'TRUNCAMIENTO'))
);

CREATE TABLE perfil_calificacion_asignacion (
    pasid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    pleid integer NOT NULL,
    pasalcance varchar(20) NOT NULL,
    nedid integer,
    graid integer,
    curid integer,
    mtcid integer,
    pasprioridad integer NOT NULL,
    pasestado boolean NOT NULL DEFAULT true,
    pasobservacion varchar(250),
    usuid_registro integer NOT NULL,
    pasfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pasfecha_modificacion timestamp,
    CONSTRAINT pk_perfil_calificacion_asignacion PRIMARY KEY (pasid),
    CONSTRAINT fk_pas_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT fk_pas_perfil_periodo FOREIGN KEY (pcaid, pleid)
        REFERENCES perfil_calificacion (pcaid, pleid),
    CONSTRAINT fk_pas_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_pas_nivel FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT fk_pas_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_pas_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_pas_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_pas_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_pas_alcance
        CHECK (pasalcance IN ('NIVEL', 'GRADO', 'CURSO', 'MATERIA')),
    CONSTRAINT ck_pas_objetivo
        CHECK (
            (pasalcance = 'NIVEL' AND nedid IS NOT NULL AND graid IS NULL AND curid IS NULL AND mtcid IS NULL)
            OR
            (pasalcance = 'GRADO' AND nedid IS NULL AND graid IS NOT NULL AND curid IS NULL AND mtcid IS NULL)
            OR
            (pasalcance = 'CURSO' AND nedid IS NULL AND graid IS NULL AND curid IS NOT NULL AND mtcid IS NULL)
            OR
            (pasalcance = 'MATERIA' AND nedid IS NULL AND graid IS NULL AND curid IS NULL AND mtcid IS NOT NULL)
        ),
    CONSTRAINT ck_pas_prioridad
        CHECK (pasprioridad > 0)
);

CREATE UNIQUE INDEX uq_pas_nivel_activo
    ON perfil_calificacion_asignacion (pleid, nedid)
    WHERE pasestado = true AND pasalcance = 'NIVEL';

CREATE UNIQUE INDEX uq_pas_grado_activo
    ON perfil_calificacion_asignacion (pleid, graid)
    WHERE pasestado = true AND pasalcance = 'GRADO';

CREATE UNIQUE INDEX uq_pas_curso_activo
    ON perfil_calificacion_asignacion (pleid, curid)
    WHERE pasestado = true AND pasalcance = 'CURSO';

CREATE UNIQUE INDEX uq_pas_materia_activo
    ON perfil_calificacion_asignacion (pleid, mtcid)
    WHERE pasestado = true AND pasalcance = 'MATERIA';

CREATE TABLE subperiodo_calificacion (
    spcid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    spcnombre varchar(80) NOT NULL,
    spcorden integer NOT NULL,
    spcfecha_inicio date NOT NULL,
    spcfecha_fin date NOT NULL,
    spcestado varchar(20) NOT NULL DEFAULT 'EN_REGISTRO',
    spcparticipa_final boolean NOT NULL DEFAULT true,
    spcpeso_final numeric(6,3),
    spcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    spcfecha_modificacion timestamp,
    CONSTRAINT pk_subperiodo_calificacion PRIMARY KEY (spcid),
    CONSTRAINT fk_spc_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT uq_spc_perfil_nombre UNIQUE (pcaid, spcnombre),
    CONSTRAINT uq_spc_perfil_orden UNIQUE (pcaid, spcorden),
    CONSTRAINT ck_spc_fechas
        CHECK (spcfecha_fin >= spcfecha_inicio),
    CONSTRAINT ck_spc_estado
        CHECK (spcestado IN ('EN_REGISTRO', 'CERRADO_DOCENTE', 'VALIDADO_COORDINACION', 'PUBLICADO')),
    CONSTRAINT ck_spc_peso
        CHECK (spcpeso_final IS NULL OR spcpeso_final > 0)
);

CREATE TABLE componente_calificacion (
    cpcid integer GENERATED BY DEFAULT AS IDENTITY,
    spcid integer NOT NULL,
    cpcnombre varchar(100) NOT NULL,
    cpcorden integer NOT NULL,
    cpcpeso numeric(6,3),
    cpctipo_calculo varchar(30) NOT NULL DEFAULT 'PROMEDIO_SIMPLE',
    cpcestado boolean NOT NULL DEFAULT true,
    cpcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cpcfecha_modificacion timestamp,
    CONSTRAINT pk_componente_calificacion PRIMARY KEY (cpcid),
    CONSTRAINT fk_cpc_subperiodo FOREIGN KEY (spcid)
        REFERENCES subperiodo_calificacion (spcid),
    CONSTRAINT uq_cpc_subperiodo_nombre UNIQUE (spcid, cpcnombre),
    CONSTRAINT uq_cpc_subperiodo_orden UNIQUE (spcid, cpcorden),
    CONSTRAINT ck_cpc_tipo_calculo
        CHECK (cpctipo_calculo IN ('PROMEDIO_SIMPLE', 'PROMEDIO_PONDERADO', 'SUMA')),
    CONSTRAINT ck_cpc_peso
        CHECK (cpcpeso IS NULL OR cpcpeso > 0)
);

CREATE TABLE escala_cualitativa (
    ecaid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    ecacodigo varchar(20) NOT NULL,
    ecanombre varchar(80) NOT NULL,
    ecadescripcion varchar(250),
    ecavalor_minimo numeric(5,2),
    ecavalor_maximo numeric(5,2),
    ecaorden integer NOT NULL,
    ecaestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_escala_cualitativa PRIMARY KEY (ecaid),
    CONSTRAINT fk_eca_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT uq_eca_perfil_codigo UNIQUE (pcaid, ecacodigo),
    CONSTRAINT uq_eca_perfil_orden UNIQUE (pcaid, ecaorden),
    CONSTRAINT ck_eca_rango
        CHECK (
            (ecavalor_minimo IS NULL AND ecavalor_maximo IS NULL)
            OR
            (ecavalor_minimo IS NOT NULL AND ecavalor_maximo IS NOT NULL AND ecavalor_maximo >= ecavalor_minimo)
        )
);

CREATE TABLE materia_calificacion_config (
    mccid integer GENERATED BY DEFAULT AS IDENTITY,
    mtcid integer NOT NULL,
    pcaid integer NOT NULL,
    mcctipo_registro varchar(30) NOT NULL DEFAULT 'CUANTITATIVO',
    mcctipo_visualizacion varchar(20) NOT NULL DEFAULT 'MIXTA',
    mccpromediable boolean NOT NULL DEFAULT true,
    mccvisible_libreta boolean NOT NULL DEFAULT true,
    mccusa_equivalencia boolean NOT NULL DEFAULT true,
    mccestado boolean NOT NULL DEFAULT true,
    mccobservacion varchar(250),
    mccfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mccfecha_modificacion timestamp,
    CONSTRAINT pk_materia_calificacion_config PRIMARY KEY (mccid),
    CONSTRAINT fk_mcc_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_mcc_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT uq_mcc_materia_perfil UNIQUE (mtcid, pcaid),
    CONSTRAINT ck_mcc_tipo_registro
        CHECK (mcctipo_registro IN ('CUANTITATIVO', 'CUALITATIVO', 'AMBITOS_DESTREZAS')),
    CONSTRAINT ck_mcc_tipo_visualizacion
        CHECK (mcctipo_visualizacion IN ('CUANTITATIVA', 'CUALITATIVA', 'MIXTA'))
);

CREATE TABLE actividad_calificacion (
    aciid integer GENERATED BY DEFAULT AS IDENTITY,
    cpcid integer NOT NULL,
    mtcid integer NOT NULL,
    acinombre varchar(120) NOT NULL,
    acidescripcion varchar(250),
    acifecha date NOT NULL,
    acipeso numeric(6,3),
    aciestado varchar(20) NOT NULL DEFAULT 'OBLIGATORIA',
    usuid_creacion integer NOT NULL,
    acifecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    acifecha_modificacion timestamp,
    CONSTRAINT pk_actividad_calificacion PRIMARY KEY (aciid),
    CONSTRAINT fk_aci_componente FOREIGN KEY (cpcid)
        REFERENCES componente_calificacion (cpcid),
    CONSTRAINT fk_aci_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_aci_usuario FOREIGN KEY (usuid_creacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_aci_estado
        CHECK (aciestado IN ('OBLIGATORIA', 'OPCIONAL', 'ANULADA')),
    CONSTRAINT ck_aci_peso
        CHECK (acipeso IS NULL OR acipeso > 0)
);

CREATE INDEX ix_actividad_calificacion_materia
    ON actividad_calificacion (mtcid, acifecha);

CREATE TABLE calificacion_estudiante (
    cesid integer GENERATED BY DEFAULT AS IDENTITY,
    aciid integer NOT NULL,
    matid integer NOT NULL,
    cesnota numeric(5,2),
    ecaid integer,
    cesestado varchar(20) NOT NULL DEFAULT 'REGISTRADA',
    cesobservacion varchar(250),
    usuid_registro integer NOT NULL,
    cesfecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_modificacion integer,
    cesfecha_modificacion timestamp,
    CONSTRAINT pk_calificacion_estudiante PRIMARY KEY (cesid),
    CONSTRAINT fk_ces_actividad FOREIGN KEY (aciid)
        REFERENCES actividad_calificacion (aciid),
    CONSTRAINT fk_ces_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_ces_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT fk_ces_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_ces_usuario_modificacion FOREIGN KEY (usuid_modificacion)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_ces_actividad_matricula UNIQUE (aciid, matid),
    CONSTRAINT ck_ces_estado
        CHECK (cesestado IN ('REGISTRADA', 'CORREGIDA', 'ANULADA', 'EXONERADA')),
    CONSTRAINT ck_ces_valor
        CHECK (
            (cesestado IN ('ANULADA', 'EXONERADA') AND cesnota IS NULL)
            OR
            (cesestado IN ('REGISTRADA', 'CORREGIDA') AND (cesnota IS NOT NULL OR ecaid IS NOT NULL))
        )
);

CREATE INDEX ix_calificacion_estudiante_matricula
    ON calificacion_estudiante (matid);

CREATE TABLE ambito_calificacion (
    ambid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    ambnombre varchar(120) NOT NULL,
    ambdescripcion varchar(250),
    amborden integer NOT NULL,
    ambestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_ambito_calificacion PRIMARY KEY (ambid),
    CONSTRAINT fk_amb_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT uq_amb_perfil_nombre UNIQUE (pcaid, ambnombre),
    CONSTRAINT uq_amb_perfil_orden UNIQUE (pcaid, amborden)
);

CREATE TABLE destreza_calificacion (
    desid integer GENERATED BY DEFAULT AS IDENTITY,
    ambid integer NOT NULL,
    descodigo varchar(30),
    desnombre varchar(180) NOT NULL,
    desdescripcion varchar(250),
    desorden integer NOT NULL,
    desestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_destreza_calificacion PRIMARY KEY (desid),
    CONSTRAINT fk_des_ambito FOREIGN KEY (ambid)
        REFERENCES ambito_calificacion (ambid),
    CONSTRAINT uq_des_ambito_nombre UNIQUE (ambid, desnombre),
    CONSTRAINT uq_des_ambito_orden UNIQUE (ambid, desorden)
);

CREATE TABLE valoracion_destreza_estudiante (
    vdeid integer GENERATED BY DEFAULT AS IDENTITY,
    desid integer NOT NULL,
    matid integer NOT NULL,
    spcid integer NOT NULL,
    ecaid integer NOT NULL,
    vdeobservacion varchar(250),
    usuid_registro integer NOT NULL,
    vdefecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    vdefecha_modificacion timestamp,
    CONSTRAINT pk_valoracion_destreza_estudiante PRIMARY KEY (vdeid),
    CONSTRAINT fk_vde_destreza FOREIGN KEY (desid)
        REFERENCES destreza_calificacion (desid),
    CONSTRAINT fk_vde_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_vde_subperiodo FOREIGN KEY (spcid)
        REFERENCES subperiodo_calificacion (spcid),
    CONSTRAINT fk_vde_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT fk_vde_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_vde_destreza_matricula_subperiodo UNIQUE (desid, matid, spcid)
);

CREATE TABLE resultado_materia_subperiodo (
    rmsid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mtcid integer NOT NULL,
    spcid integer NOT NULL,
    rmsnota numeric(5,2),
    ecaid integer,
    rmsestado_academico varchar(30) NOT NULL DEFAULT 'EN_REGISTRO',
    rmsfecha_calculo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resultado_materia_subperiodo PRIMARY KEY (rmsid),
    CONSTRAINT fk_rms_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_rms_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_rms_subperiodo FOREIGN KEY (spcid)
        REFERENCES subperiodo_calificacion (spcid),
    CONSTRAINT fk_rms_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT uq_rms_matricula_materia_subperiodo UNIQUE (matid, mtcid, spcid),
    CONSTRAINT ck_rms_estado
        CHECK (rmsestado_academico IN ('EN_REGISTRO', 'CERRADO_DOCENTE', 'VALIDADO_COORDINACION', 'PUBLICADO'))
);

CREATE TABLE resultado_materia_final (
    rmfid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mtcid integer NOT NULL,
    rmfnota_final numeric(5,2),
    ecaid integer,
    rmfestado_academico varchar(30) NOT NULL DEFAULT 'EN_REGISTRO',
    rmffecha_calculo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resultado_materia_final PRIMARY KEY (rmfid),
    CONSTRAINT fk_rmf_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_rmf_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_rmf_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT uq_rmf_matricula_materia UNIQUE (matid, mtcid),
    CONSTRAINT ck_rmf_estado
        CHECK (rmfestado_academico IN ('EN_REGISTRO', 'CERRADO_DOCENTE', 'VALIDADO_COORDINACION', 'PUBLICADO'))
);

CREATE TABLE resultado_estudiante_final (
    refid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    pcaid integer NOT NULL,
    refpromedio_general numeric(5,2),
    ecaid integer,
    refresultado varchar(30),
    reffecha_calculo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resultado_estudiante_final PRIMARY KEY (refid),
    CONSTRAINT fk_ref_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_ref_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT fk_ref_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT uq_ref_matricula_perfil UNIQUE (matid, pcaid),
    CONSTRAINT ck_ref_resultado
        CHECK (
            refresultado IS NULL
            OR refresultado IN ('PROMOVIDO', 'SUPLETORIO', 'RECUPERACION', 'EXAMEN_GRACIA', 'NO_PROMOVIDO', 'RETIRADO')
        )
);

CREATE TABLE publicacion_calificacion (
    pbcid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    curid integer,
    spcid integer,
    pbctipo varchar(20) NOT NULL,
    pbcestado varchar(20) NOT NULL DEFAULT 'NO_DISPONIBLE',
    pbcfecha_publicacion timestamp,
    usuid_publicacion integer,
    pbcobservacion varchar(250),
    CONSTRAINT pk_publicacion_calificacion PRIMARY KEY (pbcid),
    CONSTRAINT fk_pbc_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_pbc_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_pbc_subperiodo FOREIGN KEY (spcid)
        REFERENCES subperiodo_calificacion (spcid),
    CONSTRAINT fk_pbc_usuario FOREIGN KEY (usuid_publicacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_pbc_tipo
        CHECK (pbctipo IN ('SUBPERIODO', 'FINAL')),
    CONSTRAINT ck_pbc_estado
        CHECK (pbcestado IN ('NO_DISPONIBLE', 'HABILITADA', 'BLOQUEADA')),
    CONSTRAINT ck_pbc_subperiodo
        CHECK (
            (pbctipo = 'SUBPERIODO' AND spcid IS NOT NULL)
            OR
            (pbctipo = 'FINAL' AND spcid IS NULL)
        )
);

CREATE TABLE bloqueo_visualizacion_calificacion (
    bvcid integer GENERATED BY DEFAULT AS IDENTITY,
    pbcid integer,
    curid integer,
    matid integer,
    bvcestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    bvcmotivo varchar(250) NOT NULL,
    bvcfecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bvcfecha_fin timestamp,
    usuid_registro integer NOT NULL,
    bvcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_bloqueo_visualizacion_calificacion PRIMARY KEY (bvcid),
    CONSTRAINT fk_bvc_publicacion FOREIGN KEY (pbcid)
        REFERENCES publicacion_calificacion (pbcid),
    CONSTRAINT fk_bvc_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_bvc_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_bvc_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_bvc_estado
        CHECK (bvcestado IN ('ACTIVO', 'LEVANTADO')),
    CONSTRAINT ck_bvc_objetivo
        CHECK (
            (curid IS NOT NULL AND matid IS NULL)
            OR
            (curid IS NULL AND matid IS NOT NULL)
        ),
    CONSTRAINT ck_bvc_fechas
        CHECK (bvcfecha_fin IS NULL OR bvcfecha_fin >= bvcfecha_inicio)
);

CREATE TABLE auditoria_calificacion (
    aucid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    auctipo_accion varchar(40) NOT NULL,
    aucentidad varchar(80) NOT NULL,
    aucentidad_id integer NOT NULL,
    aucvalor_anterior text,
    aucvalor_nuevo text,
    aucmotivo varchar(250),
    aucfecha timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_auditoria_calificacion PRIMARY KEY (aucid),
    CONSTRAINT fk_auc_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid)
);

CREATE INDEX ix_auditoria_calificacion_entidad
    ON auditoria_calificacion (aucentidad, aucentidad_id);

CREATE INDEX ix_auditoria_calificacion_fecha
    ON auditoria_calificacion (aucfecha);

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
VALUES
    ('Calificaciones - configurar', 'calificaciones.configurar', 'Gestion de perfiles, escalas y reglas de calificacion', true),
    ('Calificaciones - registrar', 'calificaciones.registrar', 'Registro de actividades y notas por docente', true),
    ('Calificaciones - validar', 'calificaciones.validar', 'Cierre y validacion academica de calificaciones', true),
    ('Calificaciones - publicar', 'calificaciones.publicar', 'Publicacion y bloqueo de visualizacion de libretas', true),
    ('Calificaciones - ver propia', 'calificaciones.ver_propia', 'Consulta de calificaciones propias del estudiante', true),
    ('Calificaciones - representante ver', 'calificaciones.representante.ver', 'Consulta de calificaciones de estudiantes representados', true),
    ('Calificaciones - auditoria ver', 'calificaciones.auditoria.ver', 'Consulta de auditoria academica de calificaciones', true),
    ('Calificaciones - auditoria exportar', 'calificaciones.auditoria.exportar', 'Exportacion de auditoria academica de calificaciones', true)
ON CONFLICT (prmcodigo) DO NOTHING;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'calificaciones.configurar',
    'calificaciones.registrar',
    'calificaciones.validar',
    'calificaciones.publicar',
    'calificaciones.ver_propia',
    'calificaciones.representante.ver',
    'calificaciones.auditoria.ver',
    'calificaciones.auditoria.exportar'
)
WHERE r.rolnombre = 'Administrador'
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'calificaciones.configurar',
    'calificaciones.registrar',
    'calificaciones.validar',
    'calificaciones.publicar',
    'calificaciones.auditoria.ver'
)
WHERE r.rolnombre IN ('Rector', 'Coordinador', 'Secretaria')
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'calificaciones.registrar'
WHERE r.rolnombre = 'Docente'
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'calificaciones.ver_propia'
WHERE r.rolnombre = 'Estudiante'
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'calificaciones.representante.ver'
WHERE r.rolnombre = 'Representante'
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;
