-- Promocion academica e instancias extraordinarias.
--
-- Depende de database/scripts/18_calificaciones.sql. Este bloque separa las
-- reglas de promocion de las notas ordinarias para que cada perfil del periodo
-- pueda decidir resultados y habilitar supletorios, recuperaciones o examenes.

CREATE TABLE regla_promocion (
    rprid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    rprnombre varchar(120) NOT NULL,
    rprdescripcion varchar(250),
    rpraplica_sobre varchar(20) NOT NULL DEFAULT 'PROMEDIO_GENERAL',
    rprrequiere_todas_materias boolean NOT NULL DEFAULT true,
    rprestado boolean NOT NULL DEFAULT true,
    rprfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    rprfecha_modificacion timestamp,
    CONSTRAINT pk_regla_promocion PRIMARY KEY (rprid),
    CONSTRAINT fk_rpr_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT uq_rpr_perfil_nombre UNIQUE (pcaid, rprnombre),
    CONSTRAINT ck_rpr_aplica_sobre
        CHECK (rpraplica_sobre IN ('PROMEDIO_GENERAL', 'MATERIA', 'AMBOS'))
);

CREATE TABLE regla_promocion_tramo (
    rptid integer GENERATED BY DEFAULT AS IDENTITY,
    rprid integer NOT NULL,
    rptorden integer NOT NULL,
    rptnota_minima numeric(5,2) NOT NULL,
    rptnota_maxima numeric(5,2) NOT NULL,
    rptresultado varchar(30) NOT NULL,
    rpthabilita_extraordinaria boolean NOT NULL DEFAULT false,
    rptestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_regla_promocion_tramo PRIMARY KEY (rptid),
    CONSTRAINT fk_rpt_regla FOREIGN KEY (rprid)
        REFERENCES regla_promocion (rprid),
    CONSTRAINT uq_rpt_regla_orden UNIQUE (rprid, rptorden),
    CONSTRAINT ck_rpt_rango
        CHECK (rptnota_maxima >= rptnota_minima),
    CONSTRAINT ck_rpt_resultado
        CHECK (rptresultado IN ('PROMOVIDO', 'SUPLETORIO', 'RECUPERACION', 'EXAMEN_GRACIA', 'NO_PROMOVIDO'))
);

CREATE TABLE instancia_extraordinaria (
    iexid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    iexnombre varchar(100) NOT NULL,
    iexorden integer NOT NULL,
    iexestado varchar(20) NOT NULL DEFAULT 'ACTIVA',
    iexaplica_sobre varchar(20) NOT NULL DEFAULT 'MATERIA',
    iexnota_habilita_minima numeric(5,2) NOT NULL,
    iexnota_habilita_maxima numeric(5,2) NOT NULL,
    iexnota_minima_aprobar numeric(5,2) NOT NULL,
    iexnota_final_aprobado numeric(5,2),
    iexpermite_siguiente boolean NOT NULL DEFAULT false,
    iexfecha_inicio date,
    iexfecha_fin date,
    iexobservacion varchar(250),
    iexfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    iexfecha_modificacion timestamp,
    CONSTRAINT pk_instancia_extraordinaria PRIMARY KEY (iexid),
    CONSTRAINT fk_iex_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT uq_iex_perfil_nombre UNIQUE (pcaid, iexnombre),
    CONSTRAINT uq_iex_perfil_orden UNIQUE (pcaid, iexorden),
    CONSTRAINT ck_iex_estado
        CHECK (iexestado IN ('BORRADOR', 'ACTIVA', 'CERRADA', 'ANULADA')),
    CONSTRAINT ck_iex_aplica_sobre
        CHECK (iexaplica_sobre IN ('MATERIA', 'PROMEDIO_GENERAL')),
    CONSTRAINT ck_iex_rango_habilita
        CHECK (iexnota_habilita_maxima >= iexnota_habilita_minima),
    CONSTRAINT ck_iex_fechas
        CHECK (iexfecha_fin IS NULL OR iexfecha_inicio IS NULL OR iexfecha_fin >= iexfecha_inicio)
);

CREATE TABLE instancia_extraordinaria_registro (
    ierid integer GENERATED BY DEFAULT AS IDENTITY,
    iexid integer NOT NULL,
    matid integer NOT NULL,
    mtcid integer,
    iernota_anterior numeric(5,2),
    iernota_extraordinaria numeric(5,2),
    iernota_final numeric(5,2),
    ierresultado varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    ierobservacion varchar(250),
    usuid_registro integer NOT NULL,
    ierfecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_modificacion integer,
    ierfecha_modificacion timestamp,
    CONSTRAINT pk_instancia_extraordinaria_registro PRIMARY KEY (ierid),
    CONSTRAINT fk_ier_instancia FOREIGN KEY (iexid)
        REFERENCES instancia_extraordinaria (iexid),
    CONSTRAINT fk_ier_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_ier_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_ier_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_ier_usuario_modificacion FOREIGN KEY (usuid_modificacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_ier_resultado
        CHECK (ierresultado IN ('PENDIENTE', 'APROBADO', 'REPROBADO', 'ANULADO')),
    CONSTRAINT ck_ier_notas_resultado
        CHECK (
            ierresultado IN ('PENDIENTE', 'ANULADO')
            OR iernota_extraordinaria IS NOT NULL
        )
);

CREATE INDEX ix_ier_matricula
    ON instancia_extraordinaria_registro (matid);

CREATE INDEX ix_ier_materia
    ON instancia_extraordinaria_registro (mtcid);

CREATE UNIQUE INDEX uq_ier_instancia_matricula_general
    ON instancia_extraordinaria_registro (iexid, matid)
    WHERE mtcid IS NULL;

CREATE UNIQUE INDEX uq_ier_instancia_matricula_materia
    ON instancia_extraordinaria_registro (iexid, matid, mtcid)
    WHERE mtcid IS NOT NULL;

CREATE TABLE promocion_estudiante (
    preid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    pcaid integer NOT NULL,
    rprid integer,
    prepromedio_original numeric(5,2),
    prepromedio_final numeric(5,2),
    preestado varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    preobservacion varchar(250),
    usuid_calculo integer NOT NULL,
    prefecha_calculo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_modificacion integer,
    prefecha_modificacion timestamp,
    CONSTRAINT pk_promocion_estudiante PRIMARY KEY (preid),
    CONSTRAINT fk_pre_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_pre_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT fk_pre_regla FOREIGN KEY (rprid)
        REFERENCES regla_promocion (rprid),
    CONSTRAINT fk_pre_usuario_calculo FOREIGN KEY (usuid_calculo)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_pre_usuario_modificacion FOREIGN KEY (usuid_modificacion)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_pre_matricula_perfil UNIQUE (matid, pcaid),
    CONSTRAINT ck_pre_estado
        CHECK (preestado IN ('PENDIENTE', 'PROMOVIDO', 'SUPLETORIO', 'RECUPERACION', 'EXAMEN_GRACIA', 'NO_PROMOVIDO', 'RETIRADO'))
);

CREATE TABLE promocion_materia (
    pmtid integer GENERATED BY DEFAULT AS IDENTITY,
    preid integer NOT NULL,
    mtcid integer NOT NULL,
    rmfid integer,
    pmtnota_original numeric(5,2),
    pmtnota_final numeric(5,2),
    pmtestado varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT pk_promocion_materia PRIMARY KEY (pmtid),
    CONSTRAINT fk_pmt_promocion FOREIGN KEY (preid)
        REFERENCES promocion_estudiante (preid),
    CONSTRAINT fk_pmt_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_pmt_resultado_materia FOREIGN KEY (rmfid)
        REFERENCES resultado_materia_final (rmfid),
    CONSTRAINT uq_pmt_promocion_materia UNIQUE (preid, mtcid),
    CONSTRAINT ck_pmt_estado
        CHECK (pmtestado IN ('PENDIENTE', 'APROBADA', 'HABILITA_EXTRAORDINARIA', 'REPROBADA', 'NO_PROMEDIA'))
);

CREATE INDEX ix_promocion_estudiante_matricula
    ON promocion_estudiante (matid);

CREATE INDEX ix_promocion_materia_materia
    ON promocion_materia (mtcid);

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
VALUES
    ('Calificaciones - promocion configurar', 'calificaciones.promocion.configurar', 'Gestion de reglas de promocion e instancias extraordinarias', true),
    ('Calificaciones - promocion calcular', 'calificaciones.promocion.calcular', 'Calculo de promocion academica del estudiante', true),
    ('Calificaciones - extraordinarias registrar', 'calificaciones.extraordinarias.registrar', 'Registro de notas de supletorio, recuperacion o examen de gracia', true)
ON CONFLICT (prmcodigo) DO NOTHING;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'calificaciones.promocion.configurar',
    'calificaciones.promocion.calcular',
    'calificaciones.extraordinarias.registrar'
)
WHERE r.rolnombre = 'Administrador'
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'calificaciones.promocion.configurar',
    'calificaciones.promocion.calcular',
    'calificaciones.extraordinarias.registrar'
)
WHERE r.rolnombre IN ('Rector', 'Coordinador', 'Secretaria')
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'calificaciones.extraordinarias.registrar'
WHERE r.rolnombre = 'Docente'
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;
