-- Soporte para configuracion de calificaciones.
--
-- Depende de database/scripts/18_calificaciones.sql y
-- database/scripts/19_calificaciones_promocion.sql. Agrega plantillas para
-- crear perfiles por periodo y vistas para resolver el perfil efectivo.

CREATE TABLE plantilla_calificacion (
    pclid integer GENERATED BY DEFAULT AS IDENTITY,
    pclnombre varchar(120) NOT NULL,
    pcldescripcion varchar(250),
    pcltipo_base varchar(30) NOT NULL DEFAULT 'CUANTITATIVO',
    pclminima numeric(5,2),
    pclmaxima numeric(5,2),
    pclaprobacion numeric(5,2),
    pcldecimales integer NOT NULL DEFAULT 2,
    pclmetodo_decimal varchar(20) NOT NULL DEFAULT 'REDONDEO',
    pclpromedia_final boolean NOT NULL DEFAULT true,
    pclaplica_promocion boolean NOT NULL DEFAULT true,
    pclestado boolean NOT NULL DEFAULT true,
    pclfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    pclfecha_modificacion timestamp,
    CONSTRAINT pk_plantilla_calificacion PRIMARY KEY (pclid),
    CONSTRAINT uq_plantilla_calificacion_nombre UNIQUE (pclnombre),
    CONSTRAINT ck_pcl_tipo_base
        CHECK (pcltipo_base IN ('CUANTITATIVO', 'CUALITATIVO', 'AMBITOS_DESTREZAS')),
    CONSTRAINT ck_pcl_escala
        CHECK (
            (
                pcltipo_base IN ('CUALITATIVO', 'AMBITOS_DESTREZAS')
                AND pclminima IS NULL
                AND pclmaxima IS NULL
                AND pclaprobacion IS NULL
            )
            OR
            (
                pcltipo_base = 'CUANTITATIVO'
                AND pclminima IS NOT NULL
                AND pclmaxima IS NOT NULL
                AND pclaprobacion IS NOT NULL
                AND pclminima < pclmaxima
                AND pclaprobacion BETWEEN pclminima AND pclmaxima
            )
        ),
    CONSTRAINT ck_pcl_decimales
        CHECK (pcldecimales BETWEEN 0 AND 4),
    CONSTRAINT ck_pcl_metodo_decimal
        CHECK (pclmetodo_decimal IN ('REDONDEO', 'TRUNCAMIENTO'))
);

CREATE TABLE plantilla_subperiodo (
    psuid integer GENERATED BY DEFAULT AS IDENTITY,
    pclid integer NOT NULL,
    psunombre varchar(80) NOT NULL,
    psuorden integer NOT NULL,
    psuparticipa_final boolean NOT NULL DEFAULT true,
    psupeso_final numeric(6,3),
    CONSTRAINT pk_plantilla_subperiodo PRIMARY KEY (psuid),
    CONSTRAINT fk_psu_plantilla FOREIGN KEY (pclid)
        REFERENCES plantilla_calificacion (pclid),
    CONSTRAINT uq_psu_plantilla_nombre UNIQUE (pclid, psunombre),
    CONSTRAINT uq_psu_plantilla_orden UNIQUE (pclid, psuorden),
    CONSTRAINT ck_psu_peso
        CHECK (psupeso_final IS NULL OR psupeso_final > 0)
);

CREATE TABLE plantilla_componente (
    pcoid integer GENERATED BY DEFAULT AS IDENTITY,
    psuid integer NOT NULL,
    pconombre varchar(100) NOT NULL,
    pcoorden integer NOT NULL,
    pcopeso numeric(6,3),
    pcotipo_calculo varchar(30) NOT NULL DEFAULT 'PROMEDIO_SIMPLE',
    pcoestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_plantilla_componente PRIMARY KEY (pcoid),
    CONSTRAINT fk_pco_subperiodo FOREIGN KEY (psuid)
        REFERENCES plantilla_subperiodo (psuid),
    CONSTRAINT uq_pco_subperiodo_nombre UNIQUE (psuid, pconombre),
    CONSTRAINT uq_pco_subperiodo_orden UNIQUE (psuid, pcoorden),
    CONSTRAINT ck_pco_tipo_calculo
        CHECK (pcotipo_calculo IN ('PROMEDIO_SIMPLE', 'PROMEDIO_PONDERADO', 'SUMA')),
    CONSTRAINT ck_pco_peso
        CHECK (pcopeso IS NULL OR pcopeso > 0)
);

CREATE TABLE plantilla_escala_cualitativa (
    pecid integer GENERATED BY DEFAULT AS IDENTITY,
    pclid integer NOT NULL,
    peccodigo varchar(20) NOT NULL,
    pecnombre varchar(80) NOT NULL,
    pecdescripcion varchar(250),
    pecvalor_minimo numeric(5,2),
    pecvalor_maximo numeric(5,2),
    pecorden integer NOT NULL,
    pecestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_plantilla_escala_cualitativa PRIMARY KEY (pecid),
    CONSTRAINT fk_pec_plantilla FOREIGN KEY (pclid)
        REFERENCES plantilla_calificacion (pclid),
    CONSTRAINT uq_pec_plantilla_codigo UNIQUE (pclid, peccodigo),
    CONSTRAINT uq_pec_plantilla_orden UNIQUE (pclid, pecorden),
    CONSTRAINT ck_pec_rango
        CHECK (
            (pecvalor_minimo IS NULL AND pecvalor_maximo IS NULL)
            OR
            (pecvalor_minimo IS NOT NULL AND pecvalor_maximo IS NOT NULL AND pecvalor_maximo >= pecvalor_minimo)
        )
);

CREATE TABLE plantilla_ambito (
    pambid integer GENERATED BY DEFAULT AS IDENTITY,
    pclid integer NOT NULL,
    pambnombre varchar(120) NOT NULL,
    pambdescripcion varchar(250),
    pamborden integer NOT NULL,
    pambestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_plantilla_ambito PRIMARY KEY (pambid),
    CONSTRAINT fk_pamb_plantilla FOREIGN KEY (pclid)
        REFERENCES plantilla_calificacion (pclid),
    CONSTRAINT uq_pamb_plantilla_nombre UNIQUE (pclid, pambnombre),
    CONSTRAINT uq_pamb_plantilla_orden UNIQUE (pclid, pamborden)
);

CREATE TABLE plantilla_destreza (
    pdesid integer GENERATED BY DEFAULT AS IDENTITY,
    pambid integer NOT NULL,
    pdescodigo varchar(30),
    pdesnombre varchar(180) NOT NULL,
    pdesdescripcion varchar(250),
    pdesorden integer NOT NULL,
    pdesestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_plantilla_destreza PRIMARY KEY (pdesid),
    CONSTRAINT fk_pdes_ambito FOREIGN KEY (pambid)
        REFERENCES plantilla_ambito (pambid),
    CONSTRAINT uq_pdes_ambito_nombre UNIQUE (pambid, pdesnombre),
    CONSTRAINT uq_pdes_ambito_orden UNIQUE (pambid, pdesorden)
);

CREATE TABLE plantilla_promocion_tramo (
    pptid integer GENERATED BY DEFAULT AS IDENTITY,
    pclid integer NOT NULL,
    pptorden integer NOT NULL,
    pptnota_minima numeric(5,2) NOT NULL,
    pptnota_maxima numeric(5,2) NOT NULL,
    pptresultado varchar(30) NOT NULL,
    ppthabilita_extraordinaria boolean NOT NULL DEFAULT false,
    pptestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_plantilla_promocion_tramo PRIMARY KEY (pptid),
    CONSTRAINT fk_ppt_plantilla FOREIGN KEY (pclid)
        REFERENCES plantilla_calificacion (pclid),
    CONSTRAINT uq_ppt_plantilla_orden UNIQUE (pclid, pptorden),
    CONSTRAINT ck_ppt_rango
        CHECK (pptnota_maxima >= pptnota_minima),
    CONSTRAINT ck_ppt_resultado
        CHECK (pptresultado IN ('PROMOVIDO', 'SUPLETORIO', 'RECUPERACION', 'EXAMEN_GRACIA', 'NO_PROMOVIDO'))
);

CREATE TABLE plantilla_instancia_extraordinaria (
    pieid integer GENERATED BY DEFAULT AS IDENTITY,
    pclid integer NOT NULL,
    pienombre varchar(100) NOT NULL,
    pieorden integer NOT NULL,
    pieaplica_sobre varchar(20) NOT NULL DEFAULT 'MATERIA',
    pienota_habilita_minima numeric(5,2) NOT NULL,
    pienota_habilita_maxima numeric(5,2) NOT NULL,
    pienota_minima_aprobar numeric(5,2) NOT NULL,
    pienota_final_aprobado numeric(5,2),
    piepermite_siguiente boolean NOT NULL DEFAULT false,
    pieestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_plantilla_instancia_extraordinaria PRIMARY KEY (pieid),
    CONSTRAINT fk_pie_plantilla FOREIGN KEY (pclid)
        REFERENCES plantilla_calificacion (pclid),
    CONSTRAINT uq_pie_plantilla_nombre UNIQUE (pclid, pienombre),
    CONSTRAINT uq_pie_plantilla_orden UNIQUE (pclid, pieorden),
    CONSTRAINT ck_pie_aplica_sobre
        CHECK (pieaplica_sobre IN ('MATERIA', 'PROMEDIO_GENERAL')),
    CONSTRAINT ck_pie_rango_habilita
        CHECK (pienota_habilita_maxima >= pienota_habilita_minima)
);

CREATE VIEW vw_calificacion_perfil_curso AS
SELECT *
FROM (
    SELECT
        c.curid,
        c.pleid,
        c.graid,
        g.nedid,
        p.pcaid,
        p.pcanombre,
        p.pcatipo_base,
        p.pcaestado,
        a.pasid,
        a.pasalcance,
        a.pasprioridad,
        ROW_NUMBER() OVER (
            PARTITION BY c.curid
            ORDER BY
                CASE a.pasalcance
                    WHEN 'CURSO' THEN 3
                    WHEN 'GRADO' THEN 2
                    WHEN 'NIVEL' THEN 1
                    ELSE 0
                END DESC,
                a.pasprioridad DESC,
                a.pasid DESC
        ) AS prioridad_resuelta
    FROM curso c
    INNER JOIN grado g ON g.graid = c.graid
    INNER JOIN perfil_calificacion_asignacion a
        ON a.pleid = c.pleid
        AND a.pasestado = true
        AND (
            (a.pasalcance = 'CURSO' AND a.curid = c.curid)
            OR
            (a.pasalcance = 'GRADO' AND a.graid = c.graid)
            OR
            (a.pasalcance = 'NIVEL' AND a.nedid = g.nedid)
        )
    INNER JOIN perfil_calificacion p ON p.pcaid = a.pcaid
    WHERE p.pcaestado IN ('ACTIVA', 'BLOQUEADA')
) perfiles
WHERE prioridad_resuelta = 1;

CREATE VIEW vw_calificacion_perfil_materia AS
SELECT *
FROM (
    SELECT
        mc.mtcid,
        mc.curid,
        c.pleid,
        c.graid,
        g.nedid,
        mc.asgid,
        p.pcaid,
        p.pcanombre,
        p.pcatipo_base,
        p.pcaestado,
        a.pasid,
        a.pasalcance,
        a.pasprioridad,
        ROW_NUMBER() OVER (
            PARTITION BY mc.mtcid
            ORDER BY
                CASE a.pasalcance
                    WHEN 'MATERIA' THEN 4
                    WHEN 'CURSO' THEN 3
                    WHEN 'GRADO' THEN 2
                    WHEN 'NIVEL' THEN 1
                    ELSE 0
                END DESC,
                a.pasprioridad DESC,
                a.pasid DESC
        ) AS prioridad_resuelta
    FROM materia_curso mc
    INNER JOIN curso c ON c.curid = mc.curid
    INNER JOIN grado g ON g.graid = c.graid
    INNER JOIN perfil_calificacion_asignacion a
        ON a.pleid = c.pleid
        AND a.pasestado = true
        AND (
            (a.pasalcance = 'MATERIA' AND a.mtcid = mc.mtcid)
            OR
            (a.pasalcance = 'CURSO' AND a.curid = c.curid)
            OR
            (a.pasalcance = 'GRADO' AND a.graid = c.graid)
            OR
            (a.pasalcance = 'NIVEL' AND a.nedid = g.nedid)
        )
    INNER JOIN perfil_calificacion p ON p.pcaid = a.pcaid
    WHERE p.pcaestado IN ('ACTIVA', 'BLOQUEADA')
) perfiles
WHERE prioridad_resuelta = 1;

CREATE VIEW vw_calificacion_materia_config_efectiva AS
SELECT
    v.mtcid,
    v.curid,
    v.pleid,
    v.graid,
    v.nedid,
    v.asgid,
    v.pcaid,
    v.pcanombre,
    v.pcatipo_base,
    COALESCE(mcc.mcctipo_registro, v.pcatipo_base) AS tipo_registro,
    COALESCE(mcc.mcctipo_visualizacion, 'MIXTA') AS tipo_visualizacion,
    COALESCE(mcc.mccpromediable, true) AS promediable,
    COALESCE(mcc.mccvisible_libreta, true) AS visible_libreta,
    COALESCE(mcc.mccusa_equivalencia, true) AS usa_equivalencia,
    mcc.mccid
FROM vw_calificacion_perfil_materia v
LEFT JOIN materia_calificacion_config mcc
    ON mcc.mtcid = v.mtcid
    AND mcc.pcaid = v.pcaid
    AND mcc.mccestado = true;

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
VALUES
    ('Calificaciones - plantillas', 'calificaciones.plantillas.gestionar', 'Gestion de plantillas base de configuracion de calificaciones', true)
ON CONFLICT (prmcodigo) DO NOTHING;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'calificaciones.plantillas.gestionar'
WHERE r.rolnombre IN ('Administrador', 'Rector', 'Coordinador')
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;
