-- Grupos de materias para calificaciones.
--
-- Permite casos como Ingles + Science + Language, donde cada materia puede
-- registrar notas propias, pero para libreta, promedio y promocion se comportan
-- como una sola materia academica dentro de un perfil de calificacion.
--
-- Depende de:
-- - database/scripts/18_calificaciones.sql
-- - database/scripts/19_calificaciones_promocion.sql
-- - database/scripts/20_calificaciones_soporte.sql

CREATE TABLE grupo_materia_calificacion (
    gmcid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    areaid integer NOT NULL,
    gmcnombre varchar(120) NOT NULL,
    gmcdescripcion varchar(250),
    gmcmodo_calculo varchar(30) NOT NULL DEFAULT 'PROMEDIO_SIMPLE',
    gmcmtcid_representante integer,
    gmcvisualizacion varchar(20) NOT NULL DEFAULT 'GRUPO',
    gmcpromediable boolean NOT NULL DEFAULT true,
    gmcvisible_libreta boolean NOT NULL DEFAULT true,
    gmcestado boolean NOT NULL DEFAULT true,
    gmcorden integer NOT NULL,
    gmcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmcfecha_modificacion timestamp,
    CONSTRAINT pk_grupo_materia_calificacion PRIMARY KEY (gmcid),
    CONSTRAINT uq_gmc_id_perfil UNIQUE (gmcid, pcaid),
    CONSTRAINT fk_gmc_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT fk_gmc_area FOREIGN KEY (areaid)
        REFERENCES area_academica (areaid),
    CONSTRAINT fk_gmc_materia_representante FOREIGN KEY (gmcmtcid_representante)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT uq_gmc_perfil_nombre UNIQUE (pcaid, gmcnombre),
    CONSTRAINT uq_gmc_perfil_orden UNIQUE (pcaid, gmcorden),
    CONSTRAINT ck_gmc_modo_calculo
        CHECK (gmcmodo_calculo IN ('PROMEDIO_SIMPLE', 'PROMEDIO_PONDERADO', 'SUMA')),
    CONSTRAINT ck_gmc_visualizacion
        CHECK (gmcvisualizacion IN ('GRUPO', 'REPRESENTANTE'))
);

CREATE TABLE grupo_materia_calificacion_detalle (
    gmcdid integer GENERATED BY DEFAULT AS IDENTITY,
    gmcid integer NOT NULL,
    pcaid integer NOT NULL,
    mtcid integer NOT NULL,
    gmcdpeso numeric(6,3),
    gmcdorden integer NOT NULL,
    gmcdincluye_calculo boolean NOT NULL DEFAULT true,
    gmcdvisible_detalle boolean NOT NULL DEFAULT false,
    gmcdestado boolean NOT NULL DEFAULT true,
    gmcdfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmcdfecha_modificacion timestamp,
    CONSTRAINT pk_grupo_materia_calificacion_detalle PRIMARY KEY (gmcdid),
    CONSTRAINT fk_gmcd_grupo FOREIGN KEY (gmcid, pcaid)
        REFERENCES grupo_materia_calificacion (gmcid, pcaid),
    CONSTRAINT fk_gmcd_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT uq_gmcd_grupo_materia UNIQUE (gmcid, mtcid),
    CONSTRAINT uq_gmcd_grupo_orden UNIQUE (gmcid, gmcdorden),
    CONSTRAINT ck_gmcd_peso
        CHECK (gmcdpeso IS NULL OR gmcdpeso > 0)
);

CREATE UNIQUE INDEX uq_gmcd_perfil_materia_activa
    ON grupo_materia_calificacion_detalle (pcaid, mtcid)
    WHERE gmcdestado = true;

CREATE TABLE resultado_grupo_materia_subperiodo (
    rgmsid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    gmcid integer NOT NULL,
    spcid integer NOT NULL,
    rgmsnota numeric(5,2),
    ecaid integer,
    rgmsestado_academico varchar(30) NOT NULL DEFAULT 'EN_REGISTRO',
    rgmsfecha_calculo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resultado_grupo_materia_subperiodo PRIMARY KEY (rgmsid),
    CONSTRAINT fk_rgms_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_rgms_grupo FOREIGN KEY (gmcid)
        REFERENCES grupo_materia_calificacion (gmcid),
    CONSTRAINT fk_rgms_subperiodo FOREIGN KEY (spcid)
        REFERENCES subperiodo_calificacion (spcid),
    CONSTRAINT fk_rgms_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT uq_rgms_matricula_grupo_subperiodo UNIQUE (matid, gmcid, spcid),
    CONSTRAINT ck_rgms_estado
        CHECK (rgmsestado_academico IN ('EN_REGISTRO', 'CERRADO_DOCENTE', 'VALIDADO_COORDINACION', 'PUBLICADO'))
);

CREATE TABLE resultado_grupo_materia_final (
    rgmfid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    gmcid integer NOT NULL,
    rgmfnota_final numeric(5,2),
    ecaid integer,
    rgmfestado_academico varchar(30) NOT NULL DEFAULT 'EN_REGISTRO',
    rgmffecha_calculo timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_resultado_grupo_materia_final PRIMARY KEY (rgmfid),
    CONSTRAINT fk_rgmf_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_rgmf_grupo FOREIGN KEY (gmcid)
        REFERENCES grupo_materia_calificacion (gmcid),
    CONSTRAINT fk_rgmf_escala FOREIGN KEY (ecaid)
        REFERENCES escala_cualitativa (ecaid),
    CONSTRAINT uq_rgmf_matricula_grupo UNIQUE (matid, gmcid),
    CONSTRAINT ck_rgmf_estado
        CHECK (rgmfestado_academico IN ('EN_REGISTRO', 'CERRADO_DOCENTE', 'VALIDADO_COORDINACION', 'PUBLICADO'))
);

CREATE TABLE promocion_grupo_materia (
    pgmid integer GENERATED BY DEFAULT AS IDENTITY,
    preid integer NOT NULL,
    gmcid integer NOT NULL,
    rgmfid integer,
    pgmnota_original numeric(5,2),
    pgmnota_final numeric(5,2),
    pgmestado varchar(30) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT pk_promocion_grupo_materia PRIMARY KEY (pgmid),
    CONSTRAINT fk_pgm_promocion FOREIGN KEY (preid)
        REFERENCES promocion_estudiante (preid),
    CONSTRAINT fk_pgm_grupo FOREIGN KEY (gmcid)
        REFERENCES grupo_materia_calificacion (gmcid),
    CONSTRAINT fk_pgm_resultado_grupo FOREIGN KEY (rgmfid)
        REFERENCES resultado_grupo_materia_final (rgmfid),
    CONSTRAINT uq_pgm_promocion_grupo UNIQUE (preid, gmcid),
    CONSTRAINT ck_pgm_estado
        CHECK (pgmestado IN ('PENDIENTE', 'APROBADA', 'HABILITA_EXTRAORDINARIA', 'REPROBADA', 'NO_PROMEDIA'))
);

CREATE INDEX ix_gmc_perfil
    ON grupo_materia_calificacion (pcaid);

CREATE INDEX ix_gmcd_materia
    ON grupo_materia_calificacion_detalle (mtcid);

CREATE INDEX ix_rgms_grupo
    ON resultado_grupo_materia_subperiodo (gmcid, spcid);

CREATE INDEX ix_rgmf_grupo
    ON resultado_grupo_materia_final (gmcid);

CREATE INDEX ix_pgm_grupo
    ON promocion_grupo_materia (gmcid);

CREATE VIEW vw_calificacion_grupo_materia_detalle AS
SELECT
    g.gmcid,
    g.pcaid,
    g.areaid,
    ga.areanombre AS grupo_areanombre,
    g.gmcnombre,
    g.gmcdescripcion,
    g.gmcmodo_calculo,
    g.gmcmtcid_representante,
    g.gmcvisualizacion,
    g.gmcpromediable,
    g.gmcvisible_libreta,
    g.gmcestado,
    g.gmcorden,
    d.gmcdid,
    d.mtcid,
    d.gmcdpeso,
    d.gmcdorden,
    d.gmcdincluye_calculo,
    d.gmcdvisible_detalle,
    d.gmcdestado,
    v.curid,
    v.pleid,
    v.graid,
    v.prlid,
    v.areaid AS materia_areaid,
    v.areanombre AS materia_areanombre,
    v.asgnombre,
    v.granombre,
    v.prlnombre,
    v.mtcnombre_mostrar
FROM grupo_materia_calificacion g
INNER JOIN area_academica ga ON ga.areaid = g.areaid
INNER JOIN grupo_materia_calificacion_detalle d
    ON d.gmcid = g.gmcid
    AND d.pcaid = g.pcaid
INNER JOIN vw_materia_curso v ON v.mtcid = d.mtcid;

CREATE VIEW vw_calificacion_materia_config_agrupada AS
SELECT
    c.*,
    gd.gmcid,
    gd.gmcnombre,
    gd.gmcmodo_calculo,
    gd.gmcvisualizacion,
    gd.gmcpromediable AS grupo_promediable,
    gd.gmcvisible_libreta AS grupo_visible_libreta,
    gd.gmcorden AS grupo_orden,
    gd.gmcdpeso AS grupo_materia_peso,
    gd.gmcdorden AS grupo_materia_orden,
    gd.gmcdincluye_calculo,
    gd.gmcdvisible_detalle,
    CASE
        WHEN gd.gmcid IS NULL THEN c.promediable
        ELSE false
    END AS promedia_como_materia_individual,
    CASE
        WHEN gd.gmcid IS NULL THEN c.visible_libreta
        ELSE gd.gmcdvisible_detalle
    END AS visible_como_materia_individual
FROM vw_calificacion_materia_config_efectiva c
LEFT JOIN vw_calificacion_grupo_materia_detalle gd
    ON gd.pcaid = c.pcaid
    AND gd.mtcid = c.mtcid
    AND gd.gmcestado = true
    AND gd.gmcdestado = true;

INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
VALUES
    ('Calificaciones - grupos de materias', 'calificaciones.grupos_materias.configurar', 'Configuracion de materias que se calculan como una sola nota', true)
ON CONFLICT (prmcodigo) DO NOTHING;

INSERT INTO rol_permiso (rolid, prmid, rpeestado)
SELECT r.rolid, p.prmid, true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo = 'calificaciones.grupos_materias.configurar'
WHERE r.rolnombre IN ('Administrador', 'Rector', 'Coordinador')
ON CONFLICT (rolid, prmid) DO UPDATE
SET rpeestado = EXCLUDED.rpeestado,
    rpefecha_modificacion = CURRENT_TIMESTAMP;
