-- Habilitacion temporal de registro de notas fuera del rango del subperiodo.
-- Permite que secretaria, coordinacion o autoridades reabran una materia/subperiodo
-- por una ventana controlada y auditada.

CREATE TABLE IF NOT EXISTS habilitacion_registro_calificacion (
    hrcid integer GENERATED BY DEFAULT AS IDENTITY,
    pcaid integer NOT NULL,
    spcid integer NOT NULL,
    curid integer,
    mtcid integer,
    hrcfecha_inicio timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hrcfecha_fin timestamp NOT NULL,
    hrcmotivo varchar(250) NOT NULL,
    hrcestado varchar(20) NOT NULL DEFAULT 'ACTIVA',
    usuid_registro integer NOT NULL,
    hrcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hrcfecha_modificacion timestamp,
    CONSTRAINT pk_habilitacion_registro_calificacion PRIMARY KEY (hrcid),
    CONSTRAINT fk_hrc_perfil FOREIGN KEY (pcaid)
        REFERENCES perfil_calificacion (pcaid),
    CONSTRAINT fk_hrc_subperiodo FOREIGN KEY (spcid)
        REFERENCES subperiodo_calificacion (spcid),
    CONSTRAINT fk_hrc_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_hrc_materia FOREIGN KEY (mtcid)
        REFERENCES materia_curso (mtcid),
    CONSTRAINT fk_hrc_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_hrc_estado
        CHECK (hrcestado IN ('ACTIVA', 'CERRADA', 'ANULADA')),
    CONSTRAINT ck_hrc_fechas
        CHECK (hrcfecha_fin > hrcfecha_inicio),
    CONSTRAINT ck_hrc_alcance
        CHECK (curid IS NOT NULL OR mtcid IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_hrc_subperiodo_materia_estado
    ON habilitacion_registro_calificacion (spcid, mtcid, hrcestado, hrcfecha_inicio, hrcfecha_fin);

CREATE INDEX IF NOT EXISTS ix_hrc_subperiodo_curso_estado
    ON habilitacion_registro_calificacion (spcid, curid, hrcestado, hrcfecha_inicio, hrcfecha_fin);
