-- Modulo de Gestion Contable.
--
-- Administra obligaciones escolares, rubros adicionales, comprobantes de pago,
-- saldos internos y auditoria. No emite facturas ni se acopla a proveedores
-- externos de facturacion.

CREATE TABLE contabilidad_concepto (
    ccoid integer GENERATED BY DEFAULT AS IDENTITY,
    ccocodigo varchar(40) NOT NULL,
    cconombre varchar(120) NOT NULL,
    ccocategoria varchar(20) NOT NULL,
    ccodescripcion varchar(250),
    ccoestado boolean NOT NULL DEFAULT true,
    ccofecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ccofecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_concepto PRIMARY KEY (ccoid),
    CONSTRAINT uq_contabilidad_concepto_categoria_codigo UNIQUE (ccocategoria, ccocodigo),
    CONSTRAINT uq_contabilidad_concepto_categoria_nombre UNIQUE (ccocategoria, cconombre),
    CONSTRAINT ck_contabilidad_concepto_categoria
        CHECK (ccocategoria IN ('OBLIGACION', 'RUBRO'))
);

CREATE TABLE contabilidad_metodo_pago (
    cmpid integer GENERATED BY DEFAULT AS IDENTITY,
    cmpcodigo varchar(30) NOT NULL,
    cmpnombre varchar(80) NOT NULL,
    cmpdescripcion varchar(200),
    cmpestado boolean NOT NULL DEFAULT true,
    cmpfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmpfecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_metodo_pago PRIMARY KEY (cmpid),
    CONSTRAINT uq_contabilidad_metodo_pago_codigo UNIQUE (cmpcodigo),
    CONSTRAINT uq_contabilidad_metodo_pago_nombre UNIQUE (cmpnombre)
);

CREATE TABLE contabilidad_configuracion_obligacion (
    cfoid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    cfoalcance varchar(20) NOT NULL DEFAULT 'NIVEL',
    nedid integer,
    graid integer,
    ccoid integer NOT NULL,
    cfotipo varchar(20) NOT NULL,
    cfovalor_oficial numeric(10,2) NOT NULL,
    cfocantidad_pensiones integer,
    cfomes_inicio integer,
    cfomes_fin integer,
    cfoanio_inicio integer,
    cfodia_vencimiento integer NOT NULL DEFAULT 5,
    cfogenera_mora boolean NOT NULL DEFAULT false,
    cfomora_tipo varchar(20),
    cfomora_valor numeric(10,2),
    cfoestado boolean NOT NULL DEFAULT true,
    cfoobservacion varchar(250),
    usuid_registro integer NOT NULL,
    cfofecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cfofecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_configuracion_obligacion PRIMARY KEY (cfoid),
    CONSTRAINT fk_cfo_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_cfo_nivel FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT fk_cfo_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_cfo_concepto FOREIGN KEY (ccoid)
        REFERENCES contabilidad_concepto (ccoid),
    CONSTRAINT fk_cfo_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_cfo_alcance
        CHECK (cfoalcance IN ('INSTITUCION', 'NIVEL', 'GRADO')),
    CONSTRAINT ck_cfo_tipo
        CHECK (cfotipo IN ('MATRICULA', 'PENSION')),
    CONSTRAINT ck_cfo_objetivo
        CHECK (
            (cfoalcance = 'INSTITUCION' AND nedid IS NULL AND graid IS NULL)
            OR
            (cfoalcance = 'NIVEL' AND nedid IS NOT NULL AND graid IS NULL)
            OR
            (cfoalcance = 'GRADO' AND nedid IS NULL AND graid IS NOT NULL)
        ),
    CONSTRAINT ck_cfo_valor_oficial
        CHECK (cfovalor_oficial >= 0),
    CONSTRAINT ck_cfo_cantidad_pensiones
        CHECK (cfocantidad_pensiones IS NULL OR cfocantidad_pensiones > 0),
    CONSTRAINT ck_cfo_mes_inicio
        CHECK (cfomes_inicio IS NULL OR cfomes_inicio BETWEEN 1 AND 12),
    CONSTRAINT ck_cfo_mes_fin
        CHECK (cfomes_fin IS NULL OR cfomes_fin BETWEEN 1 AND 12),
    CONSTRAINT ck_cfo_dia_vencimiento
        CHECK (cfodia_vencimiento BETWEEN 1 AND 28),
    CONSTRAINT ck_cfo_mora_tipo
        CHECK (cfomora_tipo IS NULL OR cfomora_tipo IN ('VALOR_FIJO', 'PORCENTAJE')),
    CONSTRAINT ck_cfo_mora_valor
        CHECK (cfomora_valor IS NULL OR cfomora_valor >= 0),
    CONSTRAINT ck_cfo_pension_config
        CHECK (
            (
                cfotipo = 'PENSION'
                AND cfocantidad_pensiones IS NOT NULL
                AND cfomes_inicio IS NOT NULL
                AND cfomes_fin IS NOT NULL
                AND cfoanio_inicio IS NOT NULL
            )
            OR
            (
                cfotipo = 'MATRICULA'
                AND cfocantidad_pensiones IS NULL
                AND cfomes_inicio IS NULL
                AND cfomes_fin IS NULL
                AND cfoanio_inicio IS NULL
            )
        ),
    CONSTRAINT ck_cfo_mora_config
        CHECK (
            (
                cfogenera_mora = false
                AND cfomora_tipo IS NULL
                AND cfomora_valor IS NULL
            )
            OR
            (
                cfogenera_mora = true
                AND cfomora_tipo IS NOT NULL
                AND cfomora_valor IS NOT NULL
            )
        )
);

CREATE TABLE contabilidad_configuracion_modulo (
    ccmid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    ccmrepresentante_rubros_visible boolean NOT NULL DEFAULT false,
    ccmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ccmfecha_modificacion timestamp,
    usuid_registro integer,
    CONSTRAINT pk_contabilidad_configuracion_modulo PRIMARY KEY (ccmid),
    CONSTRAINT uq_contabilidad_configuracion_modulo_periodo UNIQUE (pleid),
    CONSTRAINT fk_ccm_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_ccm_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid)
);

CREATE UNIQUE INDEX uq_cfo_periodo_institucion_tipo_activo
    ON contabilidad_configuracion_obligacion (pleid, cfotipo)
    WHERE cfoestado = true AND cfoalcance = 'INSTITUCION';

CREATE UNIQUE INDEX uq_cfo_periodo_nivel_tipo_activo
    ON contabilidad_configuracion_obligacion (pleid, nedid, cfotipo)
    WHERE cfoestado = true AND cfoalcance = 'NIVEL';

CREATE UNIQUE INDEX uq_cfo_periodo_grado_tipo_activo
    ON contabilidad_configuracion_obligacion (pleid, graid, cfotipo)
    WHERE cfoestado = true AND cfoalcance = 'GRADO';

CREATE TABLE contabilidad_obligacion (
    cobid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    ccoid integer NOT NULL,
    cfoid integer,
    cobtipo varchar(20) NOT NULL,
    cobdescripcion varchar(150) NOT NULL,
    cobanio integer,
    cobmes integer,
    coborden integer NOT NULL DEFAULT 1,
    cobfecha_vencimiento date,
    cobvalor_base numeric(10,2) NOT NULL,
    cobdescuento_tipo varchar(20),
    cobdescuento_valor numeric(10,2),
    cobvalor_descuento numeric(10,2) NOT NULL DEFAULT 0,
    cobvalor_final numeric(10,2) NOT NULL,
    cobvalor_pagado numeric(10,2) NOT NULL DEFAULT 0,
    cobsaldo_pendiente numeric(10,2) NOT NULL,
    cobmotivo_descuento varchar(250),
    cobgenera_mora boolean NOT NULL DEFAULT false,
    cobmora_tipo varchar(20),
    cobmora_valor numeric(10,2),
    cobestado varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    cobobservacion_interna varchar(250),
    usuid_registro integer NOT NULL,
    usuid_anulacion integer,
    cobfecha_anulacion timestamp,
    cobmotivo_anulacion varchar(250),
    cobfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cobfecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_obligacion PRIMARY KEY (cobid),
    CONSTRAINT fk_cob_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_cob_concepto FOREIGN KEY (ccoid)
        REFERENCES contabilidad_concepto (ccoid),
    CONSTRAINT fk_cob_configuracion FOREIGN KEY (cfoid)
        REFERENCES contabilidad_configuracion_obligacion (cfoid),
    CONSTRAINT fk_cob_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_cob_usuario_anulacion FOREIGN KEY (usuid_anulacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_cob_tipo
        CHECK (cobtipo IN ('MATRICULA', 'PENSION')),
    CONSTRAINT ck_cob_mes
        CHECK (cobmes IS NULL OR cobmes BETWEEN 1 AND 12),
    CONSTRAINT ck_cob_valores
        CHECK (
            cobvalor_base >= 0
            AND cobvalor_descuento >= 0
            AND cobvalor_final >= 0
            AND cobvalor_pagado >= 0
            AND cobsaldo_pendiente >= 0
            AND cobvalor_descuento <= cobvalor_base
            AND cobvalor_final = cobvalor_base - cobvalor_descuento
            AND cobvalor_pagado <= cobvalor_final
            AND cobsaldo_pendiente = cobvalor_final - cobvalor_pagado
        ),
    CONSTRAINT ck_cob_descuento_tipo
        CHECK (cobdescuento_tipo IS NULL OR cobdescuento_tipo IN ('VALOR_FIJO', 'PORCENTAJE')),
    CONSTRAINT ck_cob_descuento_valor
        CHECK (cobdescuento_valor IS NULL OR cobdescuento_valor >= 0),
    CONSTRAINT ck_cob_mora_tipo
        CHECK (cobmora_tipo IS NULL OR cobmora_tipo IN ('VALOR_FIJO', 'PORCENTAJE')),
    CONSTRAINT ck_cob_mora_valor
        CHECK (cobmora_valor IS NULL OR cobmora_valor >= 0),
    CONSTRAINT ck_cob_estado
        CHECK (cobestado IN ('PENDIENTE', 'EN_REVISION', 'PAGO_PARCIAL', 'PAGADO', 'VENCIDO', 'ANULADO')),
    CONSTRAINT ck_cob_periodo_pension
        CHECK (
            (
                cobtipo = 'PENSION'
                AND cobanio IS NOT NULL
                AND cobmes IS NOT NULL
            )
            OR
            (
                cobtipo = 'MATRICULA'
                AND cobanio IS NULL
                AND cobmes IS NULL
            )
        ),
    CONSTRAINT ck_cob_anulacion
        CHECK (
            cobestado <> 'ANULADO'
            OR (
                usuid_anulacion IS NOT NULL
                AND cobfecha_anulacion IS NOT NULL
                AND NULLIF(trim(cobmotivo_anulacion), '') IS NOT NULL
            )
        )
);

CREATE UNIQUE INDEX uq_cob_matricula
    ON contabilidad_obligacion (matid)
    WHERE cobtipo = 'MATRICULA';

CREATE UNIQUE INDEX uq_cob_pension_mes
    ON contabilidad_obligacion (matid, cobanio, cobmes)
    WHERE cobtipo = 'PENSION';

CREATE INDEX ix_cob_matricula_estado
    ON contabilidad_obligacion (matid, cobestado);

CREATE INDEX ix_cob_vencimiento_estado
    ON contabilidad_obligacion (cobfecha_vencimiento, cobestado);

CREATE TABLE contabilidad_rubro (
    cruid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    ccoid integer NOT NULL,
    crunombre varchar(150) NOT NULL,
    crudescripcion varchar(250),
    cruvalor numeric(10,2) NOT NULL,
    crufecha_limite date,
    cruestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    usuid_registro integer NOT NULL,
    usuid_anulacion integer,
    crufecha_anulacion timestamp,
    crumotivo_anulacion varchar(250),
    crufecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crufecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_rubro PRIMARY KEY (cruid),
    CONSTRAINT fk_cru_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_cru_concepto FOREIGN KEY (ccoid)
        REFERENCES contabilidad_concepto (ccoid),
    CONSTRAINT fk_cru_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_cru_usuario_anulacion FOREIGN KEY (usuid_anulacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_cru_valor
        CHECK (cruvalor >= 0),
    CONSTRAINT ck_cru_estado
        CHECK (cruestado IN ('ACTIVO', 'CERRADO', 'ANULADO')),
    CONSTRAINT ck_cru_anulacion
        CHECK (
            cruestado <> 'ANULADO'
            OR (
                usuid_anulacion IS NOT NULL
                AND crufecha_anulacion IS NOT NULL
                AND NULLIF(trim(crumotivo_anulacion), '') IS NOT NULL
            )
        )
);

CREATE TABLE contabilidad_rubro_asignacion (
    craid integer GENERATED BY DEFAULT AS IDENTITY,
    cruid integer NOT NULL,
    craalcance varchar(20) NOT NULL,
    pleid integer NOT NULL,
    nedid integer,
    curid integer,
    matid integer,
    crafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_contabilidad_rubro_asignacion PRIMARY KEY (craid),
    CONSTRAINT fk_cra_rubro FOREIGN KEY (cruid)
        REFERENCES contabilidad_rubro (cruid),
    CONSTRAINT fk_cra_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_cra_nivel FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT fk_cra_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_cra_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT ck_cra_alcance
        CHECK (craalcance IN ('TODOS', 'NIVEL', 'CURSO', 'ESTUDIANTE')),
    CONSTRAINT ck_cra_objetivo
        CHECK (
            (craalcance = 'TODOS' AND nedid IS NULL AND curid IS NULL AND matid IS NULL)
            OR
            (craalcance = 'NIVEL' AND nedid IS NOT NULL AND curid IS NULL AND matid IS NULL)
            OR
            (craalcance = 'CURSO' AND nedid IS NULL AND curid IS NOT NULL AND matid IS NULL)
            OR
            (craalcance = 'ESTUDIANTE' AND nedid IS NULL AND curid IS NULL AND matid IS NOT NULL)
        )
);

CREATE TABLE contabilidad_rubro_estudiante (
    creid integer GENERATED BY DEFAULT AS IDENTITY,
    cruid integer NOT NULL,
    matid integer NOT NULL,
    crevalor numeric(10,2) NOT NULL,
    crefecha_limite date,
    creestado varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    creobservacion_interna varchar(250),
    usuid_registro integer NOT NULL,
    usuid_cierre integer,
    crefecha_cierre timestamp,
    cremotivo_cierre varchar(250),
    crefecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    crefecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_rubro_estudiante PRIMARY KEY (creid),
    CONSTRAINT fk_cre_rubro FOREIGN KEY (cruid)
        REFERENCES contabilidad_rubro (cruid),
    CONSTRAINT fk_cre_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_cre_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_cre_usuario_cierre FOREIGN KEY (usuid_cierre)
        REFERENCES usuario (usuid),
    CONSTRAINT uq_cre_rubro_matricula UNIQUE (cruid, matid),
    CONSTRAINT ck_cre_valor
        CHECK (crevalor >= 0),
    CONSTRAINT ck_cre_estado
        CHECK (creestado IN ('PENDIENTE', 'PAGADO', 'VENCIDO', 'EXONERADO', 'NO_APLICA', 'ANULADO')),
    CONSTRAINT ck_cre_cierre
        CHECK (
            creestado IN ('PENDIENTE', 'VENCIDO')
            OR (
                usuid_cierre IS NOT NULL
                AND crefecha_cierre IS NOT NULL
            )
        )
);

CREATE INDEX ix_cre_matricula_estado
    ON contabilidad_rubro_estudiante (matid, creestado);

CREATE INDEX ix_cre_limite_estado
    ON contabilidad_rubro_estudiante (crefecha_limite, creestado);

CREATE TABLE contabilidad_pago (
    cpagid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    cobid_sugerido integer,
    creid_sugerido integer,
    cpagorigen varchar(20) NOT NULL,
    cpagestado varchar(20) NOT NULL DEFAULT 'EN_REVISION',
    cpagvalor_reportado numeric(10,2),
    cpagvalor_aprobado numeric(10,2),
    cmpid integer,
    cpagreferencia varchar(80),
    cpagarchivo_ruta varchar(255),
    cpagarchivo_nombre varchar(180),
    cpagarchivo_extension varchar(10),
    cpagarchivo_mime varchar(100),
    cpagarchivo_tamano integer,
    cpagarchivo_hash varchar(128),
    cpagobservacion_interna varchar(250),
    cpagmotivo_rechazo varchar(250),
    cpagdocumento_externo_sistema varchar(50),
    cpagdocumento_externo_numero varchar(80),
    cpagdocumento_externo_fecha date,
    usuid_registro integer NOT NULL,
    cpagfecha_registro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuid_revision integer,
    cpagfecha_revision timestamp,
    usuid_reverso integer,
    cpagfecha_reverso timestamp,
    cpagmotivo_reverso varchar(250),
    CONSTRAINT pk_contabilidad_pago PRIMARY KEY (cpagid),
    CONSTRAINT fk_cpag_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_cpag_obligacion_sugerida FOREIGN KEY (cobid_sugerido)
        REFERENCES contabilidad_obligacion (cobid),
    CONSTRAINT fk_cpag_rubro_sugerido FOREIGN KEY (creid_sugerido)
        REFERENCES contabilidad_rubro_estudiante (creid),
    CONSTRAINT fk_cpag_metodo FOREIGN KEY (cmpid)
        REFERENCES contabilidad_metodo_pago (cmpid),
    CONSTRAINT fk_cpag_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_cpag_usuario_revision FOREIGN KEY (usuid_revision)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_cpag_usuario_reverso FOREIGN KEY (usuid_reverso)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_cpag_origen
        CHECK (cpagorigen IN ('REPRESENTANTE', 'INTERNO')),
    CONSTRAINT ck_cpag_estado
        CHECK (cpagestado IN ('EN_REVISION', 'APROBADO', 'RECHAZADO', 'ANULADO', 'REVERSADO')),
    CONSTRAINT ck_cpag_valores
        CHECK (
            (cpagvalor_reportado IS NULL OR cpagvalor_reportado >= 0)
            AND (cpagvalor_aprobado IS NULL OR cpagvalor_aprobado >= 0)
        ),
    CONSTRAINT ck_cpag_archivo_tamano
        CHECK (cpagarchivo_tamano IS NULL OR cpagarchivo_tamano BETWEEN 1 AND 2097152),
    CONSTRAINT ck_cpag_archivo_extension
        CHECK (
            cpagarchivo_extension IS NULL
            OR cpagarchivo_extension IN ('PDF', 'JPG', 'JPEG', 'PNG')
        ),
    CONSTRAINT ck_cpag_representante_objetivo
        CHECK (
            cpagorigen <> 'REPRESENTANTE'
            OR (
                cobid_sugerido IS NOT NULL
                AND creid_sugerido IS NULL
                AND cpagarchivo_ruta IS NOT NULL
                AND cpagvalor_reportado IS NOT NULL
            )
        ),
    CONSTRAINT ck_cpag_revision
        CHECK (
            cpagestado = 'EN_REVISION'
            OR (
                usuid_revision IS NOT NULL
                AND cpagfecha_revision IS NOT NULL
            )
        ),
    CONSTRAINT ck_cpag_rechazo
        CHECK (
            cpagestado <> 'RECHAZADO'
            OR NULLIF(trim(cpagmotivo_rechazo), '') IS NOT NULL
        ),
    CONSTRAINT ck_cpag_aprobacion
        CHECK (
            cpagestado <> 'APROBADO'
            OR cpagvalor_aprobado IS NOT NULL
        ),
    CONSTRAINT ck_cpag_reverso
        CHECK (
            cpagestado <> 'REVERSADO'
            OR (
                usuid_reverso IS NOT NULL
                AND cpagfecha_reverso IS NOT NULL
                AND NULLIF(trim(cpagmotivo_reverso), '') IS NOT NULL
            )
        )
);

CREATE INDEX ix_cpag_matricula_estado
    ON contabilidad_pago (matid, cpagestado);

CREATE INDEX ix_cpag_revision_estado
    ON contabilidad_pago (cpagestado, cpagfecha_registro);

CREATE INDEX ix_cpag_hash
    ON contabilidad_pago (cpagarchivo_hash);

CREATE INDEX ix_cpag_referencia
    ON contabilidad_pago (cpagreferencia);

CREATE TABLE contabilidad_pago_obligacion (
    cpoid integer GENERATED BY DEFAULT AS IDENTITY,
    cpagid integer NOT NULL,
    cobid integer NOT NULL,
    cpovalor_aplicado numeric(10,2) NOT NULL,
    cpoestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    cpofecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_contabilidad_pago_obligacion PRIMARY KEY (cpoid),
    CONSTRAINT fk_cpo_pago FOREIGN KEY (cpagid)
        REFERENCES contabilidad_pago (cpagid),
    CONSTRAINT fk_cpo_obligacion FOREIGN KEY (cobid)
        REFERENCES contabilidad_obligacion (cobid),
    CONSTRAINT ck_cpo_valor
        CHECK (cpovalor_aplicado > 0),
    CONSTRAINT ck_cpo_estado
        CHECK (cpoestado IN ('ACTIVO', 'REVERSADO'))
);

CREATE INDEX ix_cpo_obligacion
    ON contabilidad_pago_obligacion (cobid, cpoestado);

CREATE TABLE contabilidad_pago_rubro (
    cprid integer GENERATED BY DEFAULT AS IDENTITY,
    cpagid integer NOT NULL,
    creid integer NOT NULL,
    cprvalor_aplicado numeric(10,2) NOT NULL,
    cprestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    cprfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_contabilidad_pago_rubro PRIMARY KEY (cprid),
    CONSTRAINT fk_cpr_pago FOREIGN KEY (cpagid)
        REFERENCES contabilidad_pago (cpagid),
    CONSTRAINT fk_cpr_rubro_estudiante FOREIGN KEY (creid)
        REFERENCES contabilidad_rubro_estudiante (creid),
    CONSTRAINT ck_cpr_valor
        CHECK (cprvalor_aplicado > 0),
    CONSTRAINT ck_cpr_estado
        CHECK (cprestado IN ('ACTIVO', 'REVERSADO'))
);

CREATE UNIQUE INDEX uq_cpr_rubro_activo
    ON contabilidad_pago_rubro (creid)
    WHERE cprestado = 'ACTIVO';

CREATE TABLE contabilidad_saldo_favor (
    csfid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    cpagid_origen integer NOT NULL,
    csfvalor_inicial numeric(10,2) NOT NULL,
    csfvalor_disponible numeric(10,2) NOT NULL,
    csfestado varchar(20) NOT NULL DEFAULT 'ACTIVO',
    csfobservacion varchar(250),
    csffecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    csffecha_modificacion timestamp,
    CONSTRAINT pk_contabilidad_saldo_favor PRIMARY KEY (csfid),
    CONSTRAINT fk_csf_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_csf_pago_origen FOREIGN KEY (cpagid_origen)
        REFERENCES contabilidad_pago (cpagid),
    CONSTRAINT ck_csf_valores
        CHECK (
            csfvalor_inicial > 0
            AND csfvalor_disponible >= 0
            AND csfvalor_disponible <= csfvalor_inicial
        ),
    CONSTRAINT ck_csf_estado
        CHECK (csfestado IN ('ACTIVO', 'CONSUMIDO', 'REVERSADO'))
);

CREATE INDEX ix_csf_matricula_estado
    ON contabilidad_saldo_favor (matid, csfestado);

CREATE TABLE contabilidad_saldo_movimiento (
    csmid integer GENERATED BY DEFAULT AS IDENTITY,
    csfid integer NOT NULL,
    cobid integer,
    csmvalor numeric(10,2) NOT NULL,
    csmtipo varchar(20) NOT NULL,
    csmobservacion varchar(250),
    usuid_registro integer NOT NULL,
    csmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_contabilidad_saldo_movimiento PRIMARY KEY (csmid),
    CONSTRAINT fk_csm_saldo FOREIGN KEY (csfid)
        REFERENCES contabilidad_saldo_favor (csfid),
    CONSTRAINT fk_csm_obligacion FOREIGN KEY (cobid)
        REFERENCES contabilidad_obligacion (cobid),
    CONSTRAINT fk_csm_usuario FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_csm_valor
        CHECK (csmvalor > 0),
    CONSTRAINT ck_csm_tipo
        CHECK (csmtipo IN ('APLICACION', 'REVERSO'))
);

CREATE TABLE contabilidad_auditoria (
    cauid integer GENERATED BY DEFAULT AS IDENTITY,
    cautabla varchar(80) NOT NULL,
    cauregistro_id integer NOT NULL,
    cauaccion varchar(40) NOT NULL,
    cauvalor_anterior text,
    cauvalor_nuevo text,
    cauobservacion varchar(250),
    usuid integer NOT NULL,
    caufecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_contabilidad_auditoria PRIMARY KEY (cauid),
    CONSTRAINT fk_cau_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_cau_accion
        CHECK (
            cauaccion IN (
                'CREAR',
                'EDITAR',
                'ANULAR',
                'APROBAR',
                'RECHAZAR',
                'REVERSAR',
                'DOCUMENTO_EXTERNO',
                'DUPLICADO_ACEPTADO'
            )
        )
);

CREATE INDEX ix_cau_entidad
    ON contabilidad_auditoria (cautabla, cauregistro_id);

CREATE INDEX ix_cau_fecha
    ON contabilidad_auditoria (caufecha_creacion);
