-- Ajuste incremental para bases ya instaladas.
-- Agrega configuracion global del modulo contable por periodo.

CREATE TABLE IF NOT EXISTS contabilidad_configuracion_modulo (
    ccmid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    ccmrepresentante_rubros_visible boolean NOT NULL DEFAULT false,
    ccmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ccmfecha_modificacion timestamp,
    usuid_registro integer,
    CONSTRAINT pk_contabilidad_configuracion_modulo PRIMARY KEY (ccmid),
    CONSTRAINT uq_contabilidad_configuracion_modulo_periodo UNIQUE (pleid),
    CONSTRAINT fk_ccm_periodo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_ccm_usuario_registro FOREIGN KEY (usuid_registro)
        REFERENCES usuario (usuid)
);
