CREATE TABLE comunicado (
    comid integer GENERATED BY DEFAULT AS IDENTITY,
    comtitulo varchar(180) NOT NULL,
    commensaje text NOT NULL,
    comestado varchar(20) NOT NULL DEFAULT 'BORRADOR',
    comcriterios_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    comdestino_resumen varchar(500),
    comfecha_publicacion timestamp,
    comfecha_anulacion timestamp,
    commotivo_anulacion varchar(250),
    usuid_creacion integer NOT NULL,
    usuid_publicacion integer,
    usuid_anulacion integer,
    comfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comfecha_modificacion timestamp,
    CONSTRAINT pk_comunicado PRIMARY KEY (comid),
    CONSTRAINT fk_comunicado_usuario_creacion FOREIGN KEY (usuid_creacion)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_comunicado_usuario_publicacion FOREIGN KEY (usuid_publicacion)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_comunicado_usuario_anulacion FOREIGN KEY (usuid_anulacion)
        REFERENCES usuario (usuid),
    CONSTRAINT ck_comunicado_estado
        CHECK (comestado IN ('BORRADOR', 'PUBLICADO', 'ANULADO'))
);

CREATE TABLE comunicado_destinatario (
    cdeid integer GENERATED BY DEFAULT AS IDENTITY,
    comid integer NOT NULL,
    usuid integer NOT NULL,
    perid integer NOT NULL,
    cdetipo varchar(30) NOT NULL DEFAULT 'USUARIO',
    cdeorigen varchar(80),
    cdeestado_lectura varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    cdefecha_lectura timestamp,
    cdefecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cdefecha_modificacion timestamp,
    CONSTRAINT pk_comunicado_destinatario PRIMARY KEY (cdeid),
    CONSTRAINT fk_comunicado_destinatario_comunicado FOREIGN KEY (comid)
        REFERENCES comunicado (comid),
    CONSTRAINT fk_comunicado_destinatario_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_comunicado_destinatario_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_comunicado_destinatario_comid_usuid UNIQUE (comid, usuid),
    CONSTRAINT ck_comunicado_destinatario_lectura
        CHECK (cdeestado_lectura IN ('PENDIENTE', 'LEIDO'))
);

CREATE TABLE comunicado_entrega (
    cenid integer GENERATED BY DEFAULT AS IDENTITY,
    comid integer NOT NULL,
    cdeid integer NOT NULL,
    cencanal varchar(20) NOT NULL,
    cendestino varchar(180),
    cenestado varchar(20) NOT NULL DEFAULT 'PENDIENTE',
    cenintentos integer NOT NULL DEFAULT 0,
    cenmax_intentos integer NOT NULL DEFAULT 3,
    cenfecha_programada timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cenfecha_procesamiento timestamp,
    cenfecha_envio timestamp,
    cenultimo_error text,
    cenprovider_message_id varchar(180),
    cenfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cenfecha_modificacion timestamp,
    CONSTRAINT pk_comunicado_entrega PRIMARY KEY (cenid),
    CONSTRAINT fk_comunicado_entrega_comunicado FOREIGN KEY (comid)
        REFERENCES comunicado (comid),
    CONSTRAINT fk_comunicado_entrega_destinatario FOREIGN KEY (cdeid)
        REFERENCES comunicado_destinatario (cdeid),
    CONSTRAINT ck_comunicado_entrega_canal
        CHECK (cencanal IN ('SISTEMA', 'EMAIL', 'WHATSAPP')),
    CONSTRAINT ck_comunicado_entrega_estado
        CHECK (cenestado IN ('PENDIENTE', 'PROCESANDO', 'ENVIADO', 'FALLIDO', 'OMITIDO')),
    CONSTRAINT uq_comunicado_entrega_cdeid_canal UNIQUE (cdeid, cencanal)
);

CREATE TABLE mensajeria_configuracion (
    mcoid integer GENERATED BY DEFAULT AS IDENTITY,
    mcoproveedor varchar(40) NOT NULL DEFAULT 'SMTP',
    mcoactivo boolean NOT NULL DEFAULT false,
    mcoremitente_email varchar(180),
    mcoremitente_nombre varchar(120),
    mcosmtp_host varchar(180),
    mcosmtp_puerto integer,
    mcosmtp_seguridad varchar(20),
    mcosmtp_usuario varchar(180),
    mcosmtp_clave_secreta varchar(180),
    mcolote_maximo integer NOT NULL DEFAULT 25,
    mcomax_intentos integer NOT NULL DEFAULT 3,
    mcofecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mcofecha_modificacion timestamp,
    CONSTRAINT pk_mensajeria_configuracion PRIMARY KEY (mcoid),
    CONSTRAINT ck_mensajeria_configuracion_seguridad
        CHECK (mcosmtp_seguridad IS NULL OR mcosmtp_seguridad IN ('TLS', 'SSL', 'NINGUNA'))
);

CREATE UNIQUE INDEX uq_mensajeria_configuracion_unica
    ON mensajeria_configuracion ((true));

INSERT INTO mensajeria_configuracion (
    mcoproveedor,
    mcoactivo,
    mcolote_maximo,
    mcomax_intentos
) VALUES (
    'SMTP',
    false,
    25,
    3
) ON CONFLICT DO NOTHING;

CREATE INDEX idx_comunicado_estado_fecha
    ON comunicado (comestado, comfecha_publicacion DESC);

CREATE INDEX idx_comunicado_destinatario_usuario_lectura
    ON comunicado_destinatario (usuid, cdeestado_lectura);

CREATE INDEX idx_comunicado_entrega_canal_estado
    ON comunicado_entrega (cencanal, cenestado, cenfecha_programada);
