CREATE TABLE institucion (
    insid integer GENERATED BY DEFAULT AS IDENTITY,
    insnombre varchar(150) NOT NULL,
    insrazonsocial varchar(200),
    insruc varchar(13),
    inscodigoamie varchar(20),
    insdireccion varchar(250),
    instelefono varchar(20),
    inscorreoelectronico varchar(150),
    insrepresentantelegal varchar(150),
    CONSTRAINT pk_institucion PRIMARY KEY (insid),
    CONSTRAINT uq_institucion_insruc UNIQUE (insruc),
    CONSTRAINT uq_institucion_inscodigoamie UNIQUE (inscodigoamie)
);

CREATE TABLE periodo_lectivo (
    pleid integer GENERATED BY DEFAULT AS IDENTITY,
    pledescripcion varchar(20) NOT NULL,
    plefechainicio date NOT NULL,
    plefechafin date NOT NULL,
    pleactivo boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_periodo_lectivo PRIMARY KEY (pleid)
);

CREATE TABLE paralelo (
    prlid integer GENERATED BY DEFAULT AS IDENTITY,
    prlnombre varchar(10) NOT NULL,
    CONSTRAINT pk_paralelo PRIMARY KEY (prlid),
    CONSTRAINT uq_paralelo_prlnombre UNIQUE (prlnombre)
);

CREATE TABLE nivel_educativo (
    nedid integer GENERATED BY DEFAULT AS IDENTITY,
    nednombre varchar(50) NOT NULL,
    CONSTRAINT pk_nivel_educativo PRIMARY KEY (nedid),
    CONSTRAINT uq_nivel_educativo_nednombre UNIQUE (nednombre)
);

CREATE TABLE parentesco (
    pteid integer GENERATED BY DEFAULT AS IDENTITY,
    ptenombre varchar(50) NOT NULL,
    CONSTRAINT pk_parentesco PRIMARY KEY (pteid),
    CONSTRAINT uq_parentesco_ptenombre UNIQUE (ptenombre)
);

CREATE TABLE estado_civil (
    eciid integer GENERATED BY DEFAULT AS IDENTITY,
    ecinombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_civil PRIMARY KEY (eciid),
    CONSTRAINT uq_estado_civil_ecinombre UNIQUE (ecinombre)
);

CREATE TABLE instruccion (
    istid integer GENERATED BY DEFAULT AS IDENTITY,
    istnombre varchar(50) NOT NULL,
    CONSTRAINT pk_instruccion PRIMARY KEY (istid),
    CONSTRAINT uq_instruccion_istnombre UNIQUE (istnombre)
);

CREATE TABLE grado (
    graid integer GENERATED BY DEFAULT AS IDENTITY,
    nedid integer NOT NULL,
    granombre varchar(50) NOT NULL,
    CONSTRAINT pk_grado PRIMARY KEY (graid),
    CONSTRAINT fk_grado_nivel_educativo FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT uq_grado_nedid_granombre UNIQUE (nedid, granombre)
);

CREATE TABLE estado_matricula (
    emdid integer GENERATED BY DEFAULT AS IDENTITY,
    emdnombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_matricula PRIMARY KEY (emdid),
    CONSTRAINT uq_estado_matricula_emdnombre UNIQUE (emdnombre)
);

CREATE TABLE condicion_vivienda (
    cviid integer GENERATED BY DEFAULT AS IDENTITY,
    cvinombre varchar(80) NOT NULL,
    cviactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_condicion_vivienda PRIMARY KEY (cviid),
    CONSTRAINT uq_condicion_vivienda_cvinombre UNIQUE (cvinombre)
);

CREATE TABLE grupo_sanguineo (
    gsid integer GENERATED BY DEFAULT AS IDENTITY,
    gsnombre varchar(10) NOT NULL,
    gsactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_grupo_sanguineo PRIMARY KEY (gsid),
    CONSTRAINT uq_grupo_sanguineo_gsnombre UNIQUE (gsnombre)
);

CREATE TABLE atencion_medica (
    amid integer GENERATED BY DEFAULT AS IDENTITY,
    amnombre varchar(80) NOT NULL,
    amactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_atencion_medica PRIMARY KEY (amid),
    CONSTRAINT uq_atencion_medica_amnombre UNIQUE (amnombre)
);

CREATE TABLE tipo_condicion_salud (
    tcsid integer GENERATED BY DEFAULT AS IDENTITY,
    tcsnombre varchar(80) NOT NULL,
    tcsactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_condicion_salud PRIMARY KEY (tcsid),
    CONSTRAINT uq_tipo_condicion_salud_tcsnombre UNIQUE (tcsnombre)
);

CREATE TABLE seguro_medico (
    smid integer GENERATED BY DEFAULT AS IDENTITY,
    smnombre varchar(120) NOT NULL,
    smactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_seguro_medico PRIMARY KEY (smid),
    CONSTRAINT uq_seguro_medico_smnombre UNIQUE (smnombre)
);

CREATE TABLE tipo_embarazo (
    teid integer GENERATED BY DEFAULT AS IDENTITY,
    tenombre varchar(50) NOT NULL,
    teactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_embarazo PRIMARY KEY (teid),
    CONSTRAINT uq_tipo_embarazo_tenombre UNIQUE (tenombre)
);

CREATE TABLE tipo_parto (
    tpid integer GENERATED BY DEFAULT AS IDENTITY,
    tpnombre varchar(50) NOT NULL,
    tpactivo boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_tipo_parto PRIMARY KEY (tpid),
    CONSTRAINT uq_tipo_parto_tpnombre UNIQUE (tpnombre)
);

CREATE TABLE documento_matricula (
    domid integer GENERATED BY DEFAULT AS IDENTITY,
    domnombre varchar(150) NOT NULL,
    domdescripcion varchar(250),
    domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO',
    domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO',
    domurl varchar(255),
    domplantilla_archivo varchar(255),
    domplantilla_extension varchar(10),
    domobligatorio boolean NOT NULL DEFAULT true,
    domactivo boolean NOT NULL DEFAULT true,
    domfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domfecha_modificacion timestamp,
    CONSTRAINT pk_documento_matricula PRIMARY KEY (domid),
    CONSTRAINT uq_documento_matricula_domnombre UNIQUE (domnombre),
    CONSTRAINT ck_documento_matricula_domtipo
        CHECK (domtipo IN ('ESTATICO', 'PLANTILLA')),
    CONSTRAINT ck_documento_matricula_domorigen
        CHECK (domorigen IN ('ARCHIVO', 'URL')),
    CONSTRAINT ck_documento_matricula_domplantilla_extension
        CHECK (
            domplantilla_extension IS NULL
            OR domplantilla_extension IN ('DOCX')
        ),
    CONSTRAINT ck_documento_matricula_contenido
        CHECK (
            (
                domtipo = 'ESTATICO'
                AND (
                    (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
                    OR
                    (domorigen = 'URL' AND domurl IS NOT NULL)
                )
                AND domplantilla_archivo IS NULL
            )
            OR
            (
                domtipo = 'PLANTILLA'
                AND domorigen = 'ARCHIVO'
                AND domplantilla_archivo IS NOT NULL
                AND domplantilla_extension = 'DOCX'
            )
        )
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE documento_matricula
-- ADD COLUMN domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO';
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO';
--
-- ALTER TABLE documento_matricula
-- ALTER COLUMN domurl DROP NOT NULL;
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domplantilla_archivo varchar(255);
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domplantilla_extension varchar(10);
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domtipo
-- CHECK (domtipo IN ('ESTATICO', 'PLANTILLA'));
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domorigen
-- CHECK (domorigen IN ('ARCHIVO', 'URL'));
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domplantilla_extension
-- CHECK (
--     domplantilla_extension IS NULL
--     OR domplantilla_extension IN ('DOCX')
-- );
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_contenido
-- CHECK (
--     (
--         domtipo = 'ESTATICO'
--         AND (
--             (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
--             OR
--             (domorigen = 'URL' AND domurl IS NOT NULL)
--         )
--         AND domplantilla_archivo IS NULL
--     )
--     OR
--     (
--         domtipo = 'PLANTILLA'
--         AND domorigen = 'ARCHIVO'
--         AND domplantilla_archivo IS NOT NULL
--         AND domplantilla_extension = 'DOCX'
--     )
-- );

CREATE TABLE curso (
    curid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    graid integer NOT NULL,
    prlid integer NOT NULL,
    curestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_curso PRIMARY KEY (curid),
    CONSTRAINT fk_curso_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_curso_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_curso_paralelo FOREIGN KEY (prlid)
        REFERENCES paralelo (prlid),
    CONSTRAINT uq_curso_pleid_graid_prlid UNIQUE (pleid, graid, prlid)
);

CREATE TABLE persona (
    perid integer GENERATED BY DEFAULT AS IDENTITY,
    percedula varchar(10) NOT NULL,
    pernombres varchar(100) NOT NULL,
    perapellidos varchar(100) NOT NULL,
    pertelefono1 varchar(20),
    pertelefono2 varchar(20),
    percorreo varchar(150),
    persexo varchar(20),
    perfechanacimiento date,
    eciid integer,
    istid integer,
    perprofesion varchar(150),
    perocupacion varchar(150),
    perlugardetrabajo varchar(150),
    perhablaingles boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_persona PRIMARY KEY (perid),
    CONSTRAINT uq_persona_percedula UNIQUE (percedula),
    CONSTRAINT fk_persona_estado_civil FOREIGN KEY (eciid)
        REFERENCES estado_civil (eciid),
    CONSTRAINT fk_persona_instruccion FOREIGN KEY (istid)
        REFERENCES instruccion (istid)
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE persona
-- ADD COLUMN perfechanacimiento date;
--
-- ALTER TABLE persona
-- ADD COLUMN eciid integer;
--
-- ALTER TABLE persona
-- ADD COLUMN istid integer;
--
-- ALTER TABLE persona
-- ADD COLUMN perprofesion varchar(150);
--
-- ALTER TABLE persona
-- ADD COLUMN perocupacion varchar(150);
--
-- ALTER TABLE persona
-- ADD COLUMN perhablaingles boolean NOT NULL DEFAULT false;
--
-- ALTER TABLE persona
-- ADD CONSTRAINT fk_persona_estado_civil
-- FOREIGN KEY (eciid)
-- REFERENCES estado_civil (eciid);
--
-- ALTER TABLE persona
-- ADD CONSTRAINT fk_persona_instruccion
-- FOREIGN KEY (istid)
-- REFERENCES instruccion (istid);

CREATE TABLE estudiante (
    estid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    estlugarnacimiento varchar(150),
    estdireccion varchar(250),
    estparroquia varchar(100),
    estestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_estudiante PRIMARY KEY (estid),
    CONSTRAINT fk_estudiante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_estudiante_perid UNIQUE (perid)
);

CREATE TABLE estudiante_contexto_familiar (
    ecfid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    ecfconvivecon varchar(250),
    ecfnumerohermanos integer,
    ecfposicionhermanos varchar(50),
    ecffecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ecffecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_contexto_familiar PRIMARY KEY (ecfid),
    CONSTRAINT fk_estudiante_contexto_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT uq_estudiante_contexto_familiar_estid UNIQUE (estid)
);
CREATE TABLE estudiante_convive_con (
    eccid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    pteid integer NOT NULL,
    eccfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    eccfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_convive_con PRIMARY KEY (eccid),
    CONSTRAINT fk_estudiante_convive_con_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_convive_con_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_estudiante_convive_con_estid_pteid UNIQUE (estid, pteid)
);

CREATE TABLE estudiante_vivienda (
    estvid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    cviid integer NOT NULL,
    estvdescripcion varchar(500),
    estvluzelectrica boolean NOT NULL DEFAULT false,
    estvaguapotable boolean NOT NULL DEFAULT false,
    estvsshh boolean NOT NULL DEFAULT false,
    estvtelefono boolean NOT NULL DEFAULT false,
    estvcable boolean NOT NULL DEFAULT false,
    estvfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    estvfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_vivienda PRIMARY KEY (estvid),
    CONSTRAINT fk_estudiante_vivienda_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_vivienda_condicion_vivienda FOREIGN KEY (cviid)
        REFERENCES condicion_vivienda (cviid),
    CONSTRAINT uq_estudiante_vivienda_estid UNIQUE (estid)
);

CREATE TABLE estudiante_contexto_salud (
    ecsid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    gsid integer,
    ecstienediscapacidad boolean NOT NULL DEFAULT false,
    ecsdetallediscapacidad varchar(500),
    amid integer,
    ecsfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ecsfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_contexto_salud PRIMARY KEY (ecsid),
    CONSTRAINT fk_estudiante_contexto_salud_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_contexto_salud_grupo_sanguineo FOREIGN KEY (gsid)
        REFERENCES grupo_sanguineo (gsid),
    CONSTRAINT fk_estudiante_contexto_salud_atencion_medica FOREIGN KEY (amid)
        REFERENCES atencion_medica (amid),
    CONSTRAINT uq_estudiante_contexto_salud_estid UNIQUE (estid)
);

CREATE TABLE estudiante_condicion_salud (
    ecsaid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    tcsid integer NOT NULL,
    ecsadescripcion varchar(500) NOT NULL,
    ecsamedicamentos varchar(500),
    ecsaobservacion varchar(500),
    ecsavigente boolean NOT NULL DEFAULT true,
    ecsafecha_registro timestamp NOT NULL DEFAULT current_timestamp,
    ecsafecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_condicion_salud PRIMARY KEY (ecsaid),
    CONSTRAINT fk_estudiante_condicion_salud_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_condicion_salud_tipo FOREIGN KEY (tcsid)
        REFERENCES tipo_condicion_salud (tcsid)
);

CREATE TABLE estudiante_medicion_salud (
    emsid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    emspeso numeric(5,2) NOT NULL,
    emstalla numeric(4,2) NOT NULL,
    emsimc numeric(5,2) NOT NULL,
    emsfecha_medicion date NOT NULL,
    emsobservacion varchar(250),
    emsfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    emsfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_medicion_salud PRIMARY KEY (emsid),
    CONSTRAINT fk_estudiante_medicion_salud_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid)
);

CREATE TABLE estudiante_historia_vital (
    ehvid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    ehvedadmadre integer,
    ehvcomplicacionesembarazo varchar(500),
    ehvmedicacionembarazo varchar(500),
    teid integer,
    tpid integer,
    ehvdetalleembarazo varchar(1000),
    ehvpesonacer varchar(20),
    ehvtallanacer varchar(20),
    ehvedadcaminar varchar(50),
    ehvedadhablar varchar(50),
    ehvperiodolactancia varchar(50),
    ehvedadbiberon varchar(50),
    ehvedadcontrolesfinteres varchar(50),
    ehvfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ehvfecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_historia_vital PRIMARY KEY (ehvid),
    CONSTRAINT fk_estudiante_historia_vital_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_estudiante_historia_vital_tipo_embarazo FOREIGN KEY (teid)
        REFERENCES tipo_embarazo (teid),
    CONSTRAINT fk_estudiante_historia_vital_tipo_parto FOREIGN KEY (tpid)
        REFERENCES tipo_parto (tpid),
    CONSTRAINT uq_estudiante_historia_vital_estid UNIQUE (estid)
);

CREATE TABLE estudiante_contexto_academico (
    ecaid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    ecafechaingresoinstitucion date,
    ecaharepetidoanios boolean NOT NULL DEFAULT false,
    ecadetallerepeticion varchar(500),
    ecaasignaturaspreferencia varchar(500),
    ecaasignaturasdificultad varchar(500),
    ecaactividadesextras varchar(500),
    ecafecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    ecafecha_modificacion timestamp,
    CONSTRAINT pk_estudiante_contexto_academico PRIMARY KEY (ecaid),
    CONSTRAINT fk_estudiante_contexto_academico_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT uq_estudiante_contexto_academico_estid UNIQUE (estid)
);

CREATE TABLE tipo_matricula (
    tmaid integer GENERATED BY DEFAULT AS IDENTITY,
    tmanombre varchar(50) NOT NULL,
    tmadescripcion varchar(150),
    tmaestado boolean NOT NULL DEFAULT true,
    tmafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tmafecha_modificacion timestamp,
    CONSTRAINT pk_tipo_matricula PRIMARY KEY (tmaid),
    CONSTRAINT uq_tipo_matricula_tmanombre UNIQUE (tmanombre)
);

CREATE TABLE configuracion_matricula (
    cmid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    cmhabilitada boolean NOT NULL DEFAULT false,
    cmfechainicio date,
    cmfechafin date,
    cmhabilitadaextraordinaria boolean NOT NULL DEFAULT false,
    cmfechainicioextraordinaria date,
    cmfechafinextraordinaria date,
    cmobservacion varchar(250),
    cmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmfecha_modificacion timestamp,
    CONSTRAINT pk_configuracion_matricula PRIMARY KEY (cmid),
    CONSTRAINT fk_configuracion_matricula_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT uq_configuracion_matricula_pleid UNIQUE (pleid),
    CONSTRAINT ck_configuracion_matricula_fechas_ordinarias
        CHECK (
            cmfechainicio IS NULL
            OR cmfechafin IS NULL
            OR cmfechainicio <= cmfechafin
        ),
    CONSTRAINT ck_configuracion_matricula_fechas_extraordinarias
        CHECK (
            cmfechainicioextraordinaria IS NULL
            OR cmfechafinextraordinaria IS NULL
            OR cmfechainicioextraordinaria <= cmfechafinextraordinaria
        )
);

CREATE TABLE matricula (
    matid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    curid integer NOT NULL,
    matfecha date NOT NULL,
    matfoto varchar(255),
    emdid integer NOT NULL,
    tmaid integer NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (matid),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_matricula_estado_matricula FOREIGN KEY (emdid)
        REFERENCES estado_matricula (emdid),
    CONSTRAINT fk_matricula_tipo_matricula FOREIGN KEY (tmaid)
        REFERENCES tipo_matricula (tmaid),
    CONSTRAINT uq_matricula_estid_curid UNIQUE (estid, curid)
);

CREATE TABLE matricula_representante (
    mreid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_matricula_representante PRIMARY KEY (mreid),
    CONSTRAINT fk_matricula_representante_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_representante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_matricula_representante_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_matricula_representante_matid UNIQUE (matid)
);

CREATE TABLE matricula_recurso_tecnologico (
    mrtid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mrtinternet boolean NOT NULL DEFAULT false,
    mrtcomputador boolean NOT NULL DEFAULT false,
    mrtlaptop boolean NOT NULL DEFAULT false,
    mrttablet boolean NOT NULL DEFAULT false,
    mrtcelular boolean NOT NULL DEFAULT false,
    mrtimpresora boolean NOT NULL DEFAULT false,
    mrtfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_recurso_tecnologico PRIMARY KEY (mrtid),
    CONSTRAINT fk_matricula_recurso_tecnologico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_recurso_tecnologico_matid UNIQUE (matid)
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE matricula_recurso_tecnologico
-- ADD COLUMN mrtimpresora boolean NOT NULL DEFAULT false;

CREATE TABLE matricula_seguro_medico (
    msmid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    smid integer NOT NULL,
    msmtelefono varchar(30),
    msmobservacion varchar(250),
    msmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    msmfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_seguro_medico PRIMARY KEY (msmid),
    CONSTRAINT fk_matricula_seguro_medico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_seguro_medico_seguro_medico FOREIGN KEY (smid)
        REFERENCES seguro_medico (smid),
    CONSTRAINT uq_matricula_seguro_medico_matid UNIQUE (matid)
);

CREATE TABLE matricula_facturacion (
    mfcid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mfcnombre varchar(150) NOT NULL,
    mfctipoidentificacion varchar(10) NOT NULL,
    mfcidentificacion varchar(13) NOT NULL,
    mfcdireccion varchar(250),
    mfccorreo varchar(150),
    mfctelefono varchar(20),
    mfcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mfcfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_facturacion PRIMARY KEY (mfcid),
    CONSTRAINT fk_matricula_facturacion_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_facturacion_matid UNIQUE (matid),
    CONSTRAINT ck_matricula_facturacion_tipo_identificacion
        CHECK (mfctipoidentificacion IN ('CEDULA', 'RUC'))
);

CREATE TABLE matricula_documento_generado (
    mdgid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgnombre varchar(180) NOT NULL,
    mdgruta_archivo varchar(255) NOT NULL,
    mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
    mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdghash varchar(128),
    mdgobservacion varchar(250),
    CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
    CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT ck_matricula_documento_generado_extension
        CHECK (mdgextension IN ('DOCX', 'PDF'))
);

-- Para una base de datos ya existente, aplicar manualmente:
-- CREATE TABLE matricula_documento_generado (
--     mdgid integer GENERATED BY DEFAULT AS IDENTITY,
--     matid integer NOT NULL,
--     domid integer NOT NULL,
--     mdgnombre varchar(180) NOT NULL,
--     mdgruta_archivo varchar(255) NOT NULL,
--     mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
--     mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     mdghash varchar(128),
--     mdgobservacion varchar(250),
--     CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
--     CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
--         REFERENCES matricula (matid),
--     CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
--         REFERENCES documento_matricula (domid),
--     CONSTRAINT ck_matricula_documento_generado_extension
--         CHECK (mdgextension IN ('DOCX', 'PDF'))
-- );

CREATE TABLE matricula_aceptacion_documentos (
    madid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgid integer,
    madaceptado boolean NOT NULL DEFAULT false,
    madfecha_aceptacion timestamp,
    madobservacion varchar(250),
    CONSTRAINT pk_matricula_aceptacion_documentos PRIMARY KEY (madid),
    CONSTRAINT fk_matricula_aceptacion_documentos_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_aceptacion_documentos_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT fk_matricula_aceptacion_documentos_generado FOREIGN KEY (mdgid)
        REFERENCES matricula_documento_generado (mdgid),
    CONSTRAINT uq_matricula_aceptacion_documentos_matid_domid UNIQUE (matid, domid)
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE matricula_aceptacion_documentos
-- ADD COLUMN mdgid integer;
--
-- ALTER TABLE matricula_aceptacion_documentos
-- ADD CONSTRAINT fk_matricula_aceptacion_documentos_generado
-- FOREIGN KEY (mdgid)
-- REFERENCES matricula_documento_generado (mdgid);

CREATE TABLE familiar (
    famid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_familiar PRIMARY KEY (famid),
    CONSTRAINT fk_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_familiar_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_familiar_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_familiar_estid_perid_pteid UNIQUE (estid, perid, pteid)
);
