CREATE TABLE institucion (
    insid integer GENERATED BY DEFAULT AS IDENTITY,
    insnombre varchar(150) NOT NULL,
    insrazonsocial varchar(200),
    insruc varchar(13),
    inscodigoamie varchar(20),
    insdireccion varchar(250),
    instelefono varchar(20),
    inscorreoelectronico varchar(150),
    insrepresentantelegal varchar(150),
    CONSTRAINT pk_institucion PRIMARY KEY (insid),
    CONSTRAINT uq_institucion_insruc UNIQUE (insruc),
    CONSTRAINT uq_institucion_inscodigoamie UNIQUE (inscodigoamie)
);

CREATE TABLE periodo_lectivo (
    pleid integer GENERATED BY DEFAULT AS IDENTITY,
    pledescripcion varchar(20) NOT NULL,
    plefechainicio date NOT NULL,
    plefechafin date NOT NULL,
    pleactivo boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_periodo_lectivo PRIMARY KEY (pleid)
);

CREATE TABLE paralelo (
    prlid integer GENERATED BY DEFAULT AS IDENTITY,
    prlnombre varchar(10) NOT NULL,
    CONSTRAINT pk_paralelo PRIMARY KEY (prlid),
    CONSTRAINT uq_paralelo_prlnombre UNIQUE (prlnombre)
);

CREATE TABLE nivel_educativo (
    nedid integer GENERATED BY DEFAULT AS IDENTITY,
    nednombre varchar(50) NOT NULL,
    CONSTRAINT pk_nivel_educativo PRIMARY KEY (nedid),
    CONSTRAINT uq_nivel_educativo_nednombre UNIQUE (nednombre)
);

CREATE TABLE parentesco (
    pteid integer GENERATED BY DEFAULT AS IDENTITY,
    ptenombre varchar(50) NOT NULL,
    CONSTRAINT pk_parentesco PRIMARY KEY (pteid),
    CONSTRAINT uq_parentesco_ptenombre UNIQUE (ptenombre)
);

CREATE TABLE estado_civil (
    eciid integer GENERATED BY DEFAULT AS IDENTITY,
    ecinombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_civil PRIMARY KEY (eciid),
    CONSTRAINT uq_estado_civil_ecinombre UNIQUE (ecinombre)
);

CREATE TABLE instruccion (
    istid integer GENERATED BY DEFAULT AS IDENTITY,
    istnombre varchar(50) NOT NULL,
    CONSTRAINT pk_instruccion PRIMARY KEY (istid),
    CONSTRAINT uq_instruccion_istnombre UNIQUE (istnombre)
);

CREATE TABLE grado (
    graid integer GENERATED BY DEFAULT AS IDENTITY,
    nedid integer NOT NULL,
    granombre varchar(50) NOT NULL,
    CONSTRAINT pk_grado PRIMARY KEY (graid),
    CONSTRAINT fk_grado_nivel_educativo FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT uq_grado_nedid_granombre UNIQUE (nedid, granombre)
);

CREATE TABLE estado_matricula (
    emdid integer GENERATED BY DEFAULT AS IDENTITY,
    emdnombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_matricula PRIMARY KEY (emdid),
    CONSTRAINT uq_estado_matricula_emdnombre UNIQUE (emdnombre)
);

CREATE TABLE documento_matricula (
    domid integer GENERATED BY DEFAULT AS IDENTITY,
    domnombre varchar(150) NOT NULL,
    domdescripcion varchar(250),
    domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO',
    domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO',
    domurl varchar(255),
    domplantilla_archivo varchar(255),
    domplantilla_extension varchar(10),
    domobligatorio boolean NOT NULL DEFAULT true,
    domactivo boolean NOT NULL DEFAULT true,
    domfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domfecha_modificacion timestamp,
    CONSTRAINT pk_documento_matricula PRIMARY KEY (domid),
    CONSTRAINT uq_documento_matricula_domnombre UNIQUE (domnombre),
    CONSTRAINT ck_documento_matricula_domtipo
        CHECK (domtipo IN ('ESTATICO', 'PLANTILLA')),
    CONSTRAINT ck_documento_matricula_domorigen
        CHECK (domorigen IN ('ARCHIVO', 'URL')),
    CONSTRAINT ck_documento_matricula_domplantilla_extension
        CHECK (
            domplantilla_extension IS NULL
            OR domplantilla_extension IN ('DOCX')
        ),
    CONSTRAINT ck_documento_matricula_contenido
        CHECK (
            (
                domtipo = 'ESTATICO'
                AND (
                    (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
                    OR
                    (domorigen = 'URL' AND domurl IS NOT NULL)
                )
                AND domplantilla_archivo IS NULL
            )
            OR
            (
                domtipo = 'PLANTILLA'
                AND domorigen = 'ARCHIVO'
                AND domplantilla_archivo IS NOT NULL
                AND domplantilla_extension = 'DOCX'
            )
        )
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE documento_matricula
-- ADD COLUMN domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO';
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO';
--
-- ALTER TABLE documento_matricula
-- ALTER COLUMN domurl DROP NOT NULL;
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domplantilla_archivo varchar(255);
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domplantilla_extension varchar(10);
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domtipo
-- CHECK (domtipo IN ('ESTATICO', 'PLANTILLA'));
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domorigen
-- CHECK (domorigen IN ('ARCHIVO', 'URL'));
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domplantilla_extension
-- CHECK (
--     domplantilla_extension IS NULL
--     OR domplantilla_extension IN ('DOCX')
-- );
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_contenido
-- CHECK (
--     (
--         domtipo = 'ESTATICO'
--         AND (
--             (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
--             OR
--             (domorigen = 'URL' AND domurl IS NOT NULL)
--         )
--         AND domplantilla_archivo IS NULL
--     )
--     OR
--     (
--         domtipo = 'PLANTILLA'
--         AND domorigen = 'ARCHIVO'
--         AND domplantilla_archivo IS NOT NULL
--         AND domplantilla_extension = 'DOCX'
--     )
-- );

CREATE TABLE curso (
    curid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    graid integer NOT NULL,
    prlid integer NOT NULL,
    curestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_curso PRIMARY KEY (curid),
    CONSTRAINT fk_curso_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_curso_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_curso_paralelo FOREIGN KEY (prlid)
        REFERENCES paralelo (prlid),
    CONSTRAINT uq_curso_pleid_graid_prlid UNIQUE (pleid, graid, prlid)
);

CREATE TABLE persona (
    perid integer GENERATED BY DEFAULT AS IDENTITY,
    percedula varchar(10) NOT NULL,
    pernombres varchar(100) NOT NULL,
    perapellidos varchar(100) NOT NULL,
    pertelefono1 varchar(20),
    pertelefono2 varchar(20),
    percorreo varchar(150),
    persexo varchar(20),
    CONSTRAINT pk_persona PRIMARY KEY (perid),
    CONSTRAINT uq_persona_percedula UNIQUE (percedula)
);

CREATE TABLE estudiante (
    estid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    estlugarnacimiento varchar(150),
    estdireccion varchar(250),
    estparroquia varchar(100),
    estestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_estudiante PRIMARY KEY (estid),
    CONSTRAINT fk_estudiante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_estudiante_perid UNIQUE (perid)
);

CREATE TABLE tipo_matricula (
    tmaid integer GENERATED BY DEFAULT AS IDENTITY,
    tmanombre varchar(50) NOT NULL,
    tmadescripcion varchar(150),
    tmaestado boolean NOT NULL DEFAULT true,
    tmafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tmafecha_modificacion timestamp,
    CONSTRAINT pk_tipo_matricula PRIMARY KEY (tmaid),
    CONSTRAINT uq_tipo_matricula_tmanombre UNIQUE (tmanombre)
);

CREATE TABLE configuracion_matricula (
    cmid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    cmhabilitada boolean NOT NULL DEFAULT false,
    cmfechainicio date,
    cmfechafin date,
    cmhabilitadaextraordinaria boolean NOT NULL DEFAULT false,
    cmfechainicioextraordinaria date,
    cmfechafinextraordinaria date,
    cmobservacion varchar(250),
    cmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmfecha_modificacion timestamp,
    CONSTRAINT pk_configuracion_matricula PRIMARY KEY (cmid),
    CONSTRAINT fk_configuracion_matricula_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT uq_configuracion_matricula_pleid UNIQUE (pleid),
    CONSTRAINT ck_configuracion_matricula_fechas_ordinarias
        CHECK (
            cmfechainicio IS NULL
            OR cmfechafin IS NULL
            OR cmfechainicio <= cmfechafin
        ),
    CONSTRAINT ck_configuracion_matricula_fechas_extraordinarias
        CHECK (
            cmfechainicioextraordinaria IS NULL
            OR cmfechafinextraordinaria IS NULL
            OR cmfechainicioextraordinaria <= cmfechafinextraordinaria
        )
);

CREATE TABLE matricula (
    matid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    curid integer NOT NULL,
    matfecha date NOT NULL,
    matfoto varchar(255),
    emdid integer NOT NULL,
    tmaid integer NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (matid),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_matricula_estado_matricula FOREIGN KEY (emdid)
        REFERENCES estado_matricula (emdid),
    CONSTRAINT fk_matricula_tipo_matricula FOREIGN KEY (tmaid)
        REFERENCES tipo_matricula (tmaid),
    CONSTRAINT uq_matricula_estid_curid UNIQUE (estid, curid)
);

CREATE TABLE matricula_representante (
    mreid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_matricula_representante PRIMARY KEY (mreid),
    CONSTRAINT fk_matricula_representante_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_representante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_matricula_representante_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_matricula_representante_matid UNIQUE (matid)
);

CREATE TABLE matricula_recurso_tecnologico (
    mrtid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mrtinternet boolean NOT NULL DEFAULT false,
    mrtcomputador boolean NOT NULL DEFAULT false,
    mrtlaptop boolean NOT NULL DEFAULT false,
    mrttablet boolean NOT NULL DEFAULT false,
    mrtcelular boolean NOT NULL DEFAULT false,
    mrtfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_recurso_tecnologico PRIMARY KEY (mrtid),
    CONSTRAINT fk_matricula_recurso_tecnologico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_recurso_tecnologico_matid UNIQUE (matid)
);

CREATE TABLE matricula_facturacion (
    mfcid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mfcnombre varchar(150) NOT NULL,
    mfctipoidentificacion varchar(10) NOT NULL,
    mfcidentificacion varchar(13) NOT NULL,
    mfcdireccion varchar(250),
    mfccorreo varchar(150),
    mfctelefono varchar(20),
    mfcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mfcfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_facturacion PRIMARY KEY (mfcid),
    CONSTRAINT fk_matricula_facturacion_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_facturacion_matid UNIQUE (matid),
    CONSTRAINT ck_matricula_facturacion_tipo_identificacion
        CHECK (mfctipoidentificacion IN ('CEDULA', 'RUC'))
);

CREATE TABLE matricula_documento_generado (
    mdgid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgnombre varchar(180) NOT NULL,
    mdgruta_archivo varchar(255) NOT NULL,
    mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
    mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdghash varchar(128),
    mdgobservacion varchar(250),
    CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
    CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT ck_matricula_documento_generado_extension
        CHECK (mdgextension IN ('DOCX', 'PDF'))
);

-- Para una base de datos ya existente, aplicar manualmente:
-- CREATE TABLE matricula_documento_generado (
--     mdgid integer GENERATED BY DEFAULT AS IDENTITY,
--     matid integer NOT NULL,
--     domid integer NOT NULL,
--     mdgnombre varchar(180) NOT NULL,
--     mdgruta_archivo varchar(255) NOT NULL,
--     mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
--     mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     mdghash varchar(128),
--     mdgobservacion varchar(250),
--     CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
--     CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
--         REFERENCES matricula (matid),
--     CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
--         REFERENCES documento_matricula (domid),
--     CONSTRAINT ck_matricula_documento_generado_extension
--         CHECK (mdgextension IN ('DOCX', 'PDF'))
-- );

CREATE TABLE matricula_aceptacion_documentos (
    madid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgid integer,
    madaceptado boolean NOT NULL DEFAULT false,
    madfecha_aceptacion timestamp,
    madobservacion varchar(250),
    CONSTRAINT pk_matricula_aceptacion_documentos PRIMARY KEY (madid),
    CONSTRAINT fk_matricula_aceptacion_documentos_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_aceptacion_documentos_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT fk_matricula_aceptacion_documentos_generado FOREIGN KEY (mdgid)
        REFERENCES matricula_documento_generado (mdgid),
    CONSTRAINT uq_matricula_aceptacion_documentos_matid_domid UNIQUE (matid, domid)
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE matricula_aceptacion_documentos
-- ADD COLUMN mdgid integer;
--
-- ALTER TABLE matricula_aceptacion_documentos
-- ADD CONSTRAINT fk_matricula_aceptacion_documentos_generado
-- FOREIGN KEY (mdgid)
-- REFERENCES matricula_documento_generado (mdgid);

CREATE TABLE familiar (
    famid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    eciid integer,
    istid integer,
    famprofesion varchar(100),
    famocupacion varchar(150),
    famlugardetrabajo varchar(150),
    famfechanacimiento date,
    CONSTRAINT pk_familiar PRIMARY KEY (famid),
    CONSTRAINT fk_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_familiar_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_familiar_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT fk_familiar_estado_civil FOREIGN KEY (eciid)
        REFERENCES estado_civil (eciid),
    CONSTRAINT fk_familiar_instruccion FOREIGN KEY (istid)
        REFERENCES instruccion (istid),
    CONSTRAINT uq_familiar_estid_perid_pteid UNIQUE (estid, perid, pteid)
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE familiar
-- ADD COLUMN famocupacion varchar(150);
