CREATE TABLE institucion (
    insid integer GENERATED BY DEFAULT AS IDENTITY,
    insnombre varchar(150) NOT NULL,
    insrazonsocial varchar(200),
    insruc varchar(13),
    inscodigoamie varchar(20),
    insdireccion varchar(250),
    instelefono varchar(20),
    inscorreoelectronico varchar(150),
    insrepresentantelegal varchar(150),
    CONSTRAINT pk_institucion PRIMARY KEY (insid),
    CONSTRAINT uq_institucion_insruc UNIQUE (insruc),
    CONSTRAINT uq_institucion_inscodigoamie UNIQUE (inscodigoamie)
);
CREATE TABLE periodo_lectivo (
    pleid integer GENERATED BY DEFAULT AS IDENTITY,
    pledescripcion varchar(20) NOT NULL,
    plefechainicio date NOT NULL,
    plefechafin date NOT NULL,
    pleactivo boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_periodo_lectivo PRIMARY KEY (pleid)
);
CREATE TABLE paralelo (
    prlid integer GENERATED BY DEFAULT AS IDENTITY,
    prlnombre varchar(10) NOT NULL,
    CONSTRAINT pk_paralelo PRIMARY KEY (prlid),
    CONSTRAINT uq_paralelo_prlnombre UNIQUE (prlnombre)
);
CREATE TABLE nivel_educativo (
    nedid integer GENERATED BY DEFAULT AS IDENTITY,
    nednombre varchar(50) NOT NULL,
    CONSTRAINT pk_nivel_educativo PRIMARY KEY (nedid),
    CONSTRAINT uq_nivel_educativo_nednombre UNIQUE (nednombre)
);
CREATE TABLE parentesco (
    pteid integer GENERATED BY DEFAULT AS IDENTITY,
    ptenombre varchar(50) NOT NULL,
    CONSTRAINT pk_parentesco PRIMARY KEY (pteid),
    CONSTRAINT uq_parentesco_ptenombre UNIQUE (ptenombre)
);
CREATE TABLE estado_civil (
    eciid integer GENERATED BY DEFAULT AS IDENTITY,
    ecinombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_civil PRIMARY KEY (eciid),
    CONSTRAINT uq_estado_civil_ecinombre UNIQUE (ecinombre)
);
CREATE TABLE instruccion (
    istid integer GENERATED BY DEFAULT AS IDENTITY,
    istnombre varchar(50) NOT NULL,
    CONSTRAINT pk_instruccion PRIMARY KEY (istid),
    CONSTRAINT uq_instruccion_istnombre UNIQUE (istnombre)
);
CREATE TABLE grado (
    graid integer GENERATED BY DEFAULT AS IDENTITY,
    nedid integer NOT NULL,
    granombre varchar(50) NOT NULL,
    CONSTRAINT pk_grado PRIMARY KEY (graid),
    CONSTRAINT fk_grado_nivel_educativo FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT uq_grado_nedid_granombre UNIQUE (nedid, granombre)
);
CREATE TABLE estado_matricula (
    emdid integer GENERATED BY DEFAULT AS IDENTITY,
    emdnombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_matricula PRIMARY KEY (emdid),
    CONSTRAINT uq_estado_matricula_emdnombre UNIQUE (emdnombre)
);
CREATE TABLE documento_matricula (
    domid integer GENERATED BY DEFAULT AS IDENTITY,
    domnombre varchar(150) NOT NULL,
    domdescripcion varchar(250),
    domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO',
    domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO',
    domurl varchar(255),
    domplantilla_archivo varchar(255),
    domplantilla_extension varchar(10),
    domobligatorio boolean NOT NULL DEFAULT true,
    domactivo boolean NOT NULL DEFAULT true,
    domfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    domfecha_modificacion timestamp,
    CONSTRAINT pk_documento_matricula PRIMARY KEY (domid),
    CONSTRAINT uq_documento_matricula_domnombre UNIQUE (domnombre),
    CONSTRAINT ck_documento_matricula_domtipo
        CHECK (domtipo IN ('ESTATICO', 'PLANTILLA')),
    CONSTRAINT ck_documento_matricula_domorigen
        CHECK (domorigen IN ('ARCHIVO', 'URL')),
    CONSTRAINT ck_documento_matricula_domplantilla_extension
        CHECK (
            domplantilla_extension IS NULL
            OR domplantilla_extension IN ('DOCX')
        ),
    CONSTRAINT ck_documento_matricula_contenido
        CHECK (
            (
                domtipo = 'ESTATICO'
                AND (
                    (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
                    OR
                    (domorigen = 'URL' AND domurl IS NOT NULL)
                )
                AND domplantilla_archivo IS NULL
            )
            OR
            (
                domtipo = 'PLANTILLA'
                AND domorigen = 'ARCHIVO'
                AND domplantilla_archivo IS NOT NULL
                AND domplantilla_extension = 'DOCX'
            )
        )
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE documento_matricula
-- ADD COLUMN domtipo varchar(20) NOT NULL DEFAULT 'ESTATICO';
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domorigen varchar(20) NOT NULL DEFAULT 'ARCHIVO';
--
-- ALTER TABLE documento_matricula
-- ALTER COLUMN domurl DROP NOT NULL;
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domplantilla_archivo varchar(255);
--
-- ALTER TABLE documento_matricula
-- ADD COLUMN domplantilla_extension varchar(10);
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domtipo
-- CHECK (domtipo IN ('ESTATICO', 'PLANTILLA'));
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domorigen
-- CHECK (domorigen IN ('ARCHIVO', 'URL'));
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_domplantilla_extension
-- CHECK (
--     domplantilla_extension IS NULL
--     OR domplantilla_extension IN ('DOCX')
-- );
--
-- ALTER TABLE documento_matricula
-- ADD CONSTRAINT ck_documento_matricula_contenido
-- CHECK (
--     (
--         domtipo = 'ESTATICO'
--         AND (
--             (domorigen = 'ARCHIVO' AND domurl IS NOT NULL)
--             OR
--             (domorigen = 'URL' AND domurl IS NOT NULL)
--         )
--         AND domplantilla_archivo IS NULL
--     )
--     OR
--     (
--         domtipo = 'PLANTILLA'
--         AND domorigen = 'ARCHIVO'
--         AND domplantilla_archivo IS NOT NULL
--         AND domplantilla_extension = 'DOCX'
--     )
-- );
CREATE TABLE tipo_personal (
    tpid integer GENERATED BY DEFAULT AS IDENTITY,
    tpnombre varchar(50) NOT NULL,
    tpdescripcion varchar(150),
    tpestado boolean NOT NULL DEFAULT true,
    tpfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tpfecha_modificacion timestamp,
    CONSTRAINT pk_tipo_personal PRIMARY KEY (tpid),
    CONSTRAINT uq_tipo_personal_tpnombre UNIQUE (tpnombre)
);
CREATE TABLE curso (
    curid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    graid integer NOT NULL,
    prlid integer NOT NULL,
    curestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_curso PRIMARY KEY (curid),
    CONSTRAINT fk_curso_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_curso_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_curso_paralelo FOREIGN KEY (prlid)
        REFERENCES paralelo (prlid),
    CONSTRAINT uq_curso_pleid_graid_prlid UNIQUE (pleid, graid, prlid)
);
CREATE TABLE persona (
    perid integer GENERATED BY DEFAULT AS IDENTITY,
    percedula varchar(10) NOT NULL,
    pernombres varchar(100) NOT NULL,
    perapellidos varchar(100) NOT NULL,
    pertelefono1 varchar(20),
    pertelefono2 varchar(20),
    percorreo varchar(150),
    persexo varchar(20),
    CONSTRAINT pk_persona PRIMARY KEY (perid),
    CONSTRAINT uq_persona_percedula UNIQUE (percedula)
);
CREATE TABLE personal (
    psnid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    psnfechacontratacion date NOT NULL,
    psnfechasalida date,
    psnestado boolean NOT NULL DEFAULT true,
    psnobservacion varchar(250),
    psnfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    psnfecha_modificacion timestamp,
    CONSTRAINT pk_personal PRIMARY KEY (psnid),
    CONSTRAINT fk_personal_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_personal_perid UNIQUE (perid)
);
CREATE TABLE asignacion_tipo_personal (
    atpid integer GENERATED BY DEFAULT AS IDENTITY,
    psnid integer NOT NULL,
    tpid integer NOT NULL,
    atpestado boolean NOT NULL DEFAULT true,
    atpfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    atpfecha_modificacion timestamp,
    CONSTRAINT pk_asignacion_tipo_personal PRIMARY KEY (atpid),
    CONSTRAINT fk_asignacion_tipo_personal_personal FOREIGN KEY (psnid)
        REFERENCES personal (psnid),
    CONSTRAINT fk_asignacion_tipo_personal_tipo_personal FOREIGN KEY (tpid)
        REFERENCES tipo_personal (tpid),
    CONSTRAINT uq_asignacion_tipo_personal_psnid_tpid UNIQUE (psnid, tpid)
);
CREATE TABLE usuario (
    usuid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    usunombre varchar(50) NOT NULL,
    usuclave varchar(255) NOT NULL,
    usuestado boolean NOT NULL DEFAULT false,
    usufecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    usufecha_modificacion timestamp,
    CONSTRAINT pk_usuario PRIMARY KEY (usuid),
    CONSTRAINT fk_usuario_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_usuario_perid UNIQUE (perid),
    CONSTRAINT uq_usuario_usunombre UNIQUE (usunombre)
);
CREATE TABLE rol (
    rolid integer GENERATED BY DEFAULT AS IDENTITY,
    rolnombre varchar(50) NOT NULL,
    roldescripcion varchar(200),
    rolestado boolean NOT NULL DEFAULT true,
    rolfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    rolfecha_modificacion timestamp,
    CONSTRAINT pk_rol PRIMARY KEY (rolid),
    CONSTRAINT uq_rol_rolnombre UNIQUE (rolnombre)
);
CREATE TABLE usuario_rol (
    usrid integer GENERATED BY DEFAULT AS IDENTITY,
    usuid integer NOT NULL,
    rolid integer NOT NULL,
    usrestado boolean NOT NULL DEFAULT true,
    usrfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    usrfecha_modificacion timestamp,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usrid),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuid)
        REFERENCES usuario (usuid),
    CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (rolid)
        REFERENCES rol (rolid),
    CONSTRAINT uq_usuario_rol_usuid_rolid UNIQUE (usuid, rolid)
);
CREATE TABLE permiso (
    prmid integer GENERATED BY DEFAULT AS IDENTITY,
    prmnombre varchar(100) NOT NULL,
    prmcodigo varchar(100) NOT NULL,
    prmdescripcion varchar(200),
    prmestado boolean NOT NULL DEFAULT true,
    prmfecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    prmfecha_modificacion timestamp,
    CONSTRAINT pk_permiso PRIMARY KEY (prmid),
    CONSTRAINT uq_permiso_prmnombre UNIQUE (prmnombre),
    CONSTRAINT uq_permiso_prmcodigo UNIQUE (prmcodigo)
);
CREATE TABLE rol_permiso (
    rpeid integer GENERATED BY DEFAULT AS IDENTITY,
    rolid integer NOT NULL,
    prmid integer NOT NULL,
    rpeestado boolean NOT NULL DEFAULT true,
    rpefecha_creacion timestamp NOT NULL DEFAULT current_timestamp,
    rpefecha_modificacion timestamp,
    CONSTRAINT pk_rol_permiso PRIMARY KEY (rpeid),
    CONSTRAINT fk_rol_permiso_rol FOREIGN KEY (rolid)
        REFERENCES rol (rolid),
    CONSTRAINT fk_rol_permiso_permiso FOREIGN KEY (prmid)
        REFERENCES permiso (prmid),
    CONSTRAINT uq_rol_permiso_rolid_prmid UNIQUE (rolid, prmid)
);
CREATE TABLE estudiante (
    estid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    estlugarnacimiento varchar(150),
    estdireccion varchar(250),
    estparroquia varchar(100),
    estestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_estudiante PRIMARY KEY (estid),
    CONSTRAINT fk_estudiante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_estudiante_perid UNIQUE (perid)
);
CREATE TABLE tipo_matricula (
    tmaid integer GENERATED BY DEFAULT AS IDENTITY,
    tmanombre varchar(50) NOT NULL,
    tmadescripcion varchar(150),
    tmaestado boolean NOT NULL DEFAULT true,
    tmafecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tmafecha_modificacion timestamp,
    CONSTRAINT pk_tipo_matricula PRIMARY KEY (tmaid),
    CONSTRAINT uq_tipo_matricula_tmanombre UNIQUE (tmanombre)
);
CREATE TABLE configuracion_matricula (
    cmid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    cmhabilitada boolean NOT NULL DEFAULT false,
    cmfechainicio date,
    cmfechafin date,
    cmhabilitadaextraordinaria boolean NOT NULL DEFAULT false,
    cmfechainicioextraordinaria date,
    cmfechafinextraordinaria date,
    cmobservacion varchar(250),
    cmfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cmfecha_modificacion timestamp,
    CONSTRAINT pk_configuracion_matricula PRIMARY KEY (cmid),
    CONSTRAINT fk_configuracion_matricula_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT uq_configuracion_matricula_pleid UNIQUE (pleid),
    CONSTRAINT ck_configuracion_matricula_fechas_ordinarias
        CHECK (
            cmfechainicio IS NULL
            OR cmfechafin IS NULL
            OR cmfechainicio <= cmfechafin
        ),
    CONSTRAINT ck_configuracion_matricula_fechas_extraordinarias
        CHECK (
            cmfechainicioextraordinaria IS NULL
            OR cmfechafinextraordinaria IS NULL
            OR cmfechainicioextraordinaria <= cmfechafinextraordinaria
        )
);
CREATE TABLE matricula (
    matid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    curid integer NOT NULL,
    matfecha date NOT NULL,
    matfoto varchar(255),
    emdid integer NOT NULL,
    tmaid integer NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (matid),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_matricula_estado_matricula FOREIGN KEY (emdid)
        REFERENCES estado_matricula (emdid),
    CONSTRAINT fk_matricula_tipo_matricula FOREIGN KEY (tmaid)
        REFERENCES tipo_matricula (tmaid),
    CONSTRAINT uq_matricula_estid_curid UNIQUE (estid, curid)
);
CREATE TABLE matricula_representante (
    mreid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_matricula_representante PRIMARY KEY (mreid),
    CONSTRAINT fk_matricula_representante_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_representante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_matricula_representante_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_matricula_representante_matid UNIQUE (matid)
);

CREATE TABLE matricula_recurso_tecnologico (
    mrtid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mrtinternet boolean NOT NULL DEFAULT false,
    mrtcomputador boolean NOT NULL DEFAULT false,
    mrtlaptop boolean NOT NULL DEFAULT false,
    mrttablet boolean NOT NULL DEFAULT false,
    mrtcelular boolean NOT NULL DEFAULT false,
    mrtfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mrtfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_recurso_tecnologico PRIMARY KEY (mrtid),
    CONSTRAINT fk_matricula_recurso_tecnologico_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_recurso_tecnologico_matid UNIQUE (matid)
);

CREATE TABLE matricula_facturacion (
    mfcid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    mfcnombre varchar(150) NOT NULL,
    mfctipoidentificacion varchar(10) NOT NULL,
    mfcidentificacion varchar(13) NOT NULL,
    mfcdireccion varchar(250),
    mfccorreo varchar(150),
    mfctelefono varchar(20),
    mfcfecha_creacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mfcfecha_modificacion timestamp,
    CONSTRAINT pk_matricula_facturacion PRIMARY KEY (mfcid),
    CONSTRAINT fk_matricula_facturacion_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT uq_matricula_facturacion_matid UNIQUE (matid),
    CONSTRAINT ck_matricula_facturacion_tipo_identificacion
        CHECK (mfctipoidentificacion IN ('CEDULA', 'RUC'))
);
CREATE TABLE matricula_documento_generado (
    mdgid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgnombre varchar(180) NOT NULL,
    mdgruta_archivo varchar(255) NOT NULL,
    mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
    mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdghash varchar(128),
    mdgobservacion varchar(250),
    CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
    CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT ck_matricula_documento_generado_extension
        CHECK (mdgextension IN ('DOCX', 'PDF'))
);
-- Para una base de datos ya existente, aplicar manualmente:
-- CREATE TABLE matricula_documento_generado (
--     mdgid integer GENERATED BY DEFAULT AS IDENTITY,
--     matid integer NOT NULL,
--     domid integer NOT NULL,
--     mdgnombre varchar(180) NOT NULL,
--     mdgruta_archivo varchar(255) NOT NULL,
--     mdgextension varchar(10) NOT NULL DEFAULT 'PDF',
--     mdgfecha_generacion timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     mdghash varchar(128),
--     mdgobservacion varchar(250),
--     CONSTRAINT pk_matricula_documento_generado PRIMARY KEY (mdgid),
--     CONSTRAINT fk_matricula_documento_generado_matricula FOREIGN KEY (matid)
--         REFERENCES matricula (matid),
--     CONSTRAINT fk_matricula_documento_generado_documento FOREIGN KEY (domid)
--         REFERENCES documento_matricula (domid),
--     CONSTRAINT ck_matricula_documento_generado_extension
--         CHECK (mdgextension IN ('DOCX', 'PDF'))
-- );
CREATE TABLE matricula_aceptacion_documentos (
    madid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    domid integer NOT NULL,
    mdgid integer,
    madaceptado boolean NOT NULL DEFAULT false,
    madfecha_aceptacion timestamp,
    madobservacion varchar(250),
    CONSTRAINT pk_matricula_aceptacion_documentos PRIMARY KEY (madid),
    CONSTRAINT fk_matricula_aceptacion_documentos_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_aceptacion_documentos_documento FOREIGN KEY (domid)
        REFERENCES documento_matricula (domid),
    CONSTRAINT fk_matricula_aceptacion_documentos_generado FOREIGN KEY (mdgid)
        REFERENCES matricula_documento_generado (mdgid),
    CONSTRAINT uq_matricula_aceptacion_documentos_matid_domid UNIQUE (matid, domid)
);
-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE matricula_aceptacion_documentos
-- ADD COLUMN mdgid integer;
--
-- ALTER TABLE matricula_aceptacion_documentos
-- ADD CONSTRAINT fk_matricula_aceptacion_documentos_generado
-- FOREIGN KEY (mdgid)
-- REFERENCES matricula_documento_generado (mdgid);

CREATE TABLE familiar (
    famid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    eciid integer,
    istid integer,
    famprofesion varchar(100),
    famocupacion varchar(150),
    famlugardetrabajo varchar(150),
    famfechanacimiento date,
    CONSTRAINT pk_familiar PRIMARY KEY (famid),
    CONSTRAINT fk_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_familiar_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_familiar_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT fk_familiar_estado_civil FOREIGN KEY (eciid)
        REFERENCES estado_civil (eciid),
    CONSTRAINT fk_familiar_instruccion FOREIGN KEY (istid)
        REFERENCES instruccion (istid),
    CONSTRAINT uq_familiar_estid_perid_pteid UNIQUE (estid, perid, pteid)
);

-- Para una base de datos ya existente, aplicar manualmente:
-- ALTER TABLE familiar
-- ADD COLUMN famocupacion varchar(150);

-- Datos base para catalogos y periodos del sistema
INSERT INTO periodo_lectivo (pledescripcion, plefechainicio, plefechafin, pleactivo)
SELECT '2027-2028', '2027-09-02', '2028-06-30', false
WHERE NOT EXISTS (
    SELECT 1 FROM periodo_lectivo WHERE pledescripcion = '2027-2028'
);

INSERT INTO periodo_lectivo (pledescripcion, plefechainicio, plefechafin, pleactivo)
SELECT '2026 2027', '2026-09-02', '2027-06-16', false
WHERE NOT EXISTS (
    SELECT 1 FROM periodo_lectivo WHERE pledescripcion = '2026 2027'
);

INSERT INTO periodo_lectivo (pledescripcion, plefechainicio, plefechafin, pleactivo)
SELECT '2025 2026', '2025-09-01', '2026-06-30', true
WHERE NOT EXISTS (
    SELECT 1 FROM periodo_lectivo WHERE pledescripcion = '2025 2026'
);

INSERT INTO paralelo (prlnombre) VALUES
('A'),
('B')
ON CONFLICT (prlnombre) DO NOTHING;

INSERT INTO nivel_educativo (nednombre) VALUES
('Educacion Inicial'),
('Educacion General Basica Elemental'),
('Educacion General Basica Media'),
('Educacion General Basica Superior'),
('Bachillerato General Unificado')
ON CONFLICT (nednombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, 'Inicial 1'
FROM nivel_educativo
WHERE nednombre = 'Educacion Inicial'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, 'Inicial 2'
FROM nivel_educativo
WHERE nednombre = 'Educacion Inicial'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, 'Preparatoria'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Elemental'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '2do Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Elemental'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '3er Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Elemental'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '4to Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Elemental'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '5to Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Media'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '6to Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Media'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '7mo Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Media'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '8vo Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Superior'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '9no Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Superior'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '10mo Año'
FROM nivel_educativo
WHERE nednombre = 'Educacion General Basica Superior'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '1ro BGU'
FROM nivel_educativo
WHERE nednombre = 'Bachillerato General Unificado'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '2do BGU'
FROM nivel_educativo
WHERE nednombre = 'Bachillerato General Unificado'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO grado (nedid, granombre)
SELECT nedid, '3ro BGU'
FROM nivel_educativo
WHERE nednombre = 'Bachillerato General Unificado'
ON CONFLICT (nedid, granombre) DO NOTHING;

INSERT INTO parentesco (ptenombre) VALUES
('Padre'),
('Madre'),
('Hermano'),
('Hermana'),
('Abuelo/Abuela'),
('Tio/Tia'),
('Tutor'),
('Apoderado'),
('Responsable'),
('Otro')
ON CONFLICT (ptenombre) DO NOTHING;

INSERT INTO estado_civil (ecinombre) VALUES
('Soltero'),
('Casado'),
('Divorciado'),
('Viudo'),
('Union de hecho')
ON CONFLICT (ecinombre) DO NOTHING;

INSERT INTO instruccion (istnombre) VALUES
('Sin instruccion'),
('Primaria'),
('Bachiller'),
('Tercer Nivel'),
('Cuarto Nivel'),
('Doctorado')
ON CONFLICT (istnombre) DO NOTHING;

INSERT INTO estado_matricula (emdnombre) VALUES
('Inactivo'),
('Activo'),
('Anulado')
ON CONFLICT (emdnombre) DO NOTHING;

INSERT INTO tipo_personal (tpnombre, tpdescripcion, tpestado) VALUES
('Docente', 'Personal academico responsable de la ensenanza', true),
('Administrativo', 'Personal de apoyo administrativo institucional', true),
('Directivo', 'Autoridades y responsables de direccion institucional', true),
('DECE', 'Personal del departamento de consejeria estudiantil', true),
('Inspeccion', 'Personal responsable de control y convivencia', true),
('Servicios', 'Personal operativo y de apoyo general', true)
ON CONFLICT (tpnombre) DO NOTHING;

INSERT INTO tipo_matricula (tmanombre, tmadescripcion, tmaestado) VALUES
('ORDINARIA', 'Matricula realizada dentro del proceso regular', true),
('EXTRAORDINARIA', 'Matricula realizada fuera del calendario ordinario', true)
ON CONFLICT (tmanombre) DO NOTHING;

-- Cursos base por periodo lectivo
INSERT INTO curso (pleid, graid, prlid, curestado)
SELECT
    p.pleid,
    g.graid,
    pr.prlid,
    true
FROM periodo_lectivo p
CROSS JOIN grado g
CROSS JOIN LATERAL (
    SELECT prlid
    FROM paralelo
    ORDER BY
        CASE WHEN UPPER(prlnombre) = 'A' THEN 0 ELSE 1 END,
        prlnombre ASC,
        prlid ASC
    LIMIT 1
) pr
WHERE NOT EXISTS (
    SELECT 1
    FROM curso c
    WHERE c.pleid = p.pleid
      AND c.graid = g.graid
      AND c.prlid = pr.prlid
);

-- Usuario administrador inicial
-- Ejecutar despues de los datos base de periodos y catalogos.

-- Persona administradora
INSERT INTO persona (
    percedula,
    pernombres,
    perapellidos,
    pertelefono1,
    percorreo,
    persexo
)
SELECT
    '1234567890',
    'Administrador',
    'General',
    '0999999999',
    'admin@albanyschool.edu.ec',
    'Masculino'
WHERE NOT EXISTS (
    SELECT 1
    FROM persona
    WHERE percedula = '1234567890'
);

-- Registro opcional como personal institucional
INSERT INTO personal (
    perid,
    psnfechacontratacion,
    psnestado,
    psnobservacion
)
SELECT
    p.perid,
    CURRENT_DATE,
    true,
    'Registro inicial del administrador del sistema'
FROM persona p
WHERE p.percedula = '1234567890'
  AND NOT EXISTS (
      SELECT 1
      FROM personal ps
      WHERE ps.perid = p.perid
  );

INSERT INTO asignacion_tipo_personal (
    psnid,
    tpid,
    atpestado
)
SELECT
    ps.psnid,
    tp.tpid,
    true
FROM personal ps
INNER JOIN persona p ON p.perid = ps.perid
INNER JOIN tipo_personal tp ON tp.tpnombre = 'Directivo'
WHERE p.percedula = '1234567890'
  AND NOT EXISTS (
      SELECT 1
      FROM asignacion_tipo_personal atp
      WHERE atp.psnid = ps.psnid
        AND atp.tpid = tp.tpid
  );

-- Rol administrador
INSERT INTO rol (
    rolnombre,
    roldescripcion,
    rolestado
)
SELECT
    'Administrador',
    'Acceso completo de administracion del sistema',
    true
WHERE NOT EXISTS (
    SELECT 1
    FROM rol
    WHERE rolnombre = 'Administrador'
);

-- Permisos base
INSERT INTO permiso (prmnombre, prmcodigo, prmdescripcion, prmestado)
SELECT *
FROM (
    VALUES
        ('Dashboard', 'dashboard.ver', 'Acceso al dashboard principal', true),
        ('Configuracion', 'configuracion.gestionar', 'Gestion de configuracion institucional y academica', true),
        ('Catalogos academicos', 'catalogos.gestionar', 'Administracion de catalogos academicos base', true),
        ('Personas', 'personas.gestionar', 'Registro y mantenimiento de personas', true),
        ('Estudiantes', 'estudiantes.gestionar', 'Registro y mantenimiento de estudiantes', true),
        ('Cursos', 'cursos.gestionar', 'Creacion y mantenimiento de cursos por periodo', true),
        ('Matriculas', 'matriculas.gestionar', 'Registro y gestion de matriculas', true),
        ('Documentos de matricula', 'matriculas.documentos', 'Administracion de documentos del proceso de matricula', true),
        ('Usuarios', 'seguridad.usuarios', 'Asignacion y control de usuarios', true),
        ('Roles y permisos', 'seguridad.roles_permisos', 'Gestion de roles y permisos de seguridad', true)
) AS source (prmnombre, prmcodigo, prmdescripcion, prmestado)
WHERE NOT EXISTS (
    SELECT 1
    FROM permiso p
    WHERE p.prmcodigo = source.prmcodigo
);

-- Usuario administrador
INSERT INTO usuario (
    perid,
    usunombre,
    usuclave,
    usuestado
)
SELECT
    p.perid,
    'admin',
    '$2y$10$aSwxP9tPDp27hYH3k6AR7uartIJLlv1mjQ6Hqv3UvsIeQWjzYcgxq',
    true
FROM persona p
WHERE p.percedula = '1234567890'
  AND NOT EXISTS (
      SELECT 1
      FROM usuario u
      WHERE u.usunombre = 'admin'
         OR u.perid = p.perid
  );

-- Asignacion del rol administrador al usuario
INSERT INTO usuario_rol (
    usuid,
    rolid,
    usrestado
)
SELECT
    u.usuid,
    r.rolid,
    true
FROM usuario u
INNER JOIN rol r ON r.rolnombre = 'Administrador'
WHERE u.usunombre = 'admin'
  AND NOT EXISTS (
      SELECT 1
      FROM usuario_rol ur
      WHERE ur.usuid = u.usuid
        AND ur.rolid = r.rolid
  );

-- Asignacion de todos los permisos base al rol administrador
INSERT INTO rol_permiso (
    rolid,
    prmid,
    rpeestado
)
SELECT
    r.rolid,
    p.prmid,
    true
FROM rol r
INNER JOIN permiso p ON p.prmcodigo IN (
    'dashboard.ver',
    'configuracion.gestionar',
    'catalogos.gestionar',
    'personas.gestionar',
    'estudiantes.gestionar',
    'cursos.gestionar',
    'matriculas.gestionar',
    'matriculas.documentos',
    'seguridad.usuarios',
    'seguridad.roles_permisos'
)
WHERE r.rolnombre = 'Administrador'
  AND NOT EXISTS (
      SELECT 1
      FROM rol_permiso rp
      WHERE rp.rolid = r.rolid
        AND rp.prmid = p.prmid
  );
