CREATE TABLE institucion (
    insid integer GENERATED BY DEFAULT AS IDENTITY,
    insnombre varchar(150) NOT NULL,
    insrazonsocial varchar(200),
    insruc varchar(13),
    inscodigoamie varchar(20),
    insdireccion varchar(250),
    instelefono varchar(20),
    inscorreoelectronico varchar(150),
    insrepresentantelegal varchar(150),
    CONSTRAINT pk_institucion PRIMARY KEY (insid),
    CONSTRAINT uq_institucion_insruc UNIQUE (insruc),
    CONSTRAINT uq_institucion_inscodigoamie UNIQUE (inscodigoamie)
);
CREATE TABLE periodo_lectivo (
    pleid integer GENERATED BY DEFAULT AS IDENTITY,
    pledescripcion varchar(20) NOT NULL,
    plefechainicio date NOT NULL,
    plefechafin date NOT NULL,
    pleactivo boolean NOT NULL DEFAULT false,
    CONSTRAINT pk_periodo_lectivo PRIMARY KEY (pleid)
);
CREATE TABLE paralelo (
    prlid integer GENERATED BY DEFAULT AS IDENTITY,
    prlnombre varchar(10) NOT NULL,
    CONSTRAINT pk_paralelo PRIMARY KEY (prlid),
    CONSTRAINT uq_paralelo_prlnombre UNIQUE (prlnombre)
);
CREATE TABLE nivel_educativo (
    nedid integer GENERATED BY DEFAULT AS IDENTITY,
    nednombre varchar(50) NOT NULL,
    CONSTRAINT pk_nivel_educativo PRIMARY KEY (nedid),
    CONSTRAINT uq_nivel_educativo_nednombre UNIQUE (nednombre)
);
CREATE TABLE parentesco (
    pteid integer GENERATED BY DEFAULT AS IDENTITY,
    ptenombre varchar(50) NOT NULL,
    CONSTRAINT pk_parentesco PRIMARY KEY (pteid),
    CONSTRAINT uq_parentesco_ptenombre UNIQUE (ptenombre)
);
CREATE TABLE estado_civil (
    eciid integer GENERATED BY DEFAULT AS IDENTITY,
    ecinombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_civil PRIMARY KEY (eciid),
    CONSTRAINT uq_estado_civil_ecinombre UNIQUE (ecinombre)
);
CREATE TABLE instruccion (
    istid integer GENERATED BY DEFAULT AS IDENTITY,
    istnombre varchar(50) NOT NULL,
    CONSTRAINT pk_instruccion PRIMARY KEY (istid),
    CONSTRAINT uq_instruccion_istnombre UNIQUE (istnombre)
);
CREATE TABLE grado (
    graid integer GENERATED BY DEFAULT AS IDENTITY,
    nedid integer NOT NULL,
    granombre varchar(50) NOT NULL,
    CONSTRAINT pk_grado PRIMARY KEY (graid),
    CONSTRAINT fk_grado_nivel_educativo FOREIGN KEY (nedid)
        REFERENCES nivel_educativo (nedid),
    CONSTRAINT uq_grado_nedid_granombre UNIQUE (nedid, granombre)
);
CREATE TABLE estado_matricula (
    emdid integer GENERATED BY DEFAULT AS IDENTITY,
    emdnombre varchar(50) NOT NULL,
    CONSTRAINT pk_estado_matricula PRIMARY KEY (emdid),
    CONSTRAINT uq_estado_matricula_emdnombre UNIQUE (emdnombre)
);
CREATE TABLE curso (
    curid integer GENERATED BY DEFAULT AS IDENTITY,
    pleid integer NOT NULL,
    graid integer NOT NULL,
    prlid integer NOT NULL,
    curestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_curso PRIMARY KEY (curid),
    CONSTRAINT fk_curso_periodo_lectivo FOREIGN KEY (pleid)
        REFERENCES periodo_lectivo (pleid),
    CONSTRAINT fk_curso_grado FOREIGN KEY (graid)
        REFERENCES grado (graid),
    CONSTRAINT fk_curso_paralelo FOREIGN KEY (prlid)
        REFERENCES paralelo (prlid),
    CONSTRAINT uq_curso_pleid_graid_prlid UNIQUE (pleid, graid, prlid)
);
CREATE TABLE persona (
    perid integer GENERATED BY DEFAULT AS IDENTITY,
    percedula varchar(10) NOT NULL,
    pernombres varchar(100) NOT NULL,
    perapellidos varchar(100) NOT NULL,
    pertelefono1 varchar(20),
    pertelefono2 varchar(20),
    percorreo varchar(150),
    persexo varchar(20),
    CONSTRAINT pk_persona PRIMARY KEY (perid),
    CONSTRAINT uq_persona_percedula UNIQUE (percedula)
);
CREATE TABLE estudiante (
    estid integer GENERATED BY DEFAULT AS IDENTITY,
    perid integer NOT NULL,
    estlugarnacimiento varchar(150),
    estdireccion varchar(250),
    estparroquia varchar(100),
    estestado boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_estudiante PRIMARY KEY (estid),
    CONSTRAINT fk_estudiante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT uq_estudiante_perid UNIQUE (perid)
);
CREATE TABLE matricula (
    matid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    curid integer NOT NULL,
    matfecha date NOT NULL,
    matfoto varchar(255),
    emdid integer NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (matid),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_matricula_curso FOREIGN KEY (curid)
        REFERENCES curso (curid),
    CONSTRAINT fk_matricula_estado_matricula FOREIGN KEY (emdid)
        REFERENCES estado_matricula (emdid),
    CONSTRAINT uq_matricula_estid_curid UNIQUE (estid, curid)
);
CREATE TABLE matricula_representante (
    mreid integer GENERATED BY DEFAULT AS IDENTITY,
    matid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    CONSTRAINT pk_matricula_representante PRIMARY KEY (mreid),
    CONSTRAINT fk_matricula_representante_matricula FOREIGN KEY (matid)
        REFERENCES matricula (matid),
    CONSTRAINT fk_matricula_representante_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_matricula_representante_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT uq_matricula_representante_matid UNIQUE (matid)
);
CREATE TABLE familiar (
    famid integer GENERATED BY DEFAULT AS IDENTITY,
    estid integer NOT NULL,
    perid integer NOT NULL,
    pteid integer NOT NULL,
    eciid integer,
    istid integer,
    famprofesion varchar(100),
    famlugardetrabajo varchar(150),
    famfechanacimiento date,
    CONSTRAINT pk_familiar PRIMARY KEY (famid),
    CONSTRAINT fk_familiar_estudiante FOREIGN KEY (estid)
        REFERENCES estudiante (estid),
    CONSTRAINT fk_familiar_persona FOREIGN KEY (perid)
        REFERENCES persona (perid),
    CONSTRAINT fk_familiar_parentesco FOREIGN KEY (pteid)
        REFERENCES parentesco (pteid),
    CONSTRAINT fk_familiar_estado_civil FOREIGN KEY (eciid)
        REFERENCES estado_civil (eciid),
    CONSTRAINT fk_familiar_instruccion FOREIGN KEY (istid)
        REFERENCES instruccion (istid),
    CONSTRAINT uq_familiar_estid_perid_pteid UNIQUE (estid, perid, pteid)
);