<?php

declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\AttendanceController;
use App\Controllers\ConfigurationController;
use App\Controllers\CourseController;
use App\Controllers\GradeController;
use App\Controllers\MatriculationController;
use App\Controllers\ModuleController;
use App\Controllers\PersonController;
use App\Controllers\PersonalController;
use App\Controllers\SecurityController;
use App\Controllers\StudentController;
use App\Core\Router;

return static function (Router $router): void {
    $router->get('/', [AuthController::class, 'index']);
    $router->get('/login', [AuthController::class, 'index']);
    $router->post('/login', [AuthController::class, 'authenticate']);
    $router->get('/dashboard', [AuthController::class, 'dashboard']);
    $router->get('/matricula-temporal', [MatriculationController::class, 'temporary']);
    $router->post('/matricula-temporal', [MatriculationController::class, 'storeTemporary']);
    $router->get('/matricula-temporal/persona', [MatriculationController::class, 'findPersonTemporary']);
    $router->get('/mi-matricula', [StudentController::class, 'myMatriculation']);
    $router->get('/mi-matricula/modulo', [StudentController::class, 'myMatriculationModule']);
    $router->get('/representante/estudiante', [StudentController::class, 'representativeStudent']);
    $router->get('/representante/estudiante/modulo', [StudentController::class, 'representativeStudentModule']);
    $router->get('/academico', [ModuleController::class, 'academic']);
    $router->get('/configuracion', [ModuleController::class, 'configuration']);
    $router->get('/reportes', [ModuleController::class, 'reports']);
    $router->get('/reportes/asistencia', [AttendanceController::class, 'reports']);
    $router->get('/seguridad', [ModuleController::class, 'security']);
    $router->post('/logout', [AuthController::class, 'logout']);

    $router->get('/configuracion/catalogos', [ConfigurationController::class, 'catalogs']);
    $router->get('/configuracion/institucion', [ConfigurationController::class, 'institution']);
    $router->get('/configuracion/periodos', [ConfigurationController::class, 'periods']);
    $router->get('/configuracion/matricula', [ConfigurationController::class, 'matriculationSettings']);
    $router->get('/configuracion/matricula/documentos', [ConfigurationController::class, 'matriculationDocuments']);
    $router->post('/configuracion/catalogos', [ConfigurationController::class, 'storeCatalogItem']);
    $router->post('/configuracion/institucion', [ConfigurationController::class, 'storeInstitution']);
    $router->post('/configuracion/catalogos/actualizar', [ConfigurationController::class, 'updateCatalogItem']);
    $router->post('/configuracion/catalogos/eliminar', [ConfigurationController::class, 'deleteCatalogItem']);
    $router->post('/configuracion/periodos', [ConfigurationController::class, 'storePeriod']);
    $router->post('/configuracion/periodos/actualizar', [ConfigurationController::class, 'updatePeriod']);
    $router->post('/configuracion/periodo-actual', [ConfigurationController::class, 'selectCurrentPeriod']);
    $router->post('/configuracion/periodo-visualizado', [ConfigurationController::class, 'selectViewedPeriod']);
    $router->post('/configuracion/matricula', [ConfigurationController::class, 'storeMatriculationSetting']);
    $router->post('/configuracion/matricula/actualizar', [ConfigurationController::class, 'updateMatriculationSetting']);
    $router->post('/configuracion/matricula/ordinaria', [ConfigurationController::class, 'toggleOrdinaryMatriculationSetting']);
    $router->post('/configuracion/matricula/extraordinaria', [ConfigurationController::class, 'toggleExtraordinaryMatriculationSetting']);
    $router->post('/configuracion/matricula/documentos', [ConfigurationController::class, 'storeMatriculationDocument']);
    $router->post('/configuracion/matricula/documentos/actualizar', [ConfigurationController::class, 'updateMatriculationDocument']);
    $router->post('/configuracion/matricula/documentos/eliminar', [ConfigurationController::class, 'deleteMatriculationDocument']);

    $router->get('/seguridad/catalogos', [SecurityController::class, 'catalogs']);
    $router->get('/seguridad/usuarios', [SecurityController::class, 'users']);
    $router->get('/seguridad/usuarios-temporales', [SecurityController::class, 'temporaryUsers']);
    $router->get('/seguridad/usuarios/buscar', [SecurityController::class, 'searchUsers']);
    $router->get('/seguridad/personas-disponibles/buscar', [SecurityController::class, 'searchAvailablePersons']);
    $router->get('/seguridad/representantes/matricula-nueva/buscar', [SecurityController::class, 'searchRepresentativeNewStudentAuthorizations']);
    $router->post('/seguridad/catalogos', [SecurityController::class, 'storeCatalogItem']);
    $router->post('/seguridad/catalogos/actualizar', [SecurityController::class, 'updateCatalogItem']);
    $router->post('/seguridad/catalogos/eliminar', [SecurityController::class, 'deleteCatalogItem']);
    $router->get('/seguridad/roles-permisos', [SecurityController::class, 'rolePermissions']);
    $router->get('/seguridad/usuarios-roles', [SecurityController::class, 'userRoles']);
    $router->get('/seguridad/usuarios-roles/buscar', [SecurityController::class, 'searchUserRoles']);
    $router->post('/seguridad/usuarios', [SecurityController::class, 'storeUser']);
    $router->post('/seguridad/usuarios-temporales', [SecurityController::class, 'storeTemporaryUser']);
    $router->post('/seguridad/usuarios-temporales/clave', [SecurityController::class, 'resetTemporaryUserPassword']);
    $router->post('/seguridad/usuarios-temporales/extender', [SecurityController::class, 'extendTemporaryUser']);
    $router->post('/seguridad/usuarios-temporales/eliminar', [SecurityController::class, 'deleteTemporaryUser']);
    $router->post('/seguridad/representantes/matricula-nueva', [SecurityController::class, 'enableRepresentativeNewStudent']);
    $router->post('/seguridad/representantes/matricula-nueva/anular', [SecurityController::class, 'annulRepresentativeNewStudent']);
    $router->post('/seguridad/usuarios/estado', [SecurityController::class, 'toggleUserStatus']);
    $router->post('/seguridad/usuarios/clave', [SecurityController::class, 'resetUserPassword']);
    $router->post('/seguridad/roles-permisos', [SecurityController::class, 'updateRolePermissions']);
    $router->post('/seguridad/usuarios-roles', [SecurityController::class, 'updateUserRoles']);

    $router->get('/personas', [PersonController::class, 'index']);
    $router->get('/personal', [PersonalController::class, 'index']);
    $router->get('/personal/registro', [PersonalController::class, 'create']);
    $router->get('/personal/asignacion', [PersonalController::class, 'assignment']);
    $router->get('/personal/asignacion/buscar', [PersonalController::class, 'searchStaffTypes']);
    $router->get('/personal/consulta', [PersonalController::class, 'listing']);
    $router->get('/personal/consulta/buscar', [PersonalController::class, 'searchListing']);
    $router->get('/personal/editar', [PersonalController::class, 'edit']);
    $router->get('/grados', [GradeController::class, 'index']);
    $router->get('/matriculas', [MatriculationController::class, 'index']);
    $router->get('/matriculas/editar', [MatriculationController::class, 'edit']);
    $router->get('/matriculas/persona', [MatriculationController::class, 'findPerson']);
    $router->get('/cursos', [CourseController::class, 'index']);
    $router->get('/grados/crear', [GradeController::class, 'create']);
    $router->get('/grados/editar', [GradeController::class, 'edit']);
    $router->get('/personas/crear', [PersonController::class, 'create']);
    $router->get('/personas/editar', [PersonController::class, 'edit']);
    $router->get('/grados/buscar', [GradeController::class, 'search']);
    $router->get('/personas/buscar', [PersonController::class, 'search']);
    $router->post('/personas', [PersonController::class, 'store']);
    $router->post('/personal/registro', [PersonalController::class, 'store']);
    $router->post('/personal/tipos', [PersonalController::class, 'updateStaffTypes']);
    $router->post('/personal/actualizar', [PersonalController::class, 'update']);
    $router->post('/grados', [GradeController::class, 'store']);
    $router->post('/matriculas', [MatriculationController::class, 'store']);
    $router->post('/matriculas/actualizar', [MatriculationController::class, 'update']);
    $router->post('/matriculas/estado', [MatriculationController::class, 'toggleStatus']);
    $router->post('/matriculas/sincronizar-accesos', [MatriculationController::class, 'syncAccesses']);
    $router->post('/matriculas/sincronizar-accesos/matricula', [MatriculationController::class, 'syncMatriculationAccesses']);
    $router->post('/cursos', [CourseController::class, 'store']);
    $router->post('/cursos/estado', [CourseController::class, 'toggleStatus']);
    $router->post('/grados/actualizar', [GradeController::class, 'update']);
    $router->post('/grados/eliminar', [GradeController::class, 'destroy']);
    $router->post('/personas/actualizar', [PersonController::class, 'update']);
    $router->post('/personas/eliminar', [PersonController::class, 'destroy']);

    $router->get('/asistencia/configuracion', [AttendanceController::class, 'configuration']);
    $router->get('/asistencia/registro', [AttendanceController::class, 'register']);
    $router->get('/asistencia/calendario', [AttendanceController::class, 'calendar']);
    $router->get('/asistencia/justificaciones', [AttendanceController::class, 'justifications']);
    $router->get('/asistencia/supervision', [AttendanceController::class, 'supervision']);
    $router->get('/asistencia/mi-asistencia', [AttendanceController::class, 'ownAttendance']);
    $router->get('/asistencia/representante', [AttendanceController::class, 'representativeAttendance']);
    $router->post('/asistencia/calendario', [AttendanceController::class, 'saveCalendar']);
    $router->post('/asistencia/justificaciones', [AttendanceController::class, 'storeJustification']);
    $router->post('/asistencia/justificaciones/revisar', [AttendanceController::class, 'reviewJustification']);
    $router->post('/asistencia/justificaciones/anular', [AttendanceController::class, 'annulJustification']);
    $router->post('/asistencia/sesiones', [AttendanceController::class, 'openSession']);
    $router->post('/asistencia/sesiones/anular', [AttendanceController::class, 'annulSession']);
    $router->post('/asistencia/sesiones/cerrar', [AttendanceController::class, 'closeSession']);
    $router->post('/asistencia/registros', [AttendanceController::class, 'saveRegister']);
    $router->post('/asistencia/areas', [AttendanceController::class, 'storeArea']);
    $router->post('/asistencia/areas/actualizar', [AttendanceController::class, 'updateArea']);
    $router->post('/asistencia/areas/estado', [AttendanceController::class, 'toggleArea']);
    $router->post('/asistencia/asignaturas', [AttendanceController::class, 'storeSubject']);
    $router->post('/asistencia/asignaturas/actualizar', [AttendanceController::class, 'updateSubject']);
    $router->post('/asistencia/asignaturas/estado', [AttendanceController::class, 'toggleSubject']);
    $router->post('/asistencia/materias', [AttendanceController::class, 'storeCourseSubject']);
    $router->post('/asistencia/materias/estado', [AttendanceController::class, 'toggleCourseSubject']);
    $router->post('/asistencia/materias/docentes', [AttendanceController::class, 'assignTeacher']);
    $router->post('/asistencia/materias/docentes/retirar', [AttendanceController::class, 'removeTeacher']);

    $router->get('/estudiantes', [StudentController::class, 'index']);
    $router->get('/estudiantes/buscar', [StudentController::class, 'search']);
    $router->get('/estudiantes/crear', [StudentController::class, 'create']);
    $router->get('/estudiantes/ver', [StudentController::class, 'show']);
    $router->get('/estudiantes/modulo', [StudentController::class, 'module']);
    $router->get('/estudiantes/editar', [StudentController::class, 'edit']);
    $router->post('/estudiantes', [StudentController::class, 'store']);
    $router->post('/estudiantes/modulo/actualizar', [StudentController::class, 'updateModule']);
    $router->post('/estudiantes/actualizar', [StudentController::class, 'update']);
};
